Repository microsoft/botframework-solutions, pull requests merged in 2018-12, with the labels that each got.

#448 Virtual Assistant: additional waterfall dialogs requiring telemetry client
  solutions/Virtual-Assistant/src/csharp/skills/automotiveskill/Dialogs/VehicleSettings/VehicleSettingsDialog.cs
  solutions/Virtual-Assistant/src/csharp/skills/pointofinterestskill/Dialogs/Route/RouteDialog.cs
Labels: VA

#456 [Customer Support Template] Updated template to 4.2 SDK
  templates/Customer-Support-Template/CustomerSupportTemplate/BotServices.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/CustomerSupportTemplate.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/CustomerSupportTemplate.csproj
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Account/PayBillDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Account/ResetPasswordDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Account/UpdateAccountDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Cancel/CancelDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Escalate/EscalateDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Main/MainDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Onboarding/OnboardingDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Orders/CancelOrderDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Orders/CheckOrderStatusDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Orders/FindPromoCodeDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Returns/ExchangeItemDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Returns/GetRefundStatusDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Returns/StartReturnDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Shared/CustomerSupportDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Shipping/FreeShippingDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Shipping/UpdateShippingAddressDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/SignIn/SignInDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Store/CheckItemAvailabilityDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Store/FindStoreDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Dialogs/Store/PickUpInStoreDialog.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Middleware/Telemetry/LuisTelemetryConstants.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Middleware/Telemetry/QnATelemetryConstants.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Middleware/Telemetry/TelemetryConstants.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Middleware/Telemetry/TelemetryLoggerMiddleware.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Middleware/Telemetry/TelemetryLuisRecognizer.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Middleware/Telemetry/TelemetryQnAMaker.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/PowerBI/Example PowerBI Dashboard.pbit
  templates/Customer-Support-Template/CustomerSupportTemplate/Program.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/Startup.cs
  templates/Customer-Support-Template/CustomerSupportTemplate/readme.md
Labels: cstemplate

#472 [Web Test Harness] Pass the authenticated user ID into web chat & update UI
  solutions/Virtual-Assistant/src/csharp/testharnesses/assistant-WebTest/Assistant-WebTest/Views/Home/Index.cshtml
  solutions/Virtual-Assistant/src/csharp/testharnesses/assistant-WebTest/Assistant-WebTest/Views/Home/LinkedAccounts.cshtml
  solutions/Virtual-Assistant/src/csharp/testharnesses/assistant-WebTest/Assistant-WebTest/Views/Home/WebChat.cshtml
  solutions/Virtual-Assistant/src/csharp/testharnesses/assistant-WebTest/Assistant-WebTest/Views/Shared/_Layout.cshtml
  solutions/Virtual-Assistant/src/csharp/testharnesses/assistant-WebTest/Assistant-WebTest/wwwroot/css/site.css
  solutions/Virtual-Assistant/src/csharp/testharnesses/assistant-WebTest/Assistant-WebTest/wwwroot/css/site.min.css
Labels: test harnesses

#477 [Linked Accounts] Consolidate Web Test changes
  solutions/Virtual-Assistant/src/csharp/linkedaccounts/linkedaccounts.web/Controllers/HomeController.cs
  solutions/Virtual-Assistant/src/csharp/linkedaccounts/linkedaccounts.web/Views/Home/Index.cshtml
  solutions/Virtual-Assistant/src/csharp/linkedaccounts/linkedaccounts.web/Views/Home/LinkedAccounts.cshtml
  solutions/Virtual-Assistant/src/csharp/linkedaccounts/linkedaccounts.web/Views/Shared/_Layout.cshtml
  solutions/Virtual-Assistant/src/csharp/linkedaccounts/linkedaccounts.web/appsettings.json
  solutions/Virtual-Assistant/src/csharp/linkedaccounts/linkedaccounts.web/wwwroot/css/site.css
  solutions/Virtual-Assistant/src/csharp/linkedaccounts/linkedaccounts.web/wwwroot/css/site.min.css
  solutions/Virtual-Assistant/src/csharp/testharnesses/assistant-WebTest/Assistant-WebTest/Views/Home/Index.cshtml
  solutions/Virtual-Assistant/src/csharp/testharnesses/assistant-WebTest/Assistant-WebTest/wwwroot/css/site.min.css
Labels: test harnesses

#500 [To Do] fix bugs and optimize flow
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/API/Fakes/MockData.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/API/Fakes/MockHttpClientHandlerGen.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/API/OneNoteServiceTests.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/API/OutlookServiceTests.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/Flow/AddToDoFlowTests.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/Flow/DeleteAllToDosFlowTests.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/Flow/DeleteToDoFlowTests.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/Flow/Fakes/MockData.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/Flow/Fakes/MockToDoService.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/Flow/MarkAllToDosFlowTests.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/Flow/MarkToDoFlowTests.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/Flow/ShowToDoFlowTests.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/Flow/Utterances/AddToDoFlowTestUtterances.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/Flow/Utterances/DeleteToDoFlowTestUtterances.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/Flow/Utterances/MarkToDoFlowTestUtterances.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/Flow/Utterances/ShowToDoFlowTestUtterances.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/AddToDo/AddToDoItemDialog.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/DeleteToDo/DeleteToDoItemDialog.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/DeleteToDo/Resources/DeleteToDoResponses.de.json
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/DeleteToDo/Resources/DeleteToDoResponses.es.json
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/DeleteToDo/Resources/DeleteToDoResponses.fr.json
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/DeleteToDo/Resources/DeleteToDoResponses.it.json
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/DeleteToDo/Resources/DeleteToDoResponses.json
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/DeleteToDo/Resources/DeleteToDoResponses.zh.json
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/MarkToDo/MarkToDoItemDialog.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Action.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Resources/ToDoSharedResponses.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Resources/ToDoSharedResponses.de.json
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Resources/ToDoSharedResponses.es.json
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Resources/ToDoSharedResponses.fr.json
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Resources/ToDoSharedResponses.it.json
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Resources/ToDoSharedResponses.json
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Resources/ToDoSharedResponses.zh.json
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Resources/ToDoStrings.Designer.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Resources/ToDoStrings.de.resx
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Resources/ToDoStrings.es.resx
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Resources/ToDoStrings.fr.resx
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Resources/ToDoStrings.it.resx
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Resources/ToDoStrings.resx
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/ToDoSkillDialog.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/ShowToDo/ShowToDoItemDialog.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/ToDoSkillState.cs
Labels: bug

#494 [To Do] fix constructor issues in todo skills
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/API/OutlookServiceTests.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/Flow/DeleteToDoFlowTests.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/Flow/Fakes/MockServiceManager.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/Flow/Fakes/MockTaskService.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/Flow/ShowToDoFlowTests.cs
  solutions/Virtual-Assistant/src/csharp/skills/tests/todoskilltest/Flow/ToDoBotTestBase.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/AddToDo/AddToDoItemDialog.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/DeleteToDo/DeleteToDoItemDialog.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Main/MainDialog.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/MarkToDo/MarkToDoItemDialog.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/ServiceProviderTypes.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/ToDoSkillDialog.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/ShowToDo/ShowToDoItemDialog.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/ServiceClients/IServiceManager.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/ServiceClients/ITaskService.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/ServiceClients/OneNoteService.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/ServiceClients/OutlookService.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/ServiceClients/ServiceHelper.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/ServiceClients/ServiceManager.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/Startup.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/ToDoSkill.cs
  solutions/Virtual-Assistant/src/csharp/skills/todoskill/ToDoSkillState.cs
Labels: bug
