Repository microsoft/botframework-solutions, pull requests merged in 2019-07, with the labels that each got.

#1746 use say-as in GetPointOfInterestPrompt (#1720)
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
Labels: Status: Committed

#1713 use geographyV2 and submit action in poi
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Content/PointOfInterestDetails.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Content/PointOfInterestDetailsWithRoute.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/de/pointofinterest.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/en/pointofinterest.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/es/pointofinterest.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/fr/pointofinterest.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/it/pointofinterest.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/zh/pointofinterest.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/FindParkingDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/MainDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/RouteDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Models/PointOfInterestSkillState.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Models/PointofInterestModel.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Route/RouteResponses.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Route/RouteResponses.de.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Route/RouteResponses.es.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Route/RouteResponses.fr.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Route/RouteResponses.it.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Route/RouteResponses.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Route/RouteResponses.zh.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Services/PointOfInterestLuis.cs
Labels: Status: Committed

#1635 [Calendar] Handle more actions after show meetings
  skills/src/csharp/calendarskill/calendarskill/Dialogs/CalendarSkillDialogBase.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/ConnectToMeetingDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/SummaryDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Models/CalendarSkillState.cs
Labels: Status: Committed

#1733 use image with route (#1332)
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/RouteDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/PointOfInterestSharedStrings.Designer.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/PointOfInterestSharedStrings.de.resx
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/PointOfInterestSharedStrings.es.resx
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/PointOfInterestSharedStrings.fr.resx
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/PointOfInterestSharedStrings.it.resx
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/PointOfInterestSharedStrings.resx
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/PointOfInterestSharedStrings.zh.resx
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Services/AzureMapsGeoSpatialService.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Services/FoursquareGeoSpatialService.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Services/IGeoSpatialService.cs
Labels: Status: Committed

#1743 [DO NOT MERGE] Updated ToDo skill deployment scripts
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/template.json
  skills/src/csharp/todoskill/todoskill/Deployment/Resources/LU/de/General.lu
  skills/src/csharp/todoskill/todoskill/Deployment/Resources/LU/de/ToDo.lu
  skills/src/csharp/todoskill/todoskill/Deployment/Resources/LU/en/General.lu
  skills/src/csharp/todoskill/todoskill/Deployment/Resources/LU/en/ToDo.lu
  skills/src/csharp/todoskill/todoskill/Deployment/Resources/LU/es/General.lu
  skills/src/csharp/todoskill/todoskill/Deployment/Resources/LU/es/ToDo.lu
  skills/src/csharp/todoskill/todoskill/Deployment/Resources/LU/fr/General.lu
  skills/src/csharp/todoskill/todoskill/Deployment/Resources/LU/fr/ToDo.lu
  skills/src/csharp/todoskill/todoskill/Deployment/Resources/LU/it/General.lu
  skills/src/csharp/todoskill/todoskill/Deployment/Resources/LU/it/ToDo.lu
  skills/src/csharp/todoskill/todoskill/Deployment/Resources/LU/zh/General.lu
  skills/src/csharp/todoskill/todoskill/Deployment/Resources/LU/zh/ToDo.lu
  skills/src/csharp/todoskill/todoskill/Deployment/Resources/template.json
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/luis_functions.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/qna_functions.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/todoskill/todoskill/Dialogs/MainDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/ShowToDoItemDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/ToDoSkillDialogBase.cs
  skills/src/csharp/todoskill/todoskill/Models/ToDoSkillState.cs
  skills/src/csharp/todoskill/todoskill/Services/BotSettings.cs
  skills/src/csharp/todoskill/todoskill/Services/ToDoLuis.cs
  skills/src/csharp/todoskill/todoskill/appsettings.json
  skills/src/csharp/todoskill/todoskill/cognitivemodels.json
  skills/src/csharp/todoskill/todoskilltest/Flow/Fakes/MockData.cs
  skills/src/csharp/todoskill/todoskilltest/Flow/Fakes/MockLuisRecognizer.cs
  skills/src/csharp/todoskill/todoskilltest/Flow/Utterances/AddToDoFlowTestUtterances.cs
  skills/src/csharp/todoskill/todoskilltest/Flow/Utterances/BaseTestUtterances.cs
  skills/src/csharp/todoskill/todoskilltest/Flow/Utterances/DeleteToDoFlowTestUtterances.cs
  skills/src/csharp/todoskill/todoskilltest/Flow/Utterances/MarkToDoFlowTestUtterances.cs
  skills/src/csharp/todoskill/todoskilltest/Flow/Utterances/ShowToDoFlowTestUtterances.cs
Labels: PR: unreviewed

#1800 Update CODEOWNERS
  .github/CODEOWNERS
Labels: PR: reviewed-approved

#1744 Update Email deployment scripts
  skills/src/csharp/emailskill/emailskill/Deployment/Resources/LU/de/Email.lu
  skills/src/csharp/emailskill/emailskill/Deployment/Resources/LU/de/General.lu
  skills/src/csharp/emailskill/emailskill/Deployment/Resources/LU/en/Email.lu
  skills/src/csharp/emailskill/emailskill/Deployment/Resources/LU/en/General.lu
  skills/src/csharp/emailskill/emailskill/Deployment/Resources/LU/es/Email.lu
  skills/src/csharp/emailskill/emailskill/Deployment/Resources/LU/es/General.lu
  skills/src/csharp/emailskill/emailskill/Deployment/Resources/LU/fr/Email.lu
  skills/src/csharp/emailskill/emailskill/Deployment/Resources/LU/fr/General.lu
  skills/src/csharp/emailskill/emailskill/Deployment/Resources/LU/it/Email.lu
  skills/src/csharp/emailskill/emailskill/Deployment/Resources/LU/it/General.lu
  skills/src/csharp/emailskill/emailskill/Deployment/Resources/LU/zh/Email.lu
  skills/src/csharp/emailskill/emailskill/Deployment/Resources/LU/zh/General.lu
  skills/src/csharp/emailskill/emailskill/Deployment/Resources/template.json
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/luis_functions.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/qna_functions.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/emailskill/emailskill/Dialogs/EmailSkillDialogBase.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/FindContactDialog.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/MainDialog.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/ShowEmailDialog.cs
  skills/src/csharp/emailskill/emailskill/Models/EmailSkillState.cs
  skills/src/csharp/emailskill/emailskill/Services/BotSettings.cs
  skills/src/csharp/emailskill/emailskill/Services/EmailLuis.cs
  skills/src/csharp/emailskill/emailskill/Services/GoogleAPI/GoogleClient.cs
  skills/src/csharp/emailskill/emailskill/appsettings.json
  skills/src/csharp/emailskill/emailskill/cognitivemodels.json
  skills/src/csharp/emailskill/emailskilltest/Flow/EmailBotTestBase.cs
  skills/src/csharp/emailskill/emailskilltest/Flow/Utterances/BaseTestUtterances.cs
  skills/src/csharp/emailskill/emailskilltest/Flow/Utterances/DeleteEmailUtterances.cs
  skills/src/csharp/emailskill/emailskilltest/Flow/Utterances/ForwardEmailUtterances.cs
  skills/src/csharp/emailskill/emailskilltest/Flow/Utterances/ReplyEmailUtterances.cs
  skills/src/csharp/emailskill/emailskilltest/Flow/Utterances/SendEmailUtterances.cs
  skills/src/csharp/emailskill/emailskilltest/Flow/Utterances/ShowEmailUtterances.cs
Labels: PR: reviewed-approved

#1801 Return checklist to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: reviewed-approved

#1816 Fixed some typos
  docs/readme.md
Labels: PR: reviewed-approved

#1799 Updated Automotive deployment scripts
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Resources/LU/en/General.lu
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Resources/LU/en/Settings.lu
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Resources/LU/en/SettingsDispatch.lu
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Resources/LU/en/SettingsName.lu
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Resources/LU/en/SettingsValue.lu
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Resources/template.json
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/luis_functions.ps1
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/qna_functions.ps1
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/automotiveskill/automotiveskill/Dialogs/MainDialog.cs
  skills/src/csharp/automotiveskill/automotiveskill/Dialogs/VehicleSettingsDialog.cs
  skills/src/csharp/automotiveskill/automotiveskill/Models/AutomotiveSkillState.cs
  skills/src/csharp/automotiveskill/automotiveskill/Services/SettingsDispatchLuis.cs
  skills/src/csharp/automotiveskill/automotiveskill/Services/SettingsLuis.cs
  skills/src/csharp/automotiveskill/automotiveskill/Services/SettingsNameLuis.cs
  skills/src/csharp/automotiveskill/automotiveskill/Services/SettingsValueLuis.cs
  skills/src/csharp/automotiveskill/automotiveskill/cognitivemodels.json
  skills/src/csharp/automotiveskill/automotiveskilltest/Flow/AutomotiveSkillTestBase.cs
  skills/src/csharp/automotiveskill/automotiveskilltest/Flow/Fakes/MockLuisRecognizer.cs
  skills/src/csharp/automotiveskill/automotiveskilltest/Flow/Fakes/MockVehicleSettingsIntent.cs
  skills/src/csharp/automotiveskill/automotiveskilltest/Flow/Fakes/MockVehicleSettingsNameIntent.cs
  skills/src/csharp/automotiveskill/automotiveskilltest/Flow/Fakes/MockVehicleSettingsValueIntent.cs
Labels: PR: reviewed-approved

#1820 Updated weather deployment scripts
  skills/src/csharp/experimental/weatherskill/Deployment/Resources/template.json
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/luis_functions.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/qna_functions.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/weatherskill/Services/AccuweatherService.cs
  skills/src/csharp/experimental/weatherskill/Services/BotSettings.cs
  skills/src/csharp/experimental/weatherskill/appsettings.json
Labels: PR: reviewed-approved

#1821 Delete CODEOWNERS
  .github/CODEOWNERS
Labels: PR: reviewed-approved

#1798 Add Australia LUIS reference to docs
  docs/tutorials/assistantandskilldeploymentsteps.md
  docs/tutorials/csharp/virtualassistant.md
Labels: PR: reviewed-approved

#1814 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: PR: reviewed-approved

#1818 Update reservation skill deployment scripts
  skills/src/csharp/experimental/restaurantbooking/Deployment/Resources/LU/en/General.lu
  skills/src/csharp/experimental/restaurantbooking/Deployment/Resources/LU/en/Reservation.lu
  skills/src/csharp/experimental/restaurantbooking/Deployment/Resources/template.json
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/luis_functions.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/publish.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/qna_functions.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/restaurantbooking/Dialogs/BookingDialog.cs
  skills/src/csharp/experimental/restaurantbooking/Dialogs/MainDialog.cs
  skills/src/csharp/experimental/restaurantbooking/Dialogs/SkillDialogBase.cs
  skills/src/csharp/experimental/restaurantbooking/RestaurantBooking.sln
  skills/src/csharp/experimental/restaurantbooking/Services/BotSettings.cs
  skills/src/csharp/experimental/restaurantbooking/Utilities/UrlResolver.cs
  skills/src/csharp/experimental/restaurantbooking/appsettings.json
  skills/src/csharp/experimental/restaurantbooking/cognitivemodels.json
Labels: PR: reviewed-approved

#1815 Updated News deployment scripts
  skills/src/csharp/experimental/newsskill/Deployment/Resources/LU/en/General.lu
  skills/src/csharp/experimental/newsskill/Deployment/Resources/LU/en/News.lu
  skills/src/csharp/experimental/newsskill/Deployment/Resources/template.json
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/luis_functions.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/qna_functions.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/newsskill/Dialogs/FavoriteTopicsDialog.cs
  skills/src/csharp/experimental/newsskill/Dialogs/FindArticlesDialog.cs
  skills/src/csharp/experimental/newsskill/Dialogs/MainDialog.cs
  skills/src/csharp/experimental/newsskill/Dialogs/NewsDialogBase.cs
  skills/src/csharp/experimental/newsskill/Dialogs/TrendingArticlesDialog.cs
  skills/src/csharp/experimental/newsskill/Models/NewsSkillState.cs
  skills/src/csharp/experimental/newsskill/Services/BotSettings.cs
  skills/src/csharp/experimental/newsskill/Services/NewsLuis.cs
  skills/src/csharp/experimental/newsskill/appsettings.json
  skills/src/csharp/experimental/newsskill/cognitivemodels.json
Labels: PR: reviewed-approved

#1794 poi shows single route directly (#1663)
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/MainDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/RouteDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/POISharedResponses.de.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/POISharedResponses.es.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/POISharedResponses.fr.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/POISharedResponses.it.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/POISharedResponses.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/POISharedResponses.zh.json
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/PointOfInterestDialogTests.cs
Labels: PR: reviewed-approved

#1819 Update search skill deployment scripts
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Resources/template.json
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/luis_functions.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/qna_functions.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Dialogs/SearchDialog.cs
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Services/BotSettings.cs
Labels: PR: reviewed-approved

#1822 Create auto_assign.yml
  .github/auto_assign.yml
Labels: PR: reviewed-approved

#1829 Yuesu/skills preview merge to skills-preview
  skills/src/csharp/calendarskill/calendarskill/Adapters/AdapterWithErrorHandler.cs
  skills/src/csharp/calendarskill/calendarskill/Bots/DialogBot.cs
  skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
  skills/src/csharp/calendarskill/calendarskill/Dialogs/CreateEventDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/FindContactDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/MainDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Models/DialogModel/CalendarSkillState.cs
  skills/src/csharp/calendarskill/calendarskill/Prompts/TimePrompt.cs
  skills/src/csharp/calendarskill/calendarskill/Responses/CreateEvent/CreateEventDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/Main/MainDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/Main/MainDialog.zh-cn.lg
  skills/src/csharp/calendarskill/calendarskill/Services/CalendarLuis.cs
  skills/src/csharp/calendarskill/calendarskill/Startup.cs
Labels: PR: unreviewed

#1825 [TypeScript][Virtual Assistant Template] Add Skill folder
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/Skills/en/automotive.lu
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/Skills/en/calendar.lu
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/Skills/en/email.lu
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/Skills/en/news.lu
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/Skills/en/pointofinterest.lu
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/Skills/en/restaurant.lu
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/Skills/en/todo.lu
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/Skills/en/automotive.lu
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/Skills/en/calendar.lu
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/Skills/en/email.lu
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/Skills/en/news.lu
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/Skills/en/pointofinterest.lu
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/Skills/en/restaurant.lu
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/Skills/en/todo.lu
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/package-lock.json
Labels: PR: reviewed-approved

#1823 Deployment Cleanup for templates
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Resources/template.json
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/deploy.ps1
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/luis_functions.ps1
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/update_cognitive_models.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Resources/template.json
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/deploy.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/luis_functions.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/update_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/Skills/en/automotive.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/Skills/en/calendar.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/Skills/en/email.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/Skills/en/news.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/Skills/en/pointofinterest.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/Skills/en/restaurant.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/Skills/en/todo.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/template.json
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/luis_functions.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/update_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/Skills/en/automotive.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/Skills/en/calendar.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/Skills/en/email.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/Skills/en/news.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/Skills/en/pointofinterest.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/Skills/en/restaurant.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/Skills/en/todo.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/template.json
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/deploy.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/luis_functions.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/update_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VAProjectTemplate.vstemplate
Labels: PR: reviewed-approved

#1813 Remove hardcoded values in ARM template
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/template.json
Labels: PR: reviewed-approved

#1834 Reduce QnA KB items across all templates
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/de/chitchat.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/de/faq.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/en/faq.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/es/chitchat.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/es/faq.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/fr/chitchat.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/fr/faq.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/it/chitchat.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/it/faq.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/zh/chitchat.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/zh/faq.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/QnA/de/chitchat.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/QnA/de/faq.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/QnA/en/faq.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/QnA/es/chitchat.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/QnA/es/faq.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/QnA/fr/chitchat.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/QnA/fr/faq.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/QnA/it/chitchat.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/QnA/it/faq.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/QnA/zh/chitchat.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/QnA/zh/faq.lu
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/QnA/de/faq.lu
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/QnA/en/faq.lu
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/QnA/es/faq.lu
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/QnA/fr/faq.lu
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/QnA/it/faq.lu
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/QnA/zh/chitchat.lu
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/QnA/zh/faq.lu
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/QnA/de/faq.lu
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/QnA/en/faq.lu
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/QnA/es/faq.lu
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/QnA/fr/faq.lu
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/QnA/it/faq.lu
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/QnA/zh/chitchat.lu
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/QnA/zh/faq.lu
Labels: PR: reviewed-approved

#1840 [Virtual Assistant] Remove Linked Accounts action in IntroCards
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Content/NewUserGreeting.de.json
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Content/NewUserGreeting.es.json
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Content/NewUserGreeting.fr.json
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Content/NewUserGreeting.it.json
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Content/NewUserGreeting.zh.json
  templates/Virtual-Assistant-Template/csharp/Template/VA/Content/NewUserGreeting.de.json
  templates/Virtual-Assistant-Template/csharp/Template/VA/Content/NewUserGreeting.es.json
  templates/Virtual-Assistant-Template/csharp/Template/VA/Content/NewUserGreeting.fr.json
  templates/Virtual-Assistant-Template/csharp/Template/VA/Content/NewUserGreeting.it.json
  templates/Virtual-Assistant-Template/csharp/Template/VA/Content/NewUserGreeting.zh.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/content/NewUserGreeting.de.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/content/NewUserGreeting.es.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/content/NewUserGreeting.fr.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/content/NewUserGreeting.it.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/content/NewUserGreeting.zh.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/content/NewUserGreeting.de.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/content/NewUserGreeting.es.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/content/NewUserGreeting.fr.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/content/NewUserGreeting.it.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/content/NewUserGreeting.zh.json
Labels: PR: reviewed-approved

#1841 [TypeScript][Templates/Samples] Replace the placeholder's paths with the root of the project
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/pipeline/_sample-assistant.yml
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/pipeline/_sample-skill.yml
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/pipeline/sample-assistant.yml
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/pipeline/sample-skill.yml
Labels: PR: reviewed-approved

#1842 [TypeScript][BotBuilder Libs] Migrate latest functionalities
  lib/typescript/botbuilder-skills/src/http/skillHttpAdapter.ts
  lib/typescript/botbuilder-skills/src/http/skillHttpTransport.ts
  lib/typescript/botbuilder-skills/src/models/skillEvents.ts
  lib/typescript/botbuilder-skills/src/skillCallingRequestHandler.ts
  lib/typescript/botbuilder-skills/src/skillContext.ts
  lib/typescript/botbuilder-skills/src/skillDialog.ts
  lib/typescript/botbuilder-skills/src/skillManifestGenerator.ts
  lib/typescript/botbuilder-skills/src/skillMiddleware.ts
  lib/typescript/botbuilder-skills/src/websocket/skillWebSocketBotAdapter.ts
  lib/typescript/botbuilder-skills/src/websocket/skillWebSocketRequestHandler.ts
  lib/typescript/botbuilder-skills/src/websocket/skillWebSocketTransport.ts
  lib/typescript/botbuilder-skills/test/helpers/skillDialogTestBase.js
  lib/typescript/botbuilder-skills/test/mocks/mockSkillTransport.js
  lib/typescript/botbuilder-skills/test/skillDialogInvocation.test.js
  lib/typescript/botbuilder-skills/test/skillDialogSlotFilling.test.js
  lib/typescript/botbuilder-skills/test/skillMiddleware.test.js
  lib/typescript/botbuilder-solutions/package.json
  lib/typescript/botbuilder-solutions/src/authentication/authenticationResponses.ts
  lib/typescript/botbuilder-solutions/src/authentication/multiProviderAuthDialog.ts
  lib/typescript/botbuilder-solutions/src/authentication/providerTokenResponse.ts
  lib/typescript/botbuilder-solutions/src/botSettings.ts
  lib/typescript/botbuilder-solutions/src/dialogs/routerDialog.ts
  lib/typescript/botbuilder-solutions/src/extensions/activityExtensions.ts
  lib/typescript/botbuilder-solutions/src/middleware/consoleOutputMiddleware.ts
  lib/typescript/botbuilder-solutions/src/middleware/contentModeratorMiddleware.ts
  lib/typescript/botbuilder-solutions/src/middleware/eventDebuggerMiddleware.ts
  lib/typescript/botbuilder-solutions/src/middleware/index.ts
  lib/typescript/botbuilder-solutions/src/middleware/setSpeakMiddleware.ts
  lib/typescript/botbuilder-solutions/src/proactive/proactiveStateMiddleware.ts
  lib/typescript/botbuilder-solutions/src/responses/card.ts
  lib/typescript/botbuilder-solutions/src/responses/speechUtility.ts
  lib/typescript/botbuilder-solutions/test/speechUtility.test.js
  lib/typescript/common/config/rush/npm-shrinkwrap.json
Labels: PR: reviewed-approved

#1729 inject all body items in GetCardResponse (#1710)
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Responses/ResponseManager.cs
Labels: PR: reviewed-approved

#1817 [TypeScript][Generator] Edit Next Step messages
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/index.js
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/index.js
Labels: PR: reviewed-approved

#1843 VA Template - New Deployment Features
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Adapters/DefaultWebSocketAdapter.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/parameters.template.json
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/template.json
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/update_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Services/DispatchLuis.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Services/GeneralLuis.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/cognitivemodels.json
  templates/Virtual-Assistant-Template/csharp/Template/VA/Adapters/DefaultAdapter.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Adapters/DefaultWebSocketAdapter.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/LU/en/general.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/parameters.template.json
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/template.json
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/deploy.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/update_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Services/DispatchLuis.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Services/GeneralLuis.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/cognitivemodels.json
  templates/Virtual-Assistant-Template/csharp/Template/VAProjectTemplate.vstemplate
Labels: PR: reviewed-approved

#1845 Skills - New deployment features
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Resources/parameters.template.json
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Resources/template.json
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/automotiveskill/automotiveskill/cognitivemodels.json
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/parameters.template.json
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/template.json
  skills/src/csharp/calendarskill/calendarskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/calendarskill/calendarskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/calendarskill/calendarskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/calendarskill/calendarskill/cognitivemodels.json
  skills/src/csharp/emailskill/emailskill/Deployment/Resources/parameters.template.json
  skills/src/csharp/emailskill/emailskill/Deployment/Resources/template.json
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/emailskill/emailskill/cognitivemodels.json
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Resources/parameters.template.json
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Resources/template.json
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/cognitivemodels.json
  skills/src/csharp/experimental/newsskill/Deployment/Resources/parameters.template.json
  skills/src/csharp/experimental/newsskill/Deployment/Resources/template.json
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/newsskill/cognitivemodels.json
  skills/src/csharp/experimental/restaurantbooking/Deployment/Resources/parameters.template.json
  skills/src/csharp/experimental/restaurantbooking/Deployment/Resources/template.json
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/restaurantbooking/cognitivemodels.json
  skills/src/csharp/experimental/weatherskill/Deployment/Resources/parameters.template.json
  skills/src/csharp/experimental/weatherskill/Deployment/Resources/template.json
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/weatherskill/cognitivemodels.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/parameters.template.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/template.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/pointofinterestskill/pointofinterestskill/cognitivemodels.json
  skills/src/csharp/todoskill/todoskill/Deployment/Resources/parameters.template.json
  skills/src/csharp/todoskill/todoskill/Deployment/Resources/template.json
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/todoskill/todoskill/cognitivemodels.json
Labels: PR: reviewed-approved

#1831 MultiProviderAuthDialog uses ListStyle.Auto (#1830)
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Authentication/MultiProviderAuthDialog.cs
Labels: PR: reviewed-approved

#1867 Shzhen/test todo2
  skills/src/csharp/todoskill/todoskill/Dialogs/AddToDoItemDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/DeleteToDoItemDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/MainDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/MarkToDoItemDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/ShowToDoItemDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/ToDoSkillDialogBase.cs
  skills/src/csharp/todoskill/todoskill/Resources/AddToDoCardTexts.lg
  skills/src/csharp/todoskill/todoskill/Resources/AddToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/Card.lg
  skills/src/csharp/todoskill/todoskill/Resources/CardSummaryTexts.lg
  skills/src/csharp/todoskill/todoskill/Resources/DeleteToDoCardTexts.lg
  skills/src/csharp/todoskill/todoskill/Resources/DeleteToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/MarkToDoCardTexts.lg
  skills/src/csharp/todoskill/todoskill/Resources/MarkToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/ResponsesAndTexts.lg
  skills/src/csharp/todoskill/todoskill/Resources/ShowToDoCardTexts.lg
  skills/src/csharp/todoskill/todoskill/Resources/ShowToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/ToDoMainResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/ToDoSharedResponses.lg
  skills/src/csharp/todoskill/todoskill/Services/ServiceHelper.cs
  skills/src/csharp/todoskill/todoskill/Utilities/ToDoCommonUtil.cs
Labels: PR: unreviewed

#1828 Latest Android Updates
  docs/media/android_project_overview.jpg
  docs/media/android_screenshot_main_ui.png
  docs/media/android_screenshot_navbar.png
  docs/media/android_screenshot_settings.png
  docs/media/android_studio_credentials_debug.png
  solutions/android/VirtualAssistantClient/app/src/debug/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/configuration/DefaultConfiguration.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/MainActivity.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/settings/SettingsActivity.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/service/LocationProvider.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/service/SpeechService.java
  solutions/android/VirtualAssistantClient/app/src/main/res/layout/activity_settings.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/menu/nav_drawer_menu.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/values/strings.xml
  solutions/android/VirtualAssistantClient/build.gradle
  solutions/android/VirtualAssistantClient/directlinespeech/src/main/java/client/model/BotConnectorActivity.java
  solutions/android/VirtualAssistantClient/directlinespeech/src/main/java/client/model/InputHints.java
  solutions/android/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/model/Configuration.java
  solutions/android/VirtualAssistantClient/readme.md
Labels: PR: unreviewed

#1854 Updated libs to 4.5.0 sdk
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Microsoft.Bot.Builder.Skills.csproj
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Microsoft.Bot.Builder.Solutions.csproj
Labels: PR: reviewed-approved

#1855 Skill template bug fixes
  templates/Skill-Template/csharp/Sample/SkillSample/Dialogs/SkillDialogBase.cs
  templates/Skill-Template/csharp/Sample/SkillSample/Models/SkillState.cs
  templates/Skill-Template/csharp/Template/Skill/Dialogs/SkillDialogBase.cs
  templates/Skill-Template/csharp/Template/Skill/Models/SkillState.cs
Labels: PR: reviewed-approved

#1870 Fix Skill app settings from refactor
  skills/src/csharp/automotiveskill/automotiveskill/appsettings.json
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/appsettings.json
Labels: PR: reviewed-approved

#1869 Skills - LU File Name Capitalization Fix
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/de/Calendar.lu
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/de/General.lu
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/en/Calendar.lu
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/en/General.lu
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/es/Calendar.lu
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/es/General.lu
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/fr/Calendar.lu
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/fr/General.lu
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/it/Calendar.lu
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/it/General.lu
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/zh/Calendar.lu
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/zh/General.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/de/General.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/de/PointOfInterest.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/en/General.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/en/PointOfInterest.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/es/General.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/es/PointOfInterest.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/fr/General.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/fr/PointOfInterest.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/it/General.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/it/PointOfInterest.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/zh/General.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/zh/PointOfInterest.lu
Labels: PR: reviewed-approved

#1851 [TypeScript][BotBuilder-Libs] Fix issue with test and code coverage tasks in YAML files
  yaml/typescript/botbuilder-skills.yml
  yaml/typescript/botbuilder-solutions.yml
Labels: PR: reviewed-approved

#1874 [Docs]Update bing search skill and power bi doc
  docs/reference/analytics/powerbi.md
  docs/reference/skills/experimental.md
Labels: PR: unreviewed

#1876 Fix To-Do Skill input hints
  skills/src/csharp/todoskill/todoskill/Responses/Main/ToDoMainResponses.de.json
  skills/src/csharp/todoskill/todoskill/Responses/Main/ToDoMainResponses.es.json
  skills/src/csharp/todoskill/todoskill/Responses/Main/ToDoMainResponses.fr.json
  skills/src/csharp/todoskill/todoskill/Responses/Main/ToDoMainResponses.it.json
  skills/src/csharp/todoskill/todoskill/Responses/Main/ToDoMainResponses.json
  skills/src/csharp/todoskill/todoskill/Responses/Main/ToDoMainResponses.zh.json
Labels: PR: reviewed-approved, Project: Skills

#1887 Updated lib to sdk 4.5.1
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Microsoft.Bot.Builder.Skills.csproj
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Microsoft.Bot.Builder.Solutions.csproj
Labels: Changelog: Libraries, PR: reviewed-approved

#1885 [Botskills] Support of path with spaces in the execution of external commands
  tools/botskills/src/functionality/connectSkill.ts
  tools/botskills/src/functionality/refreshSkill.ts
  tools/botskills/test/connect.test.js
  tools/botskills/test/refresh.test.js
Labels: Changelog: CLI, PR: reviewed-approved, PR: unreviewed

#1886 [TypeScript][Botskills] Fix dispatchName argument
  tools/botskills/src/botskills-connect.ts
  tools/botskills/src/botskills-disconnect.ts
  tools/botskills/src/botskills-refresh.ts
  tools/botskills/src/botskills-update.ts
Labels: Changelog: CLI, PR: reviewed-approved, PR: unreviewed

#1857 VA Template - Updated to 4.5.1 and new streaming extensions
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Adapters/DefaultWebSocketAdapter.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Controllers/BotController.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
  templates/Virtual-Assistant-Template/csharp/Template/VA.Tests/VA.Tests.csproj
  templates/Virtual-Assistant-Template/csharp/Template/VA/Adapters/DefaultWebSocketAdapter.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Controllers/BotController.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/VA.csproj
Labels: Changelog: Templates, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#1858 Skill template - Updated to SDK 4.5.1
  skills/src/csharp/calendarskill/calendarskilltest/Flow/CalendarBotTestBase.cs
  templates/Skill-Template/csharp/Sample/SkillSample.Tests/SkillSample.Tests.csproj
  templates/Skill-Template/csharp/Sample/SkillSample/SkillSample.csproj
  templates/Skill-Template/csharp/Template/Skill.Tests/Skill.Tests.csproj
  templates/Skill-Template/csharp/Template/Skill/Skill.csproj
Labels: Changelog: Templates, PR: reviewed-approved, PR: unreviewed

#1859 Skills - Updated to sdk 4.5.1
  skills/src/csharp/automotiveskill/automotiveskill/AutomotiveSkill.csproj
  skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
  skills/src/csharp/calendarskill/calendarskilltest/Flow/CalendarBotTestBase.cs
  skills/src/csharp/emailskill/emailskill/EmailSkill.csproj
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/BingSearchSkill.csproj
  skills/src/csharp/experimental/newsskill/NewsSkill.csproj
  skills/src/csharp/experimental/restaurantbooking/RestaurantBooking.csproj
  skills/src/csharp/experimental/weatherskill/WeatherSkill.csproj
  skills/src/csharp/pointofinterestskill/pointofinterestskill/PointOfInterestSkill.csproj
  skills/src/csharp/todoskill/todoskill/ToDoSkill.csproj
Labels: Changelog: Skills, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#1875 [Part 1, lib change in future branch] Add fallback event support
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/Mocks/MockSkillTransport.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/SkillDialogTest.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Dialogs/DispatchDialog.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/ISkillIntentRecognizer.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/ISkillTransport.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Models/DispatchIntent.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Models/SkillEvents.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillCallingRequestHandler.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialog.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillSwitchConfirmOption.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketBotAdapter.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketTransport.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/IFallbackRequestProvider.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.Designer.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.de.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.es.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.fr.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.it.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.zh.resx
Labels: Changelog: Libraries, PR: reviewed-approved, PR: unreviewed

#1899 Update skilldialog test data
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/TestData/luisCalendarModelResponse.json
Labels: PR: reviewed-approved

#1898 use ShortTimePattern instead of hardcoded ones
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions.tests/Extensions/DateTimeExTests.cs
Labels: PR: reviewed-approved

#1908 Fixed Links in Overview Documentation
  docs/overview/analytics.md
Labels: PR: reviewed-approved

#1904 speechenablement.md: Update text related to Azure regions
  docs/howto/assistant/csharp/speechenablement.md
Labels: PR: reviewed-approved

#1896 Latest Android Updates
  solutions/android/VirtualAssistantClient/app/build.gradle
  solutions/android/VirtualAssistantClient/app/src/debug/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/configuration/DefaultConfiguration.java
  solutions/android/VirtualAssistantClient/app/src/main/AndroidManifest.xml
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/BaseActivity.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/MainActivity.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/actionslist/ActionsViewholder.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/chatlist/ChatAdapter.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/chatlist/ViewholderBot.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/chatlist/ViewholderUser.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/settings/ColorFlag.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/settings/SettingsActivity.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/service/SpeechService.java
  solutions/android/VirtualAssistantClient/app/src/main/res/drawable/flag.png
  solutions/android/VirtualAssistantClient/app/src/main/res/drawable/shape_rect_round_corners_white.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/layout/activity_main.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/layout/activity_settings.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/layout/item_chat_bot.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/layout/item_chat_user.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/layout/item_color_flag.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/values/colors.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/values/strings.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/values/styles.xml
  solutions/android/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/model/Configuration.java
Labels: Changelog: Android, PR: reviewed-approved

#1902 remove obsolete event from doc
  docs/reference/skills/pointofinterest.md
Labels: Changelog: Skills, PR: reviewed-approved

#1889 add helper to wrap paths with quotes and update tests
  tools/botskills/src/functionality/connectSkill.ts
  tools/botskills/src/functionality/refreshSkill.ts
  tools/botskills/src/utils/index.ts
  tools/botskills/src/utils/sanitizationUtils.ts
Labels: Changelog: CLI, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#1927 Updated to IBot Implementation across projects
  skills/src/csharp/automotiveskill/automotiveskill/Bots/DialogBot.cs
  skills/src/csharp/calendarskill/calendarskill/Bots/DialogBot.cs
  skills/src/csharp/emailskill/emailskill/Bots/DialogBot.cs
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Bots/DialogBot.cs
  skills/src/csharp/experimental/newsskill/Bots/DialogBot.cs
  skills/src/csharp/experimental/restaurantbooking/Bots/DialogBot.cs
  skills/src/csharp/experimental/weatherskill/Bots/DialogBot.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Bots/DialogBot.cs
  skills/src/csharp/todoskill/todoskill/Bots/DialogBot.cs
  templates/Skill-Template/csharp/Sample/SkillSample/Bots/DialogBot.cs
  templates/Skill-Template/csharp/Template/Skill/Bots/DialogBot.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Bots/DialogBot.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Bots/DialogBot.cs
Labels: PR: reviewed-approved

#1881 Fix test for Virtual Assistant on non-Windows machines
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/Utilities/ChitchatTestUtil.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/Utilities/FaqTestUtil.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA.Tests/Utilities/ChitchatTestUtil.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA.Tests/Utilities/FaqTestUtil.cs
Labels: Changelog: Templates, PR: reviewed-approved, PR: unreviewed

#1929 Remove autosave state middleware
  skills/src/csharp/automotiveskill/automotiveskill/Adapters/AutomotiveSkillWebSocketBotAdapter.cs
  skills/src/csharp/automotiveskill/automotiveskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/calendarskill/calendarskill/Adapters/CalendarSkillWebSocketBotAdapter.cs
  skills/src/csharp/calendarskill/calendarskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/emailskill/emailskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/emailskill/emailskill/Adapters/EmailSkillWebSocketBotAdapter.cs
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Adapters/CustomSkillAdapter.cs
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/experimental/newsskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/experimental/newsskill/Adapters/NewsSkillWebSocketBotAdapter.cs
  skills/src/csharp/experimental/restaurantbooking/Adapters/DefaultAdapter.cs
  skills/src/csharp/experimental/restaurantbooking/Adapters/RestaurantSkillWebSocketBotAdapter.cs
  skills/src/csharp/experimental/weatherskill/Adapters/CustomSkillAdapter.cs
  skills/src/csharp/experimental/weatherskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Adapters/POISkillWebSocketBotAdapter.cs
  skills/src/csharp/todoskill/todoskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/todoskill/todoskill/Adapters/ToDoSkillWebSocketBotAdapter.cs
  templates/Skill-Template/csharp/Sample/SkillSample/Adapters/CustomSkillAdapter.cs
  templates/Skill-Template/csharp/Sample/SkillSample/Adapters/DefaultAdapter.cs
  templates/Skill-Template/csharp/Template/Skill/Adapters/CustomSkillAdapter.cs
  templates/Skill-Template/csharp/Template/Skill/Adapters/DefaultAdapter.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Adapters/DefaultWebSocketAdapter.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Adapters/DefaultAdapter.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Adapters/DefaultWebSocketAdapter.cs
Labels: PR: reviewed-approved

#1915 [Botskills] Implement logger tests
  tools/botskills/test/logger.test.js
Labels: Changelog: CLI, PR: reviewed-approved

#1901 [Botskills] Implement utils tests
  tools/botskills/src/utils/authenticationUtils.ts
  tools/botskills/src/utils/childProcessUtils.ts
  tools/botskills/src/utils/validationUtils.ts
  tools/botskills/test/authentication.test.js
  tools/botskills/test/childProcess.test.js
  tools/botskills/test/connect.test.js
  tools/botskills/test/disconnect.test.js
  tools/botskills/test/list.test.js
  tools/botskills/test/mocks/appShowReplyUrl/emptyAppShowReplyUrl.json
  tools/botskills/test/mocks/appsettings/authConnectionAppsettings.json
  tools/botskills/test/mocks/appsettings/noAuthConnectionAppSettings.json
  tools/botskills/test/mocks/azureAuthSettings/emptyAuthSettings.json
  tools/botskills/test/mocks/azureAuthSettings/filledAuthSettings.json
  tools/botskills/test/mocks/skills/azureActiveDirectoryV2AuthenticationManifest.json
  tools/botskills/test/mocks/skills/googleAuthenticationManifest.json
  tools/botskills/test/sanitization.test.js
  tools/botskills/test/update.test.js
  tools/botskills/test/validation.test.js
Labels: Changelog: CLI, PR: reviewed-approved, PR: unreviewed

#1926 [Automotive] Fix LU file reference in manifest
  skills/src/csharp/automotiveskill/automotiveskill/manifestTemplate.json
Labels: Changelog: Skills, PR: reviewed-approved, PR: unreviewed

#1930 Template updates + luis_functions fix
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/luis_functions.ps1
  skills/src/csharp/calendarskill/calendarskill/Deployment/Scripts/luis_functions.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/luis_functions.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/luis_functions.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/luis_functions.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/luis_functions.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/luis_functions.ps1
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Scripts/luis_functions.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/luis_functions.ps1
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/luis_functions.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/luis_functions.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/luis_functions.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/luis_functions.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Startup.cs
Labels: PR: reviewed-approved

#1940 Set '--output json' on az cli commands across projects + publish.ps1 prompts
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/calendarskill/calendarskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/calendarskill/calendarskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/calendarskill/calendarskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/publish.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/publish.ps1
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/deploy.ps1
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/publish.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/deploy.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/publish.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/publish.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/deploy.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/publish.ps1
Labels: PR: reviewed-approved

#1897 use OpenDefaultApp instead of ActiveRoute.Directions (#1443) (#1864)
  docs/reference/skills/pointofinterest.md
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/MainDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/RouteDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Models/PointOfInterestSkillState.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Services/AzureMapsGeoSpatialService.cs
Labels: Changelog: Skills, PR: reviewed-approved

#1938 [C#][DevOps] Add YAML file for Skill-Sample
  templates/Skill-Template/csharp/Sample/SkillSample.Tests/SkillSample.Tests.csproj
  yaml/csharp/skill-sample.yml
Labels: PR: reviewed-approved

#1934 updates to lib
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/SkillDialogTestBase.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/SkillMiddlewareTests.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Skills/InProcAdapter.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Skills/SkillDefinition.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Skills/SkillDialogOptions.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Skills/SkillEvent.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Skills/SkillRouter.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Testing/DefaultTestAdapter.cs
Labels: PR: reviewed-approved

#1951 Tedlee/update streaming lib
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Microsoft.Bot.Builder.Skills.csproj
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Microsoft.Bot.Builder.Skills.nuspec
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Protocol/RouteAction.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Protocol/RouteContext.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Protocol/Router.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillCallingRequestHandler.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketAdapter.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketBotAdapter.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketRequestHandler.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketTransport.cs
Labels: PR: reviewed-approved

#1953 [VA Template] Fix LUIS and QnA names in DispatchLuis
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/Utilities/DispatchTestUtil.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Services/DispatchLuis.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA.Tests/Utilities/DispatchTestUtil.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Dialogs/MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Services/DispatchLuis.cs
Labels: PR: reviewed-approved

#1955 update skills lib version 4.5.2
  skills/src/csharp/Skills.sln
  skills/src/csharp/automotiveskill/automotiveskill/AutomotiveSkill.csproj
  skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
  skills/src/csharp/emailskill/emailskill/EmailSkill.csproj
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/BingSearchSkill.csproj
  skills/src/csharp/experimental/newsskill/NewsSkill.csproj
  skills/src/csharp/experimental/restaurantbooking/RestaurantBooking.csproj
  skills/src/csharp/experimental/weatherskill/WeatherSkill.csproj
  skills/src/csharp/pointofinterestskill/pointofinterestskill/PointOfInterestSkill.csproj
  skills/src/csharp/todoskill/todoskill/ToDoSkill.csproj
  templates/Skill-Template/csharp/Sample/SkillSample/SkillSample.csproj
  templates/Skill-Template/csharp/Template/Skill/Skill.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
  templates/Virtual-Assistant-Template/csharp/Template/VA/VA.csproj
Labels: PR: reviewed-approved

#1957 Revert "[VA Template] Fix LUIS and QnA names in DispatchLuis"
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/Utilities/DispatchTestUtil.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Services/DispatchLuis.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA.Tests/Utilities/DispatchTestUtil.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Dialogs/MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Services/DispatchLuis.cs
Labels: PR: reviewed-approved

#1958 VSIX template bug fixes
  templates/Skill-Template/csharp/Template/Microsoft.Bot.Builder.Solutions.SkillTemplate.nuspec
  templates/Skill-Template/csharp/Template/Skill.Tests/SkillTestTemplate.vstemplate
  templates/Skill-Template/csharp/Template/Skill/Adapters/CustomSkillAdapter.cs
  templates/Skill-Template/csharp/Template/Skill/SkillProjectTemplate.vstemplate
  templates/Skill-Template/csharp/Template/skill.vstemplate
  templates/Virtual-Assistant-Template/csharp/Template/Microsoft.Bot.Builder.Solutions.VirtualAssistantTemplate.nuspec
  templates/Virtual-Assistant-Template/csharp/Template/VA.Tests/VATestTemplate.vstemplate
  templates/Virtual-Assistant-Template/csharp/Template/VA/VAProjectTemplate.vstemplate
  templates/Virtual-Assistant-Template/csharp/Template/va.vstemplate
Labels: PR: reviewed-approved

#1966 revert skills lib to not use a customized nuspec file to make its dependencies streamlined
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Microsoft.Bot.Builder.Skills.csproj
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Microsoft.Bot.Builder.Skills.nuspec
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Models/SkillDefinition.cs
Labels: PR: reviewed-approved

#1967 Various release fixes (update script, capitalization)
  skills/src/csharp/automotiveskill/automotiveskill/AutomotiveSkill.csproj
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
  skills/src/csharp/calendarskill/calendarskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/emailskill/emailskill/EmailSkill.csproj
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/BingSearchSkill.csproj
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/newsskill/NewsSkill.csproj
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/restaurantbooking/RestaurantBooking.csproj
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/weatherskill/WeatherSkill.csproj
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/pointofinterestskill/pointofinterestskill/PointOfInterestSkill.csproj
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/todoskill/todoskill/ToDoSkill.csproj
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/update_cognitive_models.ps1
  templates/Skill-Template/csharp/Sample/SkillSample/SkillSample.csproj
  templates/Skill-Template/csharp/Template/Skill.Tests/Skill.Tests.csproj
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/update_cognitive_models.ps1
  templates/Skill-Template/csharp/Template/Skill/Skill.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/BotTestBase.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/Utilities/DispatchTestUtil.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/LU/de/General.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/LU/en/General.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/LU/es/General.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/LU/fr/General.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/LU/it/General.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/LU/zh/General.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/de/Chitchat.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/de/Faq.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/en/Chitchat.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/en/Faq.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/es/Chitchat.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/es/Faq.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/fr/Chitchat.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/fr/Faq.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/it/Chitchat.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/it/Faq.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/zh/Chitchat.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/zh/Faq.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/update_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Services/DispatchLuis.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
  templates/Virtual-Assistant-Template/csharp/Template/VA.Tests/BotTestBase.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA.Tests/Utilities/DispatchTestUtil.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/QnA/en/chitchat.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/QnA/en/faq.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/update_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Dialogs/MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Services/DispatchLuis.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/VA.csproj
Labels: PR: reviewed-approved

#1970 lg finalized
  skills/src/csharp/todoskill/todoskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/todoskill/todoskill/Bots/DialogBot.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/AddToDoItemDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/DeleteToDoItemDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/MainDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/MarkToDoItemDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/ShowToDoItemDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/ToDoSkillDialogBase.cs
  skills/src/csharp/todoskill/todoskill/Resources/AddToDoCardTexts.lg
  skills/src/csharp/todoskill/todoskill/Resources/AddToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/Card.lg
  skills/src/csharp/todoskill/todoskill/Resources/CardSummaryTexts.lg
  skills/src/csharp/todoskill/todoskill/Resources/DeleteToDoCardTexts.lg
  skills/src/csharp/todoskill/todoskill/Resources/DeleteToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/MarkToDoCardTexts.lg
  skills/src/csharp/todoskill/todoskill/Resources/MarkToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/ResponsesAndTexts.lg
  skills/src/csharp/todoskill/todoskill/Resources/ShowToDoCardTexts.lg
  skills/src/csharp/todoskill/todoskill/Resources/ShowToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/ToDoMainResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/ToDoSharedResponses.lg
  skills/src/csharp/todoskill/todoskill/Services/BotServices.cs
  skills/src/csharp/todoskill/todoskill/Startup.cs
  skills/src/csharp/todoskill/todoskill/ToDoSkill.csproj
  skills/src/csharp/todoskill/todoskill/Utilities/ToDoCommonUtil.cs
Labels: PR: unreviewed

#1939 [TypeScript][BotBuilder Solutions] Use of pathToResource property in AuthenticationResponses
  lib/typescript/botbuilder-solutions/src/authentication/multiProviderAuthDialog.ts
Labels: PR: reviewed-approved

#1965 [Botskills] Handle the version of Azure CLI during the execution of the tool
  docs/howto/skills/botskills.md
  tools/botskills/src/utils/authenticationUtils.ts
  tools/botskills/src/utils/azUtils.ts
  tools/botskills/src/utils/childProcessUtils.ts
  tools/botskills/src/utils/index.ts
  tools/botskills/test/authentication.test.js
Labels: PR: reviewed-approved

#1945 [Botskills] Fix line endings for test temporal files
  tools/botskills/test/authentication.test.js
  tools/botskills/test/connect.test.js
  tools/botskills/test/disconnect.test.js
  tools/botskills/test/helpers/normalizeUtils.js
  tools/botskills/test/list.test.js
  tools/botskills/test/mocks/success/dispatch/filledDispatch.dispatch
  tools/botskills/test/update.test.js
Labels: PR: reviewed-approved

#1933 [TypeScript][BotBuilder Libs] Update functionality of BotBuilder-Skills and BotBuilder-Solutions
  lib/typescript/botbuilder-skills/package.json
  lib/typescript/botbuilder-skills/src/auth/microsoftAppCredentialsEx.ts
  lib/typescript/botbuilder-skills/src/auth/serviceClientCredentials.ts
  lib/typescript/botbuilder-skills/src/http/skillHttpTransport.ts
  lib/typescript/botbuilder-skills/src/skillDialog.ts
  lib/typescript/botbuilder-solutions/src/botSettings.ts
  lib/typescript/botbuilder-solutions/src/extensions/activityExtensions.ts
Labels: PR: unreviewed

#1975 Update readme.md
  docs/readme.md
Labels: PR: unreviewed

#1979 Shzhen/todo lg
  skills/src/csharp/todoskill/todoskill/Dialogs/AddToDoItemDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/DeleteToDoItemDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/MainDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/MarkToDoItemDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/ShowToDoItemDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/ToDoSkillDialogBase.cs
  skills/src/csharp/todoskill/todoskill/Resources/AddToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/DeleteToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/MarkToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/ShowToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/ToDoMainResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/ToDoSharedResponses.lg
  skills/src/csharp/todoskill/todoskill/Utilities/ToDoCommonUtil.cs
Labels: PR: unreviewed

#1981 Yuesu/va lg preview
  skills/src/csharp/calendarskill/calendarskill/Adapters/AdapterWithErrorHandler.cs
  skills/src/csharp/calendarskill/calendarskill/Bots/DialogBot.cs
  skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
  skills/src/csharp/calendarskill/calendarskill/Dialogs/CalendarSkillDialogBase.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/ChangeEventStatusDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/ConnectToMeetingDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/CreateEventDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/FindContactDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/MainDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/SummaryDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/UpcomingEventDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/UpdateEventDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Models/CalendarDateCardData.cs
  skills/src/csharp/calendarskill/calendarskill/Models/CalendarItemCardData.cs
  skills/src/csharp/calendarskill/calendarskill/Models/EventModel.cs
  skills/src/csharp/calendarskill/calendarskill/Responses/ChangeEventStatus/ChangeEventStatus.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/CreateEvent/CreateEventDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/FindContact/FindContactDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/JoinEvent/JoinEventDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/Main/MainDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/Main/MainDialog.zh-cn.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/Shared.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/Summary/SummaryDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/UpcomingEvent/UpcomingEventDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/UpdateEvent/UpdateEventDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Startup.cs
Labels: PR: unreviewed

#1992 [LG] Fix issues and enable test
  skills/src/csharp/emailskill/emailskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/emailskill/emailskill/Adapters/EmailSkillWebSocketBotAdapter.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/DeleteEmailDialog.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/EmailSkillDialogBase.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/FindContactDialog.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/ForwardEmailDialog.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/MainDialog.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/ReplyEmailDialog.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/SendEmailDialog.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/ShowEmailDialog.cs
  skills/src/csharp/emailskill/emailskill/Responses/Main/MainDialog.lg
  skills/src/csharp/emailskill/emailskill/Responses/Shared/Shared.lg
Labels: PR: unreviewed

#1998 Shzhen/todo lg
  skills/src/csharp/todoskill/todoskill/Dialogs/ToDoSkillDialogBase.cs
  skills/src/csharp/todoskill/todoskill/Resources/AddToDoCardTexts.lg
  skills/src/csharp/todoskill/todoskill/Resources/AddToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/CardSummaryTexts.lg
  skills/src/csharp/todoskill/todoskill/Resources/DeleteToDoCardTexts.lg
  skills/src/csharp/todoskill/todoskill/Resources/DeleteToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/MarkToDoCardTexts.lg
  skills/src/csharp/todoskill/todoskill/Resources/MarkToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/ShowToDoCardTexts.lg
  skills/src/csharp/todoskill/todoskill/Resources/ShowToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/ToDoMainResponses.lg
  skills/src/csharp/todoskill/todoskill/Resources/ToDoSharedResponses.lg
  skills/src/csharp/todoskill/todoskill/Utilities/ToDoCommonUtil.cs
  skills/src/csharp/todoskill/todoskilltest/Flow/ToDoBotTestBase.cs
Labels: PR: unreviewed

#1997 Updated knownissues.md
  docs/reference/knownissues.md
Labels: Changelog: Skip, PR: reviewed-approved

#1984 [Lib]Support Action specific skill call
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/Mocks/MockSkillTransport.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/SkillDialogInvocationTests.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/ISkillTransport.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillConstants.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialog.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialogOption.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketTransport.cs
Labels: PR: reviewed-approved
