Repository microsoft/botframework-solutions, pull requests merged in 2019-09, with the labels that each got.

#2203 [TypeScript][Samples/Templates] Update the SDK dependencies
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/_package.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/_package.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/package-lock.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/package.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/package-lock.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/package.json
Labels: PR: reviewed-approved

#2231 [TypeScript][Samples] Generate samples with the latest version of the generator
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/test/helpers/botTestBase.js
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/resources/template.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/dialogs/_mainDialog.ts
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/services/botServices.ts
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/template.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/resources/template.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/dialogs/mainDialog.ts
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/services/botServices.ts
Labels: PR: reviewed-approved

#2275 [TypeScript][Skill Sample/Template] Update casing for name property
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/responses/sample/resources/SampleResponses.de.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/responses/sample/resources/SampleResponses.es.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/responses/sample/resources/SampleResponses.fr.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/responses/sample/resources/SampleResponses.it.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/responses/sample/resources/SampleResponses.zh.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/responses/sample/resources/SampleResponses.de.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/responses/sample/resources/SampleResponses.es.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/responses/sample/resources/SampleResponses.fr.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/responses/sample/resources/SampleResponses.it.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/responses/sample/resources/SampleResponses.zh.json
Labels: PR: reviewed-approved

#2287 Shzhen/context awareness
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Actions/SavePreviousQuestion.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Actions/SkillContextualActionsBase.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Models/IUserContext.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Models/Person.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Models/PreviousQuestion.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Models/Strategy/FIFOStrategy.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Models/Strategy/IReplacementStrategy.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Models/Strategy/LRUStrategy.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Models/Strategy/RandomStrategy.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Models/Strategy/StrategyType.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/SkillContextualMiddleware.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/UserContextResolver.cs
  skills/src/csharp/todoskill/todoskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/todoskill/todoskill/Controllers/BotController.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/MainDialog.cs
  skills/src/csharp/todoskill/todoskill/Startup.cs
  skills/src/csharp/todoskill/todoskill/ToDoSkill.csproj
Labels: PR: unreviewed

#2256 [Docs] Update hospitality related docs
  docs/_docs/reference/samples/hospitalitysample.md
  docs/_docs/reference/skills/experimental.md
  docs/_docs/reference/skills/transcripts.md
  docs/assets/images/hospitalitysample-diagram.png
  docs/assets/images/skills-event-transcript.png
  docs/assets/images/skills-hospitality-transcript.png
  docs/assets/transcripts/hospitalitysample-faqs.transcript
  docs/assets/transcripts/hospitalitysample-localinfo.transcript
  docs/assets/transcripts/hospitalitysample-reservationchanges.transcript
  docs/assets/transcripts/hospitalitysample-roomservices.transcript
  docs/assets/transcripts/skills-hospitality.transcript
  solutions/HospitalitySample/readme.md
Labels: PR: reviewed-approved

#2283 Need to update VA sample lib referance to support handoff
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
Labels: PR: reviewed-approved

#2299 Shzhen/context awareness
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Actions/SavePreviousQuestion.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Dialogs/ResolveContextualInfoDialog.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Models/IUserContext.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Models/Person.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Models/UserHistoryInfo.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/UserContextManager.cs
  skills/src/csharp/todoskill/todoskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/MainDialog.cs
  skills/src/csharp/todoskill/todoskill/Startup.cs
Labels: PR: unreviewed

#2291 Remove callerId in Auth flow as callerId shouldn't be transferred over the wire
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketBotAdapter.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketRequestHandler.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketTransport.cs
Labels: PR: reviewed-approved

#2286 fix find contact issue
  skills/src/csharp/calendarskill/calendarskill/Dialogs/CalendarSkillDialogBase.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/FindContactDialog.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/CreateCalendarFlowTests.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/Fakes/MockServiceManager.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/Prompt/GetEventPromptTests.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/FindContactDialog.cs
  skills/src/csharp/emailskill/emailskilltest/Flow/SendEmailFlowTests.cs
Labels: PR: reviewed-approved

#2252 [Skill Sample/Template] Update useDispatch parameter
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
Labels: PR: reviewed-approved

#2277 Fix ContentModerator Middleware
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Middleware/ContentModeratorMiddleware.cs
  samples/EnterpriseNotification/VirtualAssistant/Adapters/DefaultAdapter.cs
  samples/EnterpriseNotification/VirtualAssistant/Adapters/DefaultWebSocketAdapter.cs
  samples/EnterpriseNotification/VirtualAssistant/VirtualAssistant.csproj
  templates/Virtual-Assistant-Template/csharp/Template/VA/Adapters/DefaultAdapter.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Adapters/DefaultWebSocketAdapter.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/VA.csproj
Labels: PR: reviewed-approved

#2319 add whitelist to template
  templates/Skill-Template/csharp/Sample/SkillSample.Tests/SkillSample.Tests.csproj
  templates/Skill-Template/csharp/Sample/SkillSample/Controllers/BotController.cs
  templates/Skill-Template/csharp/Sample/SkillSample/SkillSample.csproj
  templates/Skill-Template/csharp/Sample/SkillSample/Startup.cs
  templates/Skill-Template/csharp/Sample/SkillSample/WhiteListAuthProvider.cs
  templates/Skill-Template/csharp/Sample/SkillSample/appsettings.json
Labels: PR: unreviewed

#2328 revert change
  lib/csharp/Directory.Build.props
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Dialogs/ResolveContextualInfoDialog.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Dialogs/ResolveContextualInfoResponses.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Dialogs/ResolveContextualInfoResponses.de.json
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Dialogs/ResolveContextualInfoResponses.es.json
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Dialogs/ResolveContextualInfoResponses.fr.json
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Dialogs/ResolveContextualInfoResponses.it.json
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Dialogs/ResolveContextualInfoResponses.json
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Dialogs/ResolveContextualInfoResponses.tt
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Dialogs/ResolveContextualInfoResponses.zh.json
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Dialogs/ResponseIdCollection.t4
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Dialogs/UserInfoOptions.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/IContextResolver.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Models/PossessivePronoun.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Models/RelatedEntityInfo.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Models/UserHistoryInfo.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Models/UserInfoState.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Models/UserRelationshipType.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Resources/RelationshipStrings.Designer.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Resources/RelationshipStrings.de.resx
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Resources/RelationshipStrings.es.resx
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Resources/RelationshipStrings.fr.resx
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Resources/RelationshipStrings.it.resx
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Resources/RelationshipStrings.resx
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/Resources/RelationshipStrings.zh.resx
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/UserContextResolver.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Contextual/UserStateContextResolver.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Microsoft.Bot.Builder.Skills.csproj
  skills/src/csharp/Skills.sln
  skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
  skills/src/csharp/calendarskill/calendarskill/Controllers/BotController.cs
  skills/src/csharp/calendarskill/calendarskill/Startup.cs
  skills/src/csharp/emailskill/emailskill/Contextual/EmailContextResolver.cs
  skills/src/csharp/emailskill/emailskill/Controllers/BotController.cs
  skills/src/csharp/emailskill/emailskill/Deployment/Resources/LU/en/Email.lu
  skills/src/csharp/emailskill/emailskill/Dialogs/EmailSkillDialogBase.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/FindContactDialog.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/ForwardEmailDialog.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/MainDialog.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/SendEmailDialog.cs
  skills/src/csharp/emailskill/emailskill/EmailSkill.csproj
  skills/src/csharp/emailskill/emailskill/Models/EmailSkillState.cs
  skills/src/csharp/emailskill/emailskill/Services/EmailLuis.cs
  skills/src/csharp/emailskill/emailskill/Services/GoogleAPI/GooglePeopleService.cs
  skills/src/csharp/emailskill/emailskill/Services/IUserService.cs
  skills/src/csharp/emailskill/emailskill/Services/MSGraphAPI/MSGraphUserService.cs
  skills/src/csharp/emailskill/emailskill/Startup.cs
  skills/src/csharp/emailskill/emailskill/Utilities/FindContactAction.cs
Labels: PR: unreviewed

#2329 Revert
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.Designer.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.de.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.es.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.fr.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.it.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.zh.resx
  skills/src/csharp/Skills.sln
Labels: PR: unreviewed

#2330 Merge
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.Designer.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.resx
Labels: PR: unreviewed

#2245 [TypeScript][Samples/Templates] Execute the installation and compilation during the publish
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/publish.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/publish.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/publish.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/scripts/publish.ps1
Labels: PR: reviewed-approved

#2289 [C#][Samples/Templates] Add UTF8 default encoding for deployment scripts
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/deploy.ps1
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/update_cognitive_models.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/deploy.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/update_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/update_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/deploy.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/update_cognitive_models.ps1
Labels: PR: reviewed-approved

#2278 [TypeScript][Skill Sample/Template] Add missing properties for the manifestTemplate
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/_manifestTemplate.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/manifestTemplate.json
Labels: PR: reviewed-approved

#2326 [Hospitality] typo fix
  samples/assistants/HospitalitySample/Deployment/Resources/QnA/en/hotel_FAQ.lu
  skills/src/csharp/experimental/hospitalityskill/Dialogs/CheckOutDialog.cs
  skills/src/csharp/experimental/hospitalityskill/Dialogs/ExtendStayDialog.cs
  skills/src/csharp/experimental/hospitalityskill/Dialogs/RoomServiceDialog.cs
Labels: PR: reviewed-approved

#2334 Shzhen/context awareness
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Actions/SavePreviousInputAction.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Dialogs/ResolveContextualInfoDialog.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Resolvers/UserStateContextResolver.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/UserContextManager.cs
  skills/src/csharp/calendarskill/calendarskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/calendarskill/calendarskill/Startup.cs
  skills/src/csharp/emailskill/emailskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/FindContactDialog.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/ForwardEmailDialog.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/SendEmailDialog.cs
  skills/src/csharp/emailskill/emailskill/Startup.cs
  skills/src/csharp/todoskill/todoskill/Adapters/DefaultAdapter.cs
Labels: PR: unreviewed

#2323 Improve German wording for skills for new user greeting
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Content/NewUserGreeting.de.json
  templates/Virtual-Assistant-Template/csharp/Template/VA/Content/NewUserGreeting.de.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/content/NewUserGreeting.de.json
Labels: PR: reviewed-approved

#2337 Shzhen/context awareness
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Actions/CacheCoreferenceResolutionInformationAction.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Actions/CachePreviousTriggerIntentAction.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Actions/GetSentimentAction.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Actions/SavePreviousInputAction.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Actions/SkillContextualActionBase.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Models/PreviousTriggerIntent.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Models/Strategy/LRUStrategy.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/SkillContextualMiddleware.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/UserContextManager.cs
  skills/src/csharp/calendarskill/calendarskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/emailskill/emailskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/todoskill/todoskill/Adapters/DefaultAdapter.cs
Labels: PR: unreviewed

#2343 Shzhen/context awareness
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Contextual/Actions/CacheCoreferenceResolutionInformationAction.cs
Labels: PR: unreviewed

#2310 Various docs issues
  docs/_docs/reference/skills/experimental.md
  docs/_docs/reference/skills/productivity-todo.md
  docs/_docs/tutorials/csharp/create-assistant/1_intro.md
  docs/_docs/tutorials/csharp/create-assistant/5_run_your_assistant.md
  docs/_docs/tutorials/typescript/create-assistant/1_intro.md
  docs/_docs/tutorials/typescript/create-assistant/5_run_your_assistant.md
  skills/src/csharp/automotiveskill/automotiveskill/readme.md
  skills/src/csharp/calendarskill/calendarskill/readme.md
  skills/src/csharp/emailskill/emailskill/readme.md
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/readme.md
  skills/src/csharp/experimental/eventskill/readme.md
  skills/src/csharp/experimental/hospitalityskill/readme.md
  skills/src/csharp/experimental/itsmskill/readme.md
  skills/src/csharp/experimental/musicskill/readme.md
  skills/src/csharp/experimental/newsskill/readme.md
  skills/src/csharp/experimental/restaurantbooking/readme.md
  skills/src/csharp/experimental/weatherskill/readme.md
  skills/src/csharp/pointofinterestskill/pointofinterestskill/readme.md
  skills/src/csharp/todoskill/todoskill/manifestTemplate.json
  skills/src/csharp/todoskill/todoskill/readme.md
Labels: PR: reviewed-approved

#2344 [Lib] Bug fix for single-turn dialogs not triggering CompleteAsync
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Dialogs/RouterDialog.cs
Labels: PR: reviewed-approved

#2307 [Samples/Templates] Add resourceGroupName attribute in the appsettings after deployment
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Resources/template.json
  templates/Skill-Template/csharp/Template/Skill/Deployment/Resources/template.json
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/template.json
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/template.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/template.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/deploy.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/resources/template.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/deploy.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/template.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/deploy.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/resources/template.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/scripts/deploy.ps1
Labels: PR: reviewed-approved

#2335 [TypeScript][Generator] Fix vulnerabilities in dependencies
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/package-lock.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/package.json
Labels: PR: reviewed-approved

#2327 [Calendar] Fix digest time entity logic
  skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
  skills/src/csharp/calendarskill/calendarskill/Dialogs/CalendarSkillDialogBase.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/Fakes/MockServiceManager.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/SummaryCalendarFlowTests.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/Utterances/FindMeetingTestUtterances.cs
Labels: PR: reviewed-approved

#2354 Updated error handling in publish.ps1
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/calendarskill/calendarskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/experimental/eventskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/experimental/hospitalityskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/experimental/itsmskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/experimental/musicskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/publish.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/publish.ps1
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/publish.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/publish.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/publish.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/publish.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/publish.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/publish.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/publish.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/scripts/publish.ps1
Labels: PR: unreviewed

#2304 [POI] Rename TelUri to TelephoneUri
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Models/OpenDefaultApp.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/PointOfInterestDialogTests.cs
Labels: PR: reviewed-approved

#2313 Latest Android Updates
  samples/clients/android/EventCompanion/app/src/main/res/mipmap-hdpi/ic_launcher.png
  samples/clients/android/VirtualAssistantClient/app/build.gradle
  samples/clients/android/VirtualAssistantClient/app/src/main/AndroidManifest.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/MainActivity.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/chatlist/Action.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/chatlist/ActionHandler.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/chatlist/ChatAdapter.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/chatlist/ChatModel.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/chatlist/ChatViewModel.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/chatlist/SvgImageLoader.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/chatlist/ViewHolderBot.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/chatlist/ViewHolderUser.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/chatlist/ViewholderBot.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/chatlist/ViewholderUser.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/service/SpeechService.java
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-anydpi/ic_welcome.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-hdpi/ic_gps.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-hdpi/ic_welcome.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-mdpi/ic_gps.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-mdpi/ic_welcome.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-xhdpi/ic_gps.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-xhdpi/ic_welcome.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-xxhdpi/ic_gps.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-xxhdpi/ic_welcome.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable/ic_gps.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable/ic_launcher_background.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable/ic_va.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/layout/item_adaptive_card.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/layout/item_chat_bot.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/mipmap-hdpi/ic_launcher.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/mipmap-mdpi/ic_launcher.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/raw/hostconfig.json
  samples/clients/android/VirtualAssistantClient/build.gradle
  samples/clients/android/VirtualAssistantClient/directlinespeech/build.gradle
  samples/clients/android/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/SpeechSdk.java
  samples/clients/android/VirtualAssistantClient/gradle/wrapper/gradle-wrapper.properties
Labels: PR: reviewed-approved

#2363 [Lib and Skill Template] Make white list optional
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Auth/Authenticator.cs
  templates/Skill-Template/csharp/Sample/SkillSample/WhiteListAuthProvider.cs
  templates/Skill-Template/csharp/Template/Skill/WhiteListAuthProvider.cs
Labels: PR: reviewed-approved

#2370 [Calendar] fix merge issue
  skills/src/csharp/calendarskill/calendarskill/Dialogs/CalendarSkillDialogBase.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/CreateEventDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/UpdateEventDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Prompts/DatePrompt.cs
  skills/src/csharp/calendarskill/calendarskill/Prompts/GetEventPrompt.cs
  skills/src/csharp/calendarskill/calendarskill/Prompts/TimePrompt.cs
  skills/src/csharp/calendarskill/calendarskilltest/Prompt/DatePromptTests.cs
  skills/src/csharp/calendarskill/calendarskilltest/Prompt/GetEventPromptTests.cs
Labels: PR: reviewed-approved

#2360 Skill doc updates for 0.6
  docs/_docs/reference/skills/automotive.md
  docs/_docs/reference/skills/pointofinterest.md
  docs/_docs/reference/skills/productivity-calendar.md
  docs/_docs/reference/skills/productivity-email.md
  docs/_docs/reference/skills/productivity-todo.md
  docs/_docs/reference/virtual-assistant/events.md
  docs/_docs/tutorials/csharp/create-assistant/5_run_your_assistant.md
  docs/_docs/tutorials/typescript/create-assistant/5_run_your_assistant.md
Labels: PR: unreviewed

#2371 Skill project updates
  skills/src/csharp/Directory.Build.props
  skills/src/csharp/automotiveskill/automotiveskill/Dialogs/MainDialog.cs
  skills/src/csharp/automotiveskill/automotiveskilltest/Flow/GeneralSkillFlowTests.cs
  skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
  skills/src/csharp/calendarskill/calendarskill/Dialogs/MainDialog.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/GeneralSkillFlowTests.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/Utterances/GeneralTestUtterances.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/MainDialog.cs
  skills/src/csharp/emailskill/emailskill/EmailSkill.csproj
  skills/src/csharp/emailskill/emailskilltest/Flow/GeneralSkillFlowTests.cs
  skills/src/csharp/emailskill/emailskilltest/Flow/Utterances/GeneralTestUtterances.cs
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Dialogs/MainDialog.cs
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Dialogs/SearchDialog.cs
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Dialogs/SkillDialogBase.cs
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Services/BotServices.cs
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Startup.cs
  skills/src/csharp/experimental/eventskill/Dialogs/MainDialog.cs
  skills/src/csharp/experimental/hospitalityskill/Dialogs/MainDialog.cs
  skills/src/csharp/experimental/itsmskill/Dialogs/MainDialog.cs
  skills/src/csharp/experimental/itsmskill/ITSMSkill.csproj
  skills/src/csharp/experimental/musicskill/Dialogs/MainDialog.cs
  skills/src/csharp/experimental/newsskill/Dialogs/MainDialog.cs
  skills/src/csharp/experimental/restaurantbooking/Dialogs/MainDialog.cs
  skills/src/csharp/experimental/weatherskill/Dialogs/MainDialog.cs
  skills/src/csharp/phoneskill/phoneskill/Dialogs/MainDialog.cs
  skills/src/csharp/phoneskill/phoneskilltest/Flow/GeneralSkillFlowTests.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/MainDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/GeneralSkillFlowTests.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/Utterances/GeneralTestUtterances.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/MainDialog.cs
  skills/src/csharp/todoskill/todoskilltest/Flow/GeneralSkillFlowTests.cs
  skills/src/csharp/todoskill/todoskilltest/Flow/Utterances/GeneralTestUtterances.cs
  templates/Skill-Template/csharp/Directory.Build.props
  templates/Skill-Template/csharp/Sample/SkillSample.Tests/MainDialogTests.cs
  templates/Skill-Template/csharp/Sample/SkillSample.Tests/SkillSample.Tests.csproj
  templates/Skill-Template/csharp/Sample/SkillSample/Dialogs/MainDialog.cs
  templates/Skill-Template/csharp/Sample/SkillSample/SkillSample.csproj
  templates/Skill-Template/csharp/Template/Skill.Tests/MainDialogTests.cs
  templates/Skill-Template/csharp/Template/Skill/Dialogs/MainDialog.cs
  templates/Skill-Template/csharp/Template/Skill/Skill.csproj
  templates/Virtual-Assistant-Template/csharp/Directory.Build.props
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
  templates/Virtual-Assistant-Template/csharp/Template/VA/VA.csproj
Labels: PR: reviewed-approved

#2379 Updated package versions to 4.5.4
  skills/src/csharp/automotiveskill/automotiveskill/AutomotiveSkill.csproj
  skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
  skills/src/csharp/emailskill/emailskill/EmailSkill.csproj
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/BingSearchSkill.csproj
  skills/src/csharp/experimental/eventskill/EventSkill.csproj
  skills/src/csharp/experimental/hospitalityskill/HospitalitySkill.csproj
  skills/src/csharp/experimental/itsmskill/ITSMSkill.csproj
  skills/src/csharp/experimental/musicskill/MusicSkill.csproj
  skills/src/csharp/experimental/newsskill/NewsSkill.csproj
  skills/src/csharp/experimental/restaurantbooking/RestaurantBooking.csproj
  skills/src/csharp/experimental/weatherskill/WeatherSkill.csproj
  skills/src/csharp/phoneskill/phoneskill/PhoneSkill.csproj
  skills/src/csharp/pointofinterestskill/pointofinterestskill/PointOfInterestSkill.csproj
  skills/src/csharp/todoskill/todoskill/ToDoSkill.csproj
  templates/Skill-Template/csharp/Sample/SkillSample/SkillSample.csproj
  templates/Skill-Template/csharp/Template/Skill/Skill.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
  templates/Virtual-Assistant-Template/csharp/Template/VA/VA.csproj
Labels: PR: unreviewed

#2367 Fix Botskills CLI broken links
  docs/_docs/howto/skills/addingskills.md
Labels: PR: unreviewed, Type: Docs

#2386 [Docs] Document what can be excluded from source control
  docs/_docs/tutorials/csharp/create-assistant/3_create_project.md
Labels: PR: unreviewed

#2387 Update 2_edit_your_responses.md
  docs/_docs/tutorials/csharp/customize-skill/2_edit_your_responses.md
Labels: PR: unreviewed

#2389 Update 4_edit_your_cognitive_models.md
  docs/_docs/tutorials/csharp/customize-assistant/4_edit_your_cognitive_models.md
Labels: PR: unreviewed

#2390 Doc updates
  docs/_docs/howto/virtual-assistant/manualdeployment.md
  docs/_docs/reference/virtual-assistant/localization.md
  docs/assets/images/emulator_locale.jpg
  docs/assets/images/emulator_settings.png
Labels: PR: reviewed-approved

#2385 Using country and region in code and comment
  samples/clients/csharp/assistant-WebTest/Assistant-WebTest/wwwroot/lib/jquery-validation/dist/additional-methods.js
  samples/utilities/linkedaccounts/linkedaccounts.web/wwwroot/lib/jquery-validation/dist/additional-methods.js
  skills/src/csharp/experimental/newsskill/Dialogs/NewsDialogBase.cs
  skills/src/csharp/experimental/newsskill/Models/AzureMaps/SearchAddress.cs
  skills/src/csharp/experimental/newsskill/Responses/FindArticles/FindArticlesResponses.cs
  skills/src/csharp/experimental/newsskill/Responses/Main/MainResponses.cs
  skills/src/csharp/experimental/newsskill/Responses/TrendingArticles/TrendingArticlesResponses.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Models/AzureMaps/Address.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Models/AzureMaps/SearchAddress.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Models/Foursquare/Location.cs
Labels: PR: reviewed-approved

#2197 [calendar] Add support for utterance like "my manager" or "his boss"
  docs/_docs/reference/skills/productivity-calendar.md
  skills/src/csharp/Directory.Build.props
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/de/Calendar.lu
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/en/Calendar.lu
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/es/Calendar.lu
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/fr/Calendar.lu
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/it/Calendar.lu
  skills/src/csharp/calendarskill/calendarskill/Deployment/Resources/LU/zh/Calendar.lu
  skills/src/csharp/calendarskill/calendarskill/Dialogs/CalendarSkillDialogBase.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/FindContactDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Models/CalendarSkillState.cs
  skills/src/csharp/calendarskill/calendarskill/Models/EventModel.cs
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarCommonStrings.Designer.cs
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarCommonStrings.de.resx
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarCommonStrings.es.resx
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarCommonStrings.fr.resx
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarCommonStrings.it.resx
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarCommonStrings.resx
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarCommonStrings.zh.resx
  skills/src/csharp/calendarskill/calendarskill/Services/CalendarLuis.cs
  skills/src/csharp/calendarskill/calendarskill/Services/GoogleAPI/GooglePeopleService.cs
  skills/src/csharp/calendarskill/calendarskill/Services/IUserService.cs
  skills/src/csharp/calendarskill/calendarskill/Services/MSGraphAPI/MSGraphUserService.cs
  skills/src/csharp/calendarskill/calendarskill/Services/UserService.cs
  skills/src/csharp/calendarskill/calendarskill/manifestTemplate.json
Labels: PR: reviewed-approved

#2381 [Calendar] fix parse number exception
  skills/src/csharp/calendarskill/calendarskill/Dialogs/CalendarSkillDialogBase.cs
Labels: PR: reviewed-approved

#2404 [Calendar] Remove action end responses
  skills/src/csharp/calendarskill/calendarskill/Dialogs/ChangeEventStatusDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/CreateEventDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/UpdateEventDialog.cs
Labels: PR: reviewed-approved

#2338 [Calendar] return both tel number and meeting link when join meeting
  skills/src/csharp/calendarskill/calendarskill/Dialogs/JoinEventDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Models/OpenDefaultApp.cs
  skills/src/csharp/calendarskill/calendarskill/Responses/JoinEvent/JoinEventResponses.cs
  skills/src/csharp/calendarskill/calendarskill/Responses/JoinEvent/JoinEventResponses.de.json
  skills/src/csharp/calendarskill/calendarskill/Responses/JoinEvent/JoinEventResponses.es.json
  skills/src/csharp/calendarskill/calendarskill/Responses/JoinEvent/JoinEventResponses.fr.json
  skills/src/csharp/calendarskill/calendarskill/Responses/JoinEvent/JoinEventResponses.it.json
  skills/src/csharp/calendarskill/calendarskill/Responses/JoinEvent/JoinEventResponses.json
  skills/src/csharp/calendarskill/calendarskill/Responses/JoinEvent/JoinEventResponses.zh.json
  skills/src/csharp/calendarskill/calendarskilltest/Flow/ConnectToMeetingFlowTests.cs
Labels: PR: reviewed-approved

#2378 [Documentation] Fix Skill manifest parameter descriptions
  docs/_docs/reference/skills/skillmanifest.md
Labels: PR: reviewed-approved

#2410 [TypeScript][Templates] Fix '.web.config' in VA & Skill template
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/publish.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/publish.ps1
Labels: PR: reviewed-approved

#2414 [Documentation] Fix typos, broken links and stylings
  docs/_docs/reference/skills/architecture.md
  docs/_docs/reference/skills/automotive.md
  docs/_docs/reference/skills/bestpractices.md
  docs/_docs/reference/skills/experimental.md
  docs/_docs/reference/skills/phone.md
  docs/_docs/reference/skills/pointofinterest.md
  docs/_docs/reference/skills/productivity-calendar.md
  docs/_docs/reference/skills/productivity-email.md
  docs/_docs/reference/skills/productivity-todo.md
  docs/_docs/reference/skills/responses.md
  docs/_docs/reference/skills/skillmanifest.md
  docs/_docs/tutorials/typescript/create-skill/1_intro.md
  docs/_docs/tutorials/typescript/create-skill/6_add_your_skill.md
  tools/botskills/docs/connect.md
  tools/botskills/docs/disconnect.md
  tools/botskills/docs/refresh.md
  tools/botskills/docs/update.md
Labels: PR: reviewed-approved

#2301 [Skills] convert location to timezone
  skills/src/csharp/calendarskill/calendarskill/Dialogs/MainDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Models/TimeZoneResponse.cs
  skills/src/csharp/calendarskill/calendarskill/Services/AzureMapsAPI/AzureMapsClient.cs
  skills/src/csharp/calendarskill/calendarskill/Services/BotSettings.cs
  skills/src/csharp/calendarskill/calendarskill/appsettings.json
  skills/src/csharp/emailskill/emailskill/Dialogs/MainDialog.cs
  skills/src/csharp/emailskill/emailskill/Models/TimeZoneResponse.cs
  skills/src/csharp/emailskill/emailskill/Services/AzureMapsAPI/AzureMapsClient.cs
  skills/src/csharp/emailskill/emailskill/Services/BotSettings.cs
  skills/src/csharp/emailskill/emailskill/appsettings.json
Labels: PR: reviewed-approved

#2383 [Android] UI refactoring and bug fix
  samples/clients/android/VirtualAssistantClient/app/src/debug/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/configuration/DefaultConfiguration.java
  samples/clients/android/VirtualAssistantClient/app/src/main/AndroidManifest.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/assets/default_app_configuration.json
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/MainApplication.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/BaseActivity.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/MainActivity.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/settings/SettingsActivity.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/assistant/VoiceInteractionActivity.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/service/SpeechService.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/utils/AppConfiguration.java
  samples/clients/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/utils/AppConfigurationManager.java
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-anydpi/ic_debug.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-anydpi/ic_keyboard.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-hdpi/ic_debug.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-hdpi/ic_keyboard.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-mdpi/ic_debug.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-mdpi/ic_keyboard.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-xhdpi/ic_debug.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-xhdpi/ic_keyboard.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-xxhdpi/ic_debug.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable-xxhdpi/ic_keyboard.png
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable/ic_keyboard.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable/ic_mic.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable/ic_refresh.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/drawable/ic_settings.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/layout-land/activity_main.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/layout-port/activity_settings.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/layout/activity_main.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/layout/activity_settings.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/layout/assistant_overlay.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/layout/widget_talk_button.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/menu/nav_drawer_menu.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/values/colors.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/values/strings.xml
  samples/clients/android/VirtualAssistantClient/app/src/main/res/values/styles.xml
  samples/clients/android/VirtualAssistantClient/directlinespeech/src/main/assets/default_configuration.json
  samples/clients/android/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/ConfigurationManager.java
  samples/clients/android/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/model/Configuration.java
Labels: PR: reviewed-approved

#2417 [TypeScript][Botskills] Fix vulnerabilities in dependencies
  tools/botskills/package-lock.json
Labels: PR: reviewed-approved

#2443 [TypeScript][Virtual Assistant Template] Fix inconsistency Sample/Template
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/content/NewUserGreeting.de.json
Labels: PR: reviewed-approved

#2449 skill fixes
  skills/csharp/experimental/bingsearchskill/Deployment/Resources/LU/en/BingSearchSkill.lu
  skills/csharp/experimental/bingsearchskill/Dialogs/SearchDialog.cs
  skills/csharp/experimental/bingsearchskill/Services/BingSearchClient.cs
  skills/csharp/pointofinterestskill/Deployment/Resources/LU/zh/PointOfInterest.lu
  skills/csharp/pointofinterestskill/Deployment/Resources/LU/zh/secondary/poi_navigation_get_directions.lu
  skills/csharp/tests/pointofinterestskill.tests/Flow/Fakes/MockServiceManager.cs
  skills/csharp/tests/pointofinterestskill.tests/Flow/PointOfInterestSkillTestBase.cs
Labels: PR: reviewed-approved

#2361 [TypeScript][Samples/Templates] Update TypeScript ESLint version
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/_package.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/dialogs/cancelDialog.ts
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/dialogs/mainDialog.ts
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/dialogs/onboardingDialog.ts
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/index.ts
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/responses/escalateResponses.ts
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/templateManager/templateManager.ts
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/tslint.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/_package.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/dialogs/_mainDialog.ts
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/dialogs/_skillDialogBase.ts
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/dialogs/sampleDialog.ts
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/index.ts
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/models/skillState.ts
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/tslint.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/package-lock.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/package.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/dialogs/cancelDialog.ts
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/dialogs/onboardingDialog.ts
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/index.ts
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/responses/escalateResponses.ts
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/templateManager/templateManager.ts
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/tslint.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/package-lock.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/package.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/dialogs/mainDialog.ts
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/dialogs/sampleDialog.ts
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/dialogs/skillDialogBase.ts
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/index.ts
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/models/skillState.ts
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/tslint.json
Labels: PR: reviewed-approved

#2411 [TypeScript][Samples/Templates] Fix publish instructions after deployment
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/deploy.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/deploy.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/deploy.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/scripts/deploy.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
Labels: PR: reviewed-approved

#2418 [TypeScript][Generator] Fix ESLint issues
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/index.js
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/index.js
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/services/botServices.ts
Labels: PR: reviewed-approved

#2430 [Botskills] Print informative instead of warning message for no auth settings
  tools/botskills/src/utils/authenticationUtils.ts
  tools/botskills/test/authentication.test.js
Labels: Language: Typescript, PR: reviewed-approved, PR: unreviewed

#2452 Removed duplicated MainResponse
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Dialogs/MainDialog.cs
Labels: PR: reviewed-approved
