Repository microsoft/botframework-solutions, pull requests merged in 2019-10, with the labels that each got.

#2451 [Weather] update lu
  skills/csharp/experimental/weatherskill/Deployment/Resources/LU/de/WeatherSkill.lu
  skills/csharp/experimental/weatherskill/Deployment/Resources/LU/en/WeatherSkill.lu
  skills/csharp/experimental/weatherskill/Deployment/Resources/LU/es/WeatherSkill.lu
  skills/csharp/experimental/weatherskill/Deployment/Resources/LU/fr/WeatherSkill.lu
  skills/csharp/experimental/weatherskill/Deployment/Resources/LU/it/WeatherSkill.lu
  skills/csharp/experimental/weatherskill/Deployment/Resources/LU/zh/General.lu
  skills/csharp/experimental/weatherskill/Deployment/Resources/LU/zh/WeatherSkill.lu
  skills/csharp/experimental/weatherskill/Dialogs/MainDialog.cs
  skills/csharp/experimental/weatherskill/Services/WeatherSkillLuis.cs
Labels: PR: reviewed-approved

#2268 [POI] add ShouldInterrupt for SelectPointOfInterestPrompt, SelectActionPrompt
  skills/csharp/pointofinterestskill/Content/PointOfInterestOverview.1.0.json
  skills/csharp/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
  skills/csharp/pointofinterestskill/Models/PointOfInterestSkillState.cs
  skills/csharp/tests/pointofinterestskill.tests/Flow/PointOfInterestDialogTests.cs
Labels: PR: reviewed-approved

#2458 [Lib] Refactored routerDialog
  sdk/csharp/libraries/microsoft.bot.builder.solutions/CognitiveModelSet.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Dialogs/InterruptableDialog.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Dialogs/InterruptionAction.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Dialogs/RouterDialog.cs
Labels: PR: reviewed-approved

#2476 [Documentation][Botskills] Fix botName parameter
  docs/_docs/howto/skills/addingskills.md
  docs/_docs/reference/knownissues.md
  docs/_docs/reference/skills/botskills.md
  docs/_docs/tutorials/add-prebuilt-skill/4_connect_skill.md
  docs/_docs/tutorials/csharp/create-skill/6_add_your_skill.md
  docs/_docs/tutorials/typescript/create-skill/6_add_your_skill.md
Labels: PR: reviewed-approved

#2464 [VA] ActivityHandler implementation with RouterDialog changes
  templates/Virtual-Assistant-Template/csharp/Directory.Build.props
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/BotTestBase.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/InterruptionTests.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/LocalizationTests.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/MainDialogTests.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/Mocks/MockLuisRecognizer.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/Mocks/MockQnAMaker.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/OnboardingDialogTests.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/Utilities/ChitchatTestUtil.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/Utilities/DispatchTestUtil.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/Utilities/FaqTestUtil.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/Utterances/ChitchatUtterances.Designer.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/Utterances/ChitchatUtterances.resx
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/Utterances/FaqUtterances.Designer.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/Utterances/FaqUtterances.resx
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Bots/DefaultActivityHandler.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Bots/DialogBot.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/CancelDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/EscalateDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/OnboardingDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/CancelResponses.de.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/CancelResponses.es.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/CancelResponses.fr.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/CancelResponses.it.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/CancelResponses.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/CancelResponses.zh.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/EscalateResponses.de.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/EscalateResponses.es.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/EscalateResponses.fr.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/EscalateResponses.it.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/EscalateResponses.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/EscalateResponses.zh.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.de.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.es.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.fr.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.it.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.zh.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/readme.md
  templates/Virtual-Assistant-Template/csharp/VirtualAssistant.ruleset
Labels: PR: reviewed-approved

#2375 [ITSM] make use of number
  skills/csharp/experimental/itsmskill/Dialogs/CreateTicketDialog.cs
  skills/csharp/experimental/itsmskill/Dialogs/ShowTicketDialog.cs
  skills/csharp/experimental/itsmskill/Dialogs/SkillDialogBase.cs
  skills/csharp/experimental/itsmskill/Models/ServiceNow/AggregateResponse.cs
  skills/csharp/experimental/itsmskill/Models/ServiceNow/SingleAggregateResponse.cs
  skills/csharp/experimental/itsmskill/Models/ServiceNow/StatsResponse.cs
  skills/csharp/experimental/itsmskill/Responses/Knowledge/KnowledgeResponses.cs
  skills/csharp/experimental/itsmskill/Responses/Knowledge/KnowledgeResponses.json
  skills/csharp/experimental/itsmskill/Responses/Shared/SharedStrings.Designer.cs
  skills/csharp/experimental/itsmskill/Responses/Shared/SharedStrings.resx
  skills/csharp/experimental/itsmskill/Responses/Ticket/TicketResponses.cs
  skills/csharp/experimental/itsmskill/Responses/Ticket/TicketResponses.json
  skills/csharp/experimental/itsmskill/Services/IITServiceManagement.cs
  skills/csharp/experimental/itsmskill/Services/ServiceNow/Management.cs
  skills/csharp/experimental/itsmskill/Startup.cs
  skills/csharp/experimental/itsmskill/Utilities/SimpleWhitelistAuthenticationProvider.cs
  skills/csharp/experimental/itsmskill/appsettings.json
Labels: PR: reviewed-approved

#2484 [VA] Added "repeat last message" logic
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/InterruptionTests.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs
Labels: PR: reviewed-approved

#2447 [Weather] use Latitude & Longitude if possible
  skills/csharp/experimental/weatherskill/Dialogs/ForecastDialog.cs
  skills/csharp/experimental/weatherskill/Dialogs/MainDialog.cs
  skills/csharp/experimental/weatherskill/Dialogs/SampleDialog.cs
  skills/csharp/experimental/weatherskill/Dialogs/SkillDialogBase.cs
  skills/csharp/experimental/weatherskill/Models/SkillState.cs
  skills/csharp/experimental/weatherskill/Responses/Sample/SampleResponses.cs
  skills/csharp/experimental/weatherskill/Responses/Sample/SampleResponses.de.json
  skills/csharp/experimental/weatherskill/Responses/Sample/SampleResponses.es.json
  skills/csharp/experimental/weatherskill/Responses/Sample/SampleResponses.fr.json
  skills/csharp/experimental/weatherskill/Responses/Sample/SampleResponses.it.json
  skills/csharp/experimental/weatherskill/Responses/Sample/SampleResponses.json
  skills/csharp/experimental/weatherskill/Responses/Sample/SampleResponses.tt
  skills/csharp/experimental/weatherskill/Responses/Sample/SampleResponses.zh.json
  skills/csharp/experimental/weatherskill/Services/AccuweatherService.cs
  skills/csharp/experimental/weatherskill/Startup.cs
  skills/csharp/experimental/weatherskill/WeatherSkill.csproj
  skills/csharp/experimental/weatherskill/manifestTemplate.json
  skills/csharp/pointofinterestskill/manifestTemplate.json
Labels: PR: reviewed-approved

#2490 [VA] Implemented SDK telemetry fix for websocket connection
  templates/Virtual-Assistant-Template/csharp/Directory.Build.props
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/BotTestBase.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Adapters/DefaultWebSocketAdapter.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Bots/DefaultActivityHandler.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Extensions/DialogExtensions.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
Labels: PR: reviewed-approved

#2349 [Lib] add OpenDefaultApp event model in Solutions
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Models/OpenDefaultApp.cs
Labels: PR: reviewed-approved

#2357 [Lib] add more exception type
  sdk/csharp/libraries/microsoft.bot.builder.solutions.skills/SkillException.cs
Labels: PR: reviewed-approved, Status: Blocked

#2508 Delete HospitalityAssistant.sln
  samples/csharp/assistants/hospitalityassistant/HospitalityAssistant.sln
Labels: PR: reviewed-approved

#2514 Add missing headers, defensive checks
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Authentication/MultiProviderAuthDialog.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Authentication/OAuthConnection.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Authentication/OAuthProvider.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Authentication/OAuthProviderExtensions.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Authentication/ProviderTokenResponse.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/BotSettingsBase.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/CognitiveModelSet.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Dialogs/EventPrompt.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Dialogs/InterruptableDialog.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Dialogs/RouterDialog.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Dialogs/RouterDialogTurnResult.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Dialogs/RouterDialogTurnStatus.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Extensions/DateTimeEx.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Extensions/ListEx.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Feedback/FeedbackMiddleware.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Feedback/FeedbackOptions.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Feedback/FeedbackRecord.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/IFallbackRequestProvider.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/IRemoteUserTokenProvider.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Middleware/EventDebuggerMiddleware.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Middleware/SetLocaleMiddleware.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Responses/Card.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Responses/ICardData.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Responses/ResponseManager.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Serialization.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/TaskExtensions/BackgroundService.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/TaskExtensions/BackgroundTaskQueue.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/TaskExtensions/IBackgroundTaskQueue.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/TaskExtensions/QueuedHostedService.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/TaskExtensions/ScheduledProcessor.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/TaskExtensions/ScheduledTask.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/TaskExtensions/ScheduledTaskModel.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Testing/DefaultTestAdapter.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/TokenEvents.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Util/CommonUtil.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Util/ConfigData.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Util/ConfirmRecognizerHelper.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Util/MD5Util.cs
Labels: PR: reviewed-approved

#2505 [Solutions] Defensive checks for ContentModerator Middleware
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Middleware/ContentModeratorMiddleware.cs
Labels: PR: reviewed-approved

#2486 [Skills] synchronize deploy scripts by templates
  skills/csharp/calendarskill/Deployment/Scripts/deploy.ps1
  skills/csharp/calendarskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/csharp/calendarskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/emailskill/Deployment/Scripts/deploy.ps1
  skills/csharp/emailskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/csharp/emailskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/automotiveskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/automotiveskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/csharp/experimental/automotiveskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/bingsearchskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/bingsearchskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/csharp/experimental/bingsearchskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/eventskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/eventskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/csharp/experimental/eventskill/Deployment/Scripts/qna_functions.ps1
  skills/csharp/experimental/eventskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/hospitalityskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/hospitalityskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/csharp/experimental/hospitalityskill/Deployment/Scripts/qna_functions.ps1
  skills/csharp/experimental/hospitalityskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/itsmskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/itsmskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/csharp/experimental/itsmskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/musicskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/musicskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/csharp/experimental/musicskill/Deployment/Scripts/qna_functions.ps1
  skills/csharp/experimental/musicskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/newsskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/newsskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/csharp/experimental/newsskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/phoneskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/phoneskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/csharp/experimental/phoneskill/Deployment/Scripts/luis_functions.ps1
  skills/csharp/experimental/phoneskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/restaurantbookingskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/restaurantbookingskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/csharp/experimental/restaurantbookingskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/weatherskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/weatherskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/csharp/experimental/weatherskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/pointofinterestskill/Deployment/Scripts/deploy.ps1
  skills/csharp/pointofinterestskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/csharp/pointofinterestskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/todoskill/Deployment/Scripts/deploy.ps1
  skills/csharp/todoskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/csharp/todoskill/Deployment/Scripts/update_cognitive_models.ps1
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/deploy_cognitive_models.ps1
Labels: PR: reviewed-approved

#2487 [ITSM] remove Token from state
  skills/csharp/experimental/itsmskill/Dialogs/CloseTicketDialog.cs
  skills/csharp/experimental/itsmskill/Dialogs/CreateTicketDialog.cs
  skills/csharp/experimental/itsmskill/Dialogs/ShowTicketDialog.cs
  skills/csharp/experimental/itsmskill/Dialogs/SkillDialogBase.cs
  skills/csharp/experimental/itsmskill/Dialogs/UpdateTicketDialog.cs
  skills/csharp/experimental/itsmskill/Models/SkillState.cs
Labels: PR: reviewed-approved

#2515 [Skills] synchronize deploy scripts by templates in master branch
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/calendarskill/calendarskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/calendarskill/calendarskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/calendarskill/calendarskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/eventskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/eventskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/eventskill/Deployment/Scripts/qna_functions.ps1
  skills/src/csharp/experimental/eventskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/hospitalityskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/hospitalityskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/hospitalityskill/Deployment/Scripts/qna_functions.ps1
  skills/src/csharp/experimental/hospitalityskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/itsmskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/itsmskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/itsmskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/musicskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/musicskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/musicskill/Deployment/Scripts/qna_functions.ps1
  skills/src/csharp/experimental/musicskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/phoneskill/phoneskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/phoneskill/phoneskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/phoneskill/phoneskill/Deployment/Scripts/luis_functions.ps1
  skills/src/csharp/phoneskill/phoneskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/update_cognitive_models.ps1
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/deploy_cognitive_models.ps1
Labels: PR: reviewed-approved

#2509 [Lib] move OpenDefaultApp to new lib folder
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Models/OpenDefaultApp.cs
Labels: PR: reviewed-approved

#2497 [Android] Fix gradle files for CI/CD & add App Center
  .gitignore
  samples/android/clients/VirtualAssistantClient/.gitignore
  samples/android/clients/VirtualAssistantClient/app/.gitignore
  samples/android/clients/VirtualAssistantClient/app/build.gradle
  samples/android/clients/VirtualAssistantClient/app/gradle/wrapper/gradle-wrapper.jar
  samples/android/clients/VirtualAssistantClient/app/gradle/wrapper/gradle-wrapper.properties
  samples/android/clients/VirtualAssistantClient/app/gradlew
  samples/android/clients/VirtualAssistantClient/app/gradlew.bat
  samples/android/clients/VirtualAssistantClient/app/src/main/assets/default_app_configuration.json
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/MainActivity.java
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/utils/AppConfiguration.java
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/utils/AppConfigurationManager.java
  samples/android/clients/VirtualAssistantClient/build.gradle
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/assets/default_configuration.json
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/ConfigurationManager.java
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/model/Configuration.java
Labels: PR: unreviewed

#2546 [HospitalityVA] fixes
  samples/csharp/assistants/HospitalityAssistant/HospitalityAssistant.csproj
  samples/csharp/assistants/HospitalityAssistant/Responses/Cancel/CancelStrings.Designer.cs
  samples/csharp/assistants/HospitalityAssistant/Responses/Escalate/EscalateStrings.Designer.cs
  samples/csharp/assistants/HospitalityAssistant/Responses/Main/MainStrings.Designer.cs
  samples/csharp/assistants/HospitalityAssistant/Responses/Onboarding/OnboardingStrings.Designer.cs
Labels: PR: reviewed-approved

#2545 [ITSM] updates for tickets, navigation
  skills/csharp/experimental/itsmskill/Content/Ticket.1.0.json
  skills/csharp/experimental/itsmskill/Content/Ticket.json
  skills/csharp/experimental/itsmskill/Content/TicketUpdate.1.0.json
  skills/csharp/experimental/itsmskill/Content/TicketUpdate.json
  skills/csharp/experimental/itsmskill/Content/TicketUpdateClose.1.0.json
  skills/csharp/experimental/itsmskill/Content/TicketUpdateClose.json
  skills/csharp/experimental/itsmskill/Deployment/Resources/LU/en/ITSM.lu
  skills/csharp/experimental/itsmskill/Deployment/Resources/LU/en/KnowledgeShow.lu
  skills/csharp/experimental/itsmskill/Deployment/Resources/LU/en/TicketClose.lu
  skills/csharp/experimental/itsmskill/Deployment/Resources/LU/en/TicketCreate.lu
  skills/csharp/experimental/itsmskill/Deployment/Resources/LU/en/secondary/KnowledgeShow.lu
  skills/csharp/experimental/itsmskill/Deployment/Resources/LU/en/secondary/TicketClose.lu
  skills/csharp/experimental/itsmskill/Deployment/Resources/LU/en/secondary/TicketCreate.lu
  skills/csharp/experimental/itsmskill/Deployment/Resources/LU/en/secondary/TicketShow.lu
  skills/csharp/experimental/itsmskill/Deployment/Resources/LU/en/secondary/TicketUpdate.lu
  skills/csharp/experimental/itsmskill/Dialogs/CreateTicketDialog.cs
  skills/csharp/experimental/itsmskill/Dialogs/ShowKnowledgeDialog.cs
  skills/csharp/experimental/itsmskill/Dialogs/ShowTicketDialog.cs
  skills/csharp/experimental/itsmskill/Dialogs/SkillDialogBase.cs
  skills/csharp/experimental/itsmskill/Dialogs/UpdateTicketDialog.cs
  skills/csharp/experimental/itsmskill/Models/AttributeType.cs
  skills/csharp/experimental/itsmskill/Models/ServiceNow/CreateTicketRequest.cs
  skills/csharp/experimental/itsmskill/Models/ServiceNow/TicketResponse.cs
  skills/csharp/experimental/itsmskill/Models/SkillState.cs
  skills/csharp/experimental/itsmskill/Models/Ticket.cs
  skills/csharp/experimental/itsmskill/Models/TicketCard.cs
  skills/csharp/experimental/itsmskill/Responses/Knowledge/KnowledgeResponses.json
  skills/csharp/experimental/itsmskill/Responses/Shared/SharedResponses.cs
  skills/csharp/experimental/itsmskill/Responses/Shared/SharedResponses.json
  skills/csharp/experimental/itsmskill/Responses/Shared/SharedStrings.Designer.cs
  skills/csharp/experimental/itsmskill/Responses/Shared/SharedStrings.resx
  skills/csharp/experimental/itsmskill/Responses/Ticket/TicketResponses.json
  skills/csharp/experimental/itsmskill/Services/IITServiceManagement.cs
  skills/csharp/experimental/itsmskill/Services/ITSMLuis.cs
  skills/csharp/experimental/itsmskill/Services/ServiceNow/Management.cs
  skills/csharp/experimental/itsmskill/cognitivemodels.json
Labels: PR: reviewed-approved

#2537 [Calendar] handle more exception type
  skills/csharp/calendarskill/CalendarSkill.csproj
  skills/csharp/calendarskill/Dialogs/CalendarSkillDialogBase.cs
  skills/csharp/calendarskill/Dialogs/MainDialog.cs
  skills/csharp/calendarskill/Responses/Shared/CalendarSharedResponses.cs
  skills/csharp/calendarskill/Responses/Shared/CalendarSharedResponses.de.json
  skills/csharp/calendarskill/Responses/Shared/CalendarSharedResponses.es.json
  skills/csharp/calendarskill/Responses/Shared/CalendarSharedResponses.fr.json
  skills/csharp/calendarskill/Responses/Shared/CalendarSharedResponses.it.json
  skills/csharp/calendarskill/Responses/Shared/CalendarSharedResponses.json
  skills/csharp/calendarskill/Responses/Shared/CalendarSharedResponses.zh.json
  skills/csharp/calendarskill/Services/GoogleAPI/GoogleClient.cs
  skills/csharp/calendarskill/Services/MSGraphAPI/GraphClient.cs
  skills/csharp/tests/calendarskill.tests/Flow/ChangeCalendarStatusFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/ConnectToMeetingFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/CreateCalendarFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/Fakes/MockLuisRecognizer.cs
  skills/csharp/tests/calendarskill.tests/Flow/GeneralSkillFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/NextCalendarFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/SummaryCalendarFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/TimeRemainingFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/UpdateCalendarFlowTests.cs
Labels: PR: reviewed-approved

#2494 [Calendar] support search meeting by title/attendee/location
  skills/csharp/calendarskill/Dialogs/CalendarSkillDialogBase.cs
  skills/csharp/calendarskill/Dialogs/FindContactDialog.cs
  skills/csharp/calendarskill/Dialogs/ShowEventsDialog.cs
  skills/csharp/calendarskill/Models/CalendarSkillState.cs
  skills/csharp/calendarskill/Responses/Shared/CalendarCommonStrings.Designer.cs
  skills/csharp/calendarskill/Responses/Shared/CalendarCommonStrings.de.resx
  skills/csharp/calendarskill/Responses/Shared/CalendarCommonStrings.es.resx
  skills/csharp/calendarskill/Responses/Shared/CalendarCommonStrings.fr.resx
  skills/csharp/calendarskill/Responses/Shared/CalendarCommonStrings.it.resx
  skills/csharp/calendarskill/Responses/Shared/CalendarCommonStrings.resx
  skills/csharp/calendarskill/Responses/Shared/CalendarCommonStrings.zh.resx
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.cs
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.de.json
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.es.json
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.fr.json
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.it.json
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.json
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.zh.json
  skills/csharp/calendarskill/Utilities/DisplayHelper.cs
  skills/csharp/tests/calendarskill.tests/Flow/SummaryCalendarFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/Utterances/FindMeetingTestUtterances.cs
Labels: PR: reviewed-approved

#2528 [Calendar] update create meeting flow wording
  skills/csharp/calendarskill/Dialogs/CreateEventDialog.cs
  skills/csharp/calendarskill/Dialogs/FindContactDialog.cs
  skills/csharp/calendarskill/Responses/CreateEvent/CreateEventResponses.de.json
  skills/csharp/calendarskill/Responses/CreateEvent/CreateEventResponses.es.json
  skills/csharp/calendarskill/Responses/CreateEvent/CreateEventResponses.fr.json
  skills/csharp/calendarskill/Responses/CreateEvent/CreateEventResponses.it.json
  skills/csharp/calendarskill/Responses/CreateEvent/CreateEventResponses.json
  skills/csharp/calendarskill/Responses/CreateEvent/CreateEventResponses.zh.json
  skills/csharp/calendarskill/Responses/FindContact/FindContactResponses.de.json
  skills/csharp/calendarskill/Responses/FindContact/FindContactResponses.es.json
  skills/csharp/calendarskill/Responses/FindContact/FindContactResponses.fr.json
  skills/csharp/calendarskill/Responses/FindContact/FindContactResponses.it.json
  skills/csharp/calendarskill/Responses/FindContact/FindContactResponses.json
  skills/csharp/calendarskill/Responses/FindContact/FindContactResponses.zh.json
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.de.json
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.es.json
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.fr.json
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.it.json
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.json
  skills/csharp/tests/calendarskill.tests/Flow/CreateCalendarFlowTests.cs
Labels: PR: unreviewed

#2492 [ITSM] return error if could not get user id
  skills/csharp/experimental/itsmskill/Responses/Shared/SharedStrings.Designer.cs
  skills/csharp/experimental/itsmskill/Responses/Shared/SharedStrings.resx
  skills/csharp/experimental/itsmskill/Services/ServiceNow/Management.cs
Labels: PR: unreviewed

#2536 Update MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs
Labels: PR: reviewed-approved

#2521 [Sdk] replace with defines
  sdk/csharp/libraries/microsoft.bot.builder.solutions.skills/SkillWebSocketBotAdapter.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Authentication/MultiProviderAuthDialog.cs
Labels: PR: reviewed-approved

#2382 [Calendar] add auth steps before call api
  skills/csharp/calendarskill/Dialogs/ChangeEventStatusDialog.cs
  skills/csharp/calendarskill/Dialogs/CreateEventDialog.cs
  skills/csharp/calendarskill/Dialogs/FindContactDialog.cs
  skills/csharp/calendarskill/Dialogs/UpdateEventDialog.cs
  skills/csharp/tests/calendarskill.tests/Flow/ChangeCalendarStatusFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/CreateCalendarFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/SummaryCalendarFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/UpdateCalendarFlowTests.cs
Labels: PR: reviewed-approved

#2512 [Email] Fix as designer's suggestion
  skills/csharp/emailskill/Dialogs/EmailSkillDialogBase.cs
  skills/csharp/emailskill/Dialogs/FindContactDialog.cs
  skills/csharp/emailskill/Dialogs/SendEmailDialog.cs
  skills/csharp/emailskill/Models/SendEmailStateModel.cs
  skills/csharp/emailskill/Prompts/GetRecreateInfoPrompt.cs
  skills/csharp/emailskill/Responses/DeleteEmail/DeleteEmailResponses.de.json
  skills/csharp/emailskill/Responses/DeleteEmail/DeleteEmailResponses.es.json
  skills/csharp/emailskill/Responses/DeleteEmail/DeleteEmailResponses.fr.json
  skills/csharp/emailskill/Responses/DeleteEmail/DeleteEmailResponses.it.json
  skills/csharp/emailskill/Responses/DeleteEmail/DeleteEmailResponses.json
  skills/csharp/emailskill/Responses/DeleteEmail/DeleteEmailResponses.zh.json
  skills/csharp/emailskill/Responses/SendEmail/SendEmailResponses.de.json
  skills/csharp/emailskill/Responses/SendEmail/SendEmailResponses.es.json
  skills/csharp/emailskill/Responses/SendEmail/SendEmailResponses.fr.json
  skills/csharp/emailskill/Responses/SendEmail/SendEmailResponses.it.json
  skills/csharp/emailskill/Responses/SendEmail/SendEmailResponses.json
  skills/csharp/emailskill/Responses/SendEmail/SendEmailResponses.zh.json
  skills/csharp/emailskill/Responses/Shared/EmailCommonStrings.Designer.cs
  skills/csharp/emailskill/Responses/Shared/EmailCommonStrings.de.resx
  skills/csharp/emailskill/Responses/Shared/EmailCommonStrings.es.resx
  skills/csharp/emailskill/Responses/Shared/EmailCommonStrings.fr.resx
  skills/csharp/emailskill/Responses/Shared/EmailCommonStrings.it.resx
  skills/csharp/emailskill/Responses/Shared/EmailCommonStrings.resx
  skills/csharp/emailskill/Responses/Shared/EmailCommonStrings.zh.resx
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.cs
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.de.json
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.es.json
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.fr.json
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.it.json
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.json
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.zh.json
  skills/csharp/emailskill/Responses/Shared/ResponseIdCollection.t4
  skills/csharp/experimental/phoneskill/Responses/Shared/ResponseIdCollection.t4
  skills/csharp/tests/emailskill.tests/Flow/ForwardEmailFlowTests.cs
  skills/csharp/tests/emailskill.tests/Flow/ReplyFlowTests.cs
  skills/csharp/tests/emailskill.tests/Flow/SendEmailFlowTests.cs
  skills/csharp/tests/emailskill.tests/Flow/ShowEmailFlowTests.cs
Labels: PR: reviewed-approved

#2551 [Calendar] support find event by time
  skills/csharp/calendarskill/Dialogs/CalendarSkillDialogBase.cs
  skills/csharp/calendarskill/Dialogs/ShowEventsDialog.cs
  skills/csharp/calendarskill/Models/AskParameterModel.cs
  skills/csharp/calendarskill/Responses/Shared/CalendarCommonStrings.Designer.cs
  skills/csharp/calendarskill/Responses/Shared/CalendarCommonStrings.de.resx
  skills/csharp/calendarskill/Responses/Shared/CalendarCommonStrings.es.resx
  skills/csharp/calendarskill/Responses/Shared/CalendarCommonStrings.fr.resx
  skills/csharp/calendarskill/Responses/Shared/CalendarCommonStrings.it.resx
  skills/csharp/calendarskill/Responses/Shared/CalendarCommonStrings.resx
  skills/csharp/calendarskill/Responses/Shared/CalendarCommonStrings.zh.resx
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.cs
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.de.json
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.es.json
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.fr.json
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.it.json
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.json
  skills/csharp/calendarskill/Responses/Summary/SummaryResponses.zh.json
  skills/csharp/calendarskill/Utilities/AskParameterTemplate.cs
Labels: PR: reviewed-approved

#2511 [POI] update flow
  skills/csharp/pointofinterestskill/Dialogs/GetDirectionsDialog.cs
  skills/csharp/pointofinterestskill/Dialogs/MainDialog.cs
  skills/csharp/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
  skills/csharp/pointofinterestskill/Models/PointOfInterestSkillState.cs
  skills/csharp/pointofinterestskill/Responses/Shared/POISharedResponses.de.json
  skills/csharp/pointofinterestskill/Responses/Shared/POISharedResponses.es.json
  skills/csharp/pointofinterestskill/Responses/Shared/POISharedResponses.fr.json
  skills/csharp/pointofinterestskill/Responses/Shared/POISharedResponses.it.json
  skills/csharp/pointofinterestskill/Responses/Shared/POISharedResponses.json
  skills/csharp/pointofinterestskill/Responses/Shared/POISharedResponses.zh.json
  skills/csharp/tests/pointofinterestskill.tests/Flow/PointOfInterestDialogTests.cs
  skills/csharp/tests/pointofinterestskill.tests/Flow/Utterances/GeneralTestUtterances.cs
Labels: PR: reviewed-approved

#2554 [Email Skill] resouce translate issue fix
  skills/csharp/emailskill/Responses/DeleteEmail/DeleteEmailResponses.de.json
  skills/csharp/emailskill/Responses/DeleteEmail/DeleteEmailResponses.es.json
  skills/csharp/emailskill/Responses/DeleteEmail/DeleteEmailResponses.fr.json
  skills/csharp/emailskill/Responses/DeleteEmail/DeleteEmailResponses.it.json
  skills/csharp/emailskill/Responses/DeleteEmail/DeleteEmailResponses.zh.json
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.de.json
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.es.json
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.fr.json
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.it.json
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.zh.json
Labels: PR: reviewed-approved

#2562 [POI] geo uri doc
  docs/_docs/skills/samples/point-of-interest.md
Labels: PR: reviewed-approved

#2548 [ToDo] Fix as designer's suggestion
  skills/csharp/tests/todoskill.tests/Flow/MarkAllToDosFlowTests.cs
  skills/csharp/tests/todoskill.tests/Flow/MarkToDoFlowTests.cs
  skills/csharp/todoskill/Deployment/Resources/LU/en/ToDo.lu
  skills/csharp/todoskill/Dialogs/MarkToDoItemDialog.cs
  skills/csharp/todoskill/Responses/MarkToDo/MarkToDoResponses.cs
  skills/csharp/todoskill/Responses/MarkToDo/MarkToDoResponses.de.json
  skills/csharp/todoskill/Responses/MarkToDo/MarkToDoResponses.es.json
  skills/csharp/todoskill/Responses/MarkToDo/MarkToDoResponses.fr.json
  skills/csharp/todoskill/Responses/MarkToDo/MarkToDoResponses.it.json
  skills/csharp/todoskill/Responses/MarkToDo/MarkToDoResponses.json
  skills/csharp/todoskill/Responses/MarkToDo/MarkToDoResponses.zh.json
Labels: PR: reviewed-approved

#2572 [Calendar] replace OpenDefaultApp with the class in lib
  skills/csharp/calendarskill/CalendarSkill.csproj
  skills/csharp/calendarskill/Dialogs/JoinEventDialog.cs
  skills/csharp/calendarskill/Models/OpenDefaultApp.cs
Labels: PR: reviewed-approved

#2578 [Docs] Capture review notes
  docs/_docs/overview/skills.md
  docs/_docs/overview/virtual-assistant-solution.md
  docs/index.md
Labels: PR: unreviewed

#2576 [Skills] update google support doc
  docs/_docs/skills/samples/calendar.md
  docs/_docs/skills/samples/email.md
Labels: PR: unreviewed

#2571 [POI] convert to data uri to hide subscription key
  skills/csharp/pointofinterestskill/Services/AzureMapsGeoSpatialService.cs
Labels: PR: reviewed-approved

#2522 [Sdk] do not send Handoff to Teams
  sdk/csharp/libraries/microsoft.bot.builder.solutions.skills/SkillCallingRequestHandler.cs
Labels: PR: reviewed-approved

#2581 [POI] fix test
  skills/csharp/tests/pointofinterestskill.tests/API/AzureMapsGeoSpatialServiceTests.cs
  skills/csharp/tests/pointofinterestskill.tests/API/Fakes/MockHttpClientHandlerGen.cs
Labels: PR: reviewed-approved

#2561 [Skills] set telemetry
  sdk/csharp/libraries/microsoft.bot.builder.solutions.skills/SkillDialog.cs
  skills/csharp/calendarskill/Adapters/CalendarSkillWebSocketBotAdapter.cs
  skills/csharp/emailskill/Adapters/EmailSkillWebSocketBotAdapter.cs
  skills/csharp/experimental/automotiveskill/Adapters/AutomotiveSkillWebSocketBotAdapter.cs
  skills/csharp/experimental/bingsearchskill/Adapters/CustomSkillAdapter.cs
  skills/csharp/experimental/eventskill/Adapters/EventSkillAdapter.cs
  skills/csharp/experimental/hospitalityskill/Adapters/HospitalitySkillAdapter.cs
  skills/csharp/experimental/itsmskill/Adapters/CustomSkillAdapter.cs
  skills/csharp/experimental/musicskill/Adapters/CustomSkillAdapter.cs
  skills/csharp/experimental/newsskill/Adapters/NewsSkillWebSocketBotAdapter.cs
  skills/csharp/experimental/phoneskill/Adapters/PhoneSkillWebSocketBotAdapter.cs
  skills/csharp/experimental/restaurantbookingskill/Adapters/RestaurantSkillWebSocketBotAdapter.cs
  skills/csharp/experimental/weatherskill/Adapters/CustomSkillAdapter.cs
  skills/csharp/pointofinterestskill/Adapters/POISkillWebSocketBotAdapter.cs
  skills/csharp/todoskill/Adapters/ToDoSkillWebSocketBotAdapter.cs
  templates/Skill-Template/csharp/Sample/SkillSample/Adapters/CustomSkillAdapter.cs
  templates/Skill-Template/csharp/Template/Skill/Adapters/CustomSkillAdapter.cs
Labels: PR: reviewed-approved

#2575 [botskills] update split and err
  tools/botskills/src/utils/authenticationUtils.ts
Labels: PR: reviewed-approved

#2588 [Weather] use IsNaN instead of comparison
  skills/csharp/experimental/weatherskill/Dialogs/ForecastDialog.cs
  skills/csharp/experimental/weatherskill/Models/SkillState.cs
Labels: PR: reviewed-approved

#2579 [VA][Skill] fix event, remove BuildServiceProvider
  skills/csharp/calendarskill/Startup.cs
  skills/csharp/emailskill/Startup.cs
  skills/csharp/experimental/automotiveskill/Startup.cs
  skills/csharp/experimental/bingsearchskill/Startup.cs
  skills/csharp/experimental/eventskill/Startup.cs
  skills/csharp/experimental/hospitalityskill/Startup.cs
  skills/csharp/experimental/itsmskill/Startup.cs
  skills/csharp/experimental/musicskill/Startup.cs
  skills/csharp/experimental/newsskill/Startup.cs
  skills/csharp/experimental/restaurantbookingskill/Startup.cs
  skills/csharp/experimental/weatherskill/Startup.cs
  skills/csharp/pointofinterestskill/Startup.cs
  skills/csharp/todoskill/Startup.cs
  templates/Skill-Template/csharp/Sample/SkillSample/Startup.cs
  templates/Skill-Template/csharp/Template/Skill/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Startup.cs
Labels: PR: reviewed-approved

#2580 [Skills] Add/update transcripts
  docs/_docs/overview/virtual-assistant-solution.md
  docs/_docs/skills/samples/experimental.md
  docs/assets/transcripts/skills-hospitality.transcript
  docs/assets/transcripts/skills-itsm.transcript
  docs/assets/transcripts/skills-pointofinterest.transcript
Labels: PR: reviewed-approved

#2582 [Restaurant] update transcript and data uri code
  docs/_docs/skills/samples/experimental.md
  docs/assets/transcripts/skills-restaurantbooking.transcript
  skills/csharp/experimental/restaurantbookingskill/Models/RestaurantBookingState.cs
  skills/csharp/experimental/restaurantbookingskill/RestaurantBookingSkill.csproj
  skills/csharp/experimental/restaurantbookingskill/Utilities/UrlResolver.cs
Labels: PR: reviewed-approved

#2593 [Libs] Update to sdk 4.6.0-rc0
  sdk/csharp/libraries/microsoft.bot.builder.solutions.skills/ISkillIntentRecognizer.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions.skills/Microsoft.Bot.Builder.Solutions.Skills.csproj
  sdk/csharp/libraries/microsoft.bot.builder.solutions.skills/Protocol/RouteAction.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions.skills/Protocol/RouteContext.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions.skills/Protocol/Router.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions.skills/SkillCallingRequestHandler.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions.skills/SkillWebSocketAdapter.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions.skills/SkillWebSocketBotAdapter.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions.skills/SkillWebSocketRequestHandler.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions.skills/SkillWebSocketTransport.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions.skills/SlotEqualityComparer.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Microsoft.Bot.Builder.Solutions.csproj
Labels: PR: reviewed-approved

#2585 [Libs] Deprecated routerDialog moved changes to ActivityHandlerDialog
  sdk/csharp/Directory.Build.props
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Dialogs/ActivityHandlerDialog.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Dialogs/RouterDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/readme.md
Labels: PR: reviewed-approved

#2595 [Template]Update VASample with 4.6rc0 sdk
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Adapters/DefaultWebSocketAdapter.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Controllers/BotController.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
Labels: PR: reviewed-approved

#2599 [ITSM] use dot instead of number to remove single '1' step
  docs/_docs/skills/samples/experimental.md
Labels: PR: reviewed-approved

#2601 [VA] Updated to latest sdk and libs
  templates/Virtual-Assistant-Template/csharp/Directory.Build.props
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
Labels: PR: unreviewed

#2598 [Sdk] fix BotTestBase
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Testing/BotTestBase.cs
Labels: PR: reviewed-approved

#2603 [LG Updates] Post Merge and Lib updates
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/BotTestBase.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/InterruptionTests.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/OnboardingDialogTests.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
Labels: PR: unreviewed

#2597 [Calendar][News] update transcript
  docs/assets/transcripts/skills-calendar.transcript
  docs/assets/transcripts/skills-news.transcript
Labels: PR: reviewed-approved

#2592 [Email] Update doc and transcripts
  docs/_docs/skills/samples/email.md
  docs/assets/transcripts/skills-email.transcript
Labels: PR: reviewed-approved

#2591 [ITSM][POI] transcripts
  docs/assets/transcripts/skills-pointofinterest.transcript
  skills/csharp/experimental/itsmskill/Dialogs/CreateTicketDialog.cs
  skills/csharp/experimental/itsmskill/Dialogs/SkillDialogBase.cs
  skills/csharp/experimental/itsmskill/Responses/Knowledge/KnowledgeResponses.cs
  skills/csharp/experimental/itsmskill/Responses/Knowledge/KnowledgeResponses.json
  skills/csharp/experimental/restaurantbookingskill/Utilities/UrlResolver.cs
  skills/csharp/pointofinterestskill/Services/AzureMapsGeoSpatialService.cs
  skills/csharp/pointofinterestskill/Services/FoursquareGeoSpatialService.cs
Labels: PR: reviewed-approved

#2590 [ToDo] Update doc
  docs/_docs/skills/samples/to-do.md
Labels: PR: reviewed-approved

#2600 [Bing Search Skill] Transcript and doc update
  docs/_docs/skills/samples/experimental.md
  docs/assets/transcripts/skills-bingsearch.transcript
Labels: PR: unreviewed

#2610 Proactive notifications tutorial and make samples shared
  docs/_config.yml
  docs/_data/toc.yml
  docs/_docs/virtual-assistant/handbook/enterprise-notifications.md
  docs/_docs/virtual-assistant/samples/enterprise-assistant.md
  docs/_docs/virtual-assistant/tutorials/enable-proactive-notifications/1-intro.md
  docs/_docs/virtual-assistant/tutorials/enable-proactive-notifications/2-event-producer.md
  docs/_docs/virtual-assistant/tutorials/enable-proactive-notifications/3-event-handler.md
  docs/_docs/virtual-assistant/tutorials/enable-proactive-notifications/4-virtual-assistant.md
  docs/_docs/virtual-assistant/tutorials/enable-proactive-notifications/5-run-your-solution.md
  docs/assets/css/index.scss
  docs/assets/css/syntax.css
  docs/assets/images/proactive-notifications/emulator-settings.png
  docs/assets/images/proactive-notifications/event-producer.png
  samples/csharp/assistants/enterprise-assistant/EnterpriseAssistant.sln
  samples/csharp/assistants/enterprise-assistant/EventProducer/appsettings.json
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Models/EventData.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Services/BotSettings.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Startup.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/clients/Clients.sln
  samples/csharp/clients/event-handler.function-app/.gitignore
  samples/csharp/clients/event-handler.function-app/EventDataType.cs
  samples/csharp/clients/event-handler.function-app/EventHandler.csproj
  samples/csharp/clients/event-handler.function-app/Function1.cs
  samples/csharp/clients/event-handler.function-app/UserPreference.cs
  samples/csharp/clients/event-handler.function-app/host.json
  samples/csharp/clients/event-producer.event-hub/EventProducer.csproj
  samples/csharp/clients/event-producer.event-hub/Program.cs
  samples/csharp/clients/event-producer.event-hub/appsettings.json
Labels: PR: reviewed-approved

#2612 [VA] Cleaned up comments and moved to 4.6-preview-rc1 libs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/BotTestBase.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/MainDialogTests.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/OnboardingDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Models/UserProfileState.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.de-de.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.es-es.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.fr-fr.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.it-it.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.zh-cn.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
Labels: PR: reviewed-approved

#2589 [Calendar] update document and fix some issue
  docs/_docs/skills/samples/calendar.md
  docs/_docs/skills/samples/email.md
  skills/csharp/calendarskill/Dialogs/CalendarSkillDialogBase.cs
  skills/csharp/calendarskill/Dialogs/UpdateEventDialog.cs
  skills/csharp/calendarskill/Responses/Shared/CalendarCommonStrings.Designer.cs
  skills/csharp/calendarskill/Responses/Shared/CalendarCommonStrings.resx
  skills/csharp/calendarskill/Services/MSGraphAPI/MSGraphCalendarAPI.cs
  skills/csharp/tests/calendarskill.tests/Flow/UpdateCalendarFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/Utterances/UpdateMeetingTestUtterances.cs
Labels: PR: reviewed-approved

#2616 [Calendar][POI] add tel prefix in telephone uri
  skills/csharp/calendarskill/Dialogs/JoinEventDialog.cs
  skills/csharp/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
Labels: PR: reviewed-approved

#2614 [Skills] Update the SDK version to the latest RC
  skills/csharp/Directory.Build.props
  skills/csharp/calendarskill/CalendarSkill.csproj
  skills/csharp/emailskill/EmailSkill.csproj
  skills/csharp/experimental/automotiveskill/AutomotiveSkill.csproj
  skills/csharp/experimental/bingsearchskill/BingSearchSkill.csproj
  skills/csharp/experimental/eventskill/EventSkill.csproj
  skills/csharp/experimental/hospitalityskill/HospitalitySkill.csproj
  skills/csharp/experimental/itsmskill/ITSMSkill.csproj
  skills/csharp/experimental/musicskill/MusicSkill.csproj
  skills/csharp/experimental/newsskill/NewsSkill.csproj
  skills/csharp/experimental/phoneskill/PhoneSkill.csproj
  skills/csharp/experimental/restaurantbookingskill/RestaurantBookingSkill.csproj
  skills/csharp/experimental/weatherskill/WeatherSkill.csproj
  skills/csharp/pointofinterestskill/PointOfInterestSkill.csproj
  skills/csharp/todoskill/ToDoSkill.csproj
Labels: PR: reviewed-approved

#2619 Added support for teams authentication
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Authentication/MultiProviderAuthDialog.cs
  sdk/csharp/tests/microsoft.bot.builder.solutions.tests/Extensions/ListExTests.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Bots/DefaultActivityHandler.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs
Labels: PR: unreviewed

#2560 [Skills] use single comma for scopes
  skills/csharp/calendarskill/Services/GoogleAPI/GoogleClient.cs
  skills/csharp/calendarskill/appsettings.json
  skills/csharp/calendarskill/manifestTemplate.json
  skills/csharp/emailskill/Services/GoogleAPI/GoogleClient.cs
  skills/csharp/emailskill/appsettings.json
  skills/csharp/emailskill/manifestTemplate.json
  skills/csharp/experimental/phoneskill/Services/GoogleAPI/GoogleClient.cs
  skills/csharp/todoskill/manifestTemplate.json
Labels: PR: reviewed-approved
