Repository microsoft/botframework-solutions, pull requests merged in 2019-08, with the labels that each got.

#2009 Shzhen/todo lg
  skills/src/csharp/todoskill/todoskill/Dialogs/ToDoSkillDialogBase.cs
  skills/src/csharp/todoskill/todoskill/Responses/AddToDo/AddToDoCardTexts.lg
  skills/src/csharp/todoskill/todoskill/Responses/AddToDo/AddToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Responses/DeleteToDo/DeleteToDoCardTexts.lg
  skills/src/csharp/todoskill/todoskill/Responses/DeleteToDo/DeleteToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Responses/Main/ToDoMainResponses.lg
  skills/src/csharp/todoskill/todoskill/Responses/MarkToDo/MarkToDoCardTexts.lg
  skills/src/csharp/todoskill/todoskill/Responses/MarkToDo/MarkToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Responses/Shared/Card.lg
  skills/src/csharp/todoskill/todoskill/Responses/Shared/CardSummaryTexts.lg
  skills/src/csharp/todoskill/todoskill/Responses/Shared/ResponsesAndTexts.lg
  skills/src/csharp/todoskill/todoskill/Responses/Shared/ToDoSharedResponses.lg
  skills/src/csharp/todoskill/todoskill/Responses/ShowToDo/ShowToDoCardTexts.lg
  skills/src/csharp/todoskill/todoskill/Responses/ShowToDo/ShowToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/ToDoSkill.csproj
Labels: PR: unreviewed

#1976 [Lib] Fallback lib change
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Dialogs/DispatchDialog.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Models/DispatchIntent.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialog.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Dialogs/RouterDialog.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Dialogs/RouterDialogTurnResult.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Dialogs/RouterDialogTurnStatus.cs
Labels: PR: reviewed-approved

#2013 [LG] Email LG refactor and UT
  skills/src/csharp/emailskill/emailskill/Dialogs/ShowEmailDialog.cs
  skills/src/csharp/emailskill/emailskill/Responses/Cards/ConfirmCard_RecipientLessThanFive.lg
  skills/src/csharp/emailskill/emailskill/Responses/Cards/ConfirmCard_RecipientMoreThanFive.lg
  skills/src/csharp/emailskill/emailskill/Responses/Cards/DetailCard_RecipientLessThanFive.lg
  skills/src/csharp/emailskill/emailskill/Responses/Cards/DetailCard_RecipientMoreThanFive.lg
  skills/src/csharp/emailskill/emailskill/Responses/Cards/EmailContentPreview.lg
  skills/src/csharp/emailskill/emailskill/Responses/Cards/EmailDetailCard.lg
  skills/src/csharp/emailskill/emailskill/Responses/Cards/EmailOverviewCard.lg
  skills/src/csharp/emailskill/emailskill/Responses/Cards/EmailOverviewItem.lg
  skills/src/csharp/emailskill/emailskill/Responses/Cards/EmailWithOutButtonCard.lg
  skills/src/csharp/emailskill/emailskill/Responses/DeleteEmail/DeleteEmail.lg
  skills/src/csharp/emailskill/emailskill/Responses/DeleteEmail/EmailDetailCard.lg
  skills/src/csharp/emailskill/emailskill/Responses/FindContact/FindContact.lg
  skills/src/csharp/emailskill/emailskill/Responses/ForwardEmail/ForwardEmail.lg
  skills/src/csharp/emailskill/emailskill/Responses/ReplyEmail/ConfirmCard_RecipientLessThanFive.lg
  skills/src/csharp/emailskill/emailskill/Responses/ReplyEmail/ConfirmCard_RecipientMoreThanFive.lg
  skills/src/csharp/emailskill/emailskill/Responses/ReplyEmail/ReplyEmail.lg
  skills/src/csharp/emailskill/emailskill/Responses/SendEmail/ConfirmCard_RecipientLessThanFive.lg
  skills/src/csharp/emailskill/emailskill/Responses/SendEmail/ConfirmCard_RecipientMoreThanFive.lg
  skills/src/csharp/emailskill/emailskill/Responses/SendEmail/EmailWithOutButtonCard.lg
  skills/src/csharp/emailskill/emailskill/Responses/SendEmail/SendEmail.lg
  skills/src/csharp/emailskill/emailskill/Responses/Shared/ConfirmCard_RecipientLessThanFive.lg
  skills/src/csharp/emailskill/emailskill/Responses/Shared/ConfirmCard_RecipientMoreThanFive.lg
  skills/src/csharp/emailskill/emailskill/Responses/Shared/EmailContentPreview.lg
  skills/src/csharp/emailskill/emailskill/Responses/Shared/EmailWithOutButtonCard.lg
  skills/src/csharp/emailskill/emailskill/Responses/Shared/Shared.lg
  skills/src/csharp/emailskill/emailskill/Responses/ShowEmail/DetailCard_RecipientLessThanFive.lg
  skills/src/csharp/emailskill/emailskill/Responses/ShowEmail/DetailCard_RecipientMoreThanFive.lg
  skills/src/csharp/emailskill/emailskill/Responses/ShowEmail/EmailDetailCard.lg
  skills/src/csharp/emailskill/emailskill/Responses/ShowEmail/ShowEmail.lg
  skills/src/csharp/emailskill/emailskill/Startup.cs
  skills/src/csharp/emailskill/emailskilltest/Flow/EmailBotTestBase.cs
Labels: PR: unreviewed

#2003 updated deployment scripts doc
  docs/reference/assistant/deploymentscripts.md
Labels: Changelog: Skip, PR: reviewed-approved, PR: unreviewed

#2018 Consolidated deployment docs
  docs/howto/assistant/customizedeployment.md
  docs/howto/assistant/updatedeploymentscripts.md
  docs/readme.md
  docs/reference/assistant/deploymentscripts.md
Labels: Changelog: Skip, PR: reviewed-approved

#1996 update GeographyV2 (#1995)
  skills/src/csharp/experimental/restaurantbooking/Dialogs/SkillDialogBase.cs
  skills/src/csharp/experimental/restaurantbooking/Services/ReservationLuis.cs
  skills/src/csharp/experimental/weatherskill/Dialogs/SkillDialogBase.cs
  skills/src/csharp/experimental/weatherskill/Services/WeatherSkillLuis.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/MainDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Services/PointOfInterestLuis.cs
Labels: PR: reviewed-approved

#1994 use azure map for GetPointOfInterestListByAddressAsync (#1988)
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/FindParkingDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
Labels: PR: reviewed-approved

#1993 POI returns no route for not covered areas (#1960)
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/RouteDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/POISharedResponses.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/POISharedResponses.de.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/POISharedResponses.es.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/POISharedResponses.fr.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/POISharedResponses.it.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/POISharedResponses.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/POISharedResponses.zh.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Services/AzureMapsGeoSpatialService.cs
Labels: PR: reviewed-approved

#2012 [Future to Next] Fallback Lib change
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/Mocks/MockSkillTransport.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/SkillDialogTest.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/ISkillIntentRecognizer.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/ISkillTransport.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Models/SkillEvents.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillCallingRequestHandler.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialog.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillSwitchConfirmOption.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketBotAdapter.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketTransport.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Dialogs/RouterDialog.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Dialogs/RouterDialogTurnResult.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Dialogs/RouterDialogTurnStatus.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/IFallbackRequestProvider.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.Designer.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.de.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.es.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.fr.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.it.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Resources/CommonStrings.zh.resx
Labels: PR: reviewed-approved

#2027 Yuesu/va lg preview
  skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
  skills/src/csharp/calendarskill/calendarskill/Dialogs/CalendarSkillDialogBase.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/ChangeEventStatusDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/ConnectToMeetingDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/CreateEventDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/FindContactDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/MainDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/SummaryDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/TimeRemainingDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/UpcomingEventDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/UpdateEventDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Models/EventModel.cs
  skills/src/csharp/calendarskill/calendarskill/Responses/ChangeEventStatus/ChangeEventStatusDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/ChangeEventStatus/ChangeEventStatusDialog.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/CreateEvent/CreateEventDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/CreateEvent/CreateEventDialog.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/FindContact/FindContactDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/FindContact/FindContactDialog.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/JoinEvent/JoinEventDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/JoinEvent/JoinEventDialog.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/Main/MainDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/Main/MainDialog.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/Shared.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/Shared.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/Summary/SummaryDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/Summary/SummaryDialog.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/TimeRemaining/TimeRemainingDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/TimeRemaining/TimeRemainingDialog.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/UpcomingEvent/UpcomingEventDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/UpcomingEvent/UpcomingEventDialog.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/UpdateEvent/UpdateEventDialog.en-us.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/UpdateEvent/UpdateEventDialog.lg
  skills/src/csharp/calendarskill/calendarskill/Utilities/LGHelper.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/CalendarBotTestBase.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/CreateCalendarFlowTests.cs
Labels: PR: unreviewed

#2019 Added doc on skill responses
  docs/readme.md
  docs/reference/skills/responses.md
Labels: PR: reviewed-approved

#2015 [botskills] Update Documentation Link
  tools/botskills/src/utils/authenticationUtils.ts
Labels: Customer, PR: reviewed-approved, Type: Bug, supportability

#2021 [Botskills] Prevent LUDown from breaking Botskills process
  tools/botskills/src/utils/childProcessUtils.ts
Labels: PR: reviewed-approved

#2035 [Email LG] package migration and UT fixing
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Microsoft.Bot.Builder.Skills.csproj
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Microsoft.Bot.Builder.Solutions.csproj
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Testing/DefaultTestAdapter.cs
  skills/src/csharp/emailskill/emailskill/Adapters/EmailSkillWebSocketBotAdapter.cs
  skills/src/csharp/emailskill/emailskill/EmailSkill.csproj
  skills/src/csharp/emailskill/emailskill/Responses/Cards/EmailDetailCard.lg
  skills/src/csharp/emailskill/emailskill/Responses/Cards/EmailOverviewCard.lg
  skills/src/csharp/emailskill/emailskill/Responses/Cards/EmailOverviewItem.lg
  skills/src/csharp/emailskill/emailskill/Responses/Cards/EmailWithOutButtonCard.lg
  skills/src/csharp/emailskill/emailskill/Responses/Main/MainDialog.lg
  skills/src/csharp/emailskill/emailskilltest/Flow/DeleteEmailFlowTests.cs
  skills/src/csharp/emailskill/emailskilltest/Flow/EmailBotTestBase.cs
  skills/src/csharp/emailskill/emailskilltest/Flow/ForwardEmailFlowTests.cs
  skills/src/csharp/emailskill/emailskilltest/Flow/ReplyFlowTests.cs
  skills/src/csharp/emailskill/emailskilltest/Flow/SendEmailFlowTests.cs
  skills/src/csharp/emailskill/emailskilltest/Flow/ShowEmailFlowTests.cs
Labels: PR: unreviewed

#2036 Yuesu/va lg preview
  skills/src/csharp/calendarskill/calendarskilltest/Flow/CalendarBotTestBase.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/ConnectToMeetingFlowTests.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/CreateCalendarFlowTests.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/DeleteCalendarFlowTests.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/NextCalendarFlowTests.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/SummaryCalendarFlowTests.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/TimeRemainingFlowTests.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/UpdateCalendarFlowTests.cs
Labels: PR: unreviewed

#2037 Shzhen/todo lg
  skills/src/csharp/todoskill/todoskill/Responses/AddToDo/AddToDoResponses.lg
  skills/src/csharp/todoskill/todoskill/Responses/Main/ToDoMainResponses.lg
  skills/src/csharp/todoskill/todoskill/Responses/Shared/Card.lg
  skills/src/csharp/todoskill/todoskill/Responses/Shared/ToDoSharedResponses.lg
  skills/src/csharp/todoskill/todoskill/ToDoSkill.csproj
  skills/src/csharp/todoskill/todoskilltest/Flow/AddToDoFlowTests.cs
  skills/src/csharp/todoskill/todoskilltest/Flow/DeleteAllToDosFlowTests.cs
  skills/src/csharp/todoskill/todoskilltest/Flow/DeleteToDoFlowTests.cs
  skills/src/csharp/todoskill/todoskilltest/Flow/MarkAllToDosFlowTests.cs
  skills/src/csharp/todoskill/todoskilltest/Flow/MarkToDoFlowTests.cs
  skills/src/csharp/todoskill/todoskilltest/Flow/ShowToDoFlowTests.cs
  skills/src/csharp/todoskill/todoskilltest/Flow/ToDoBotTestBase.cs
Labels: PR: unreviewed

#1948 Use consistent header name for authorization header
  lib/typescript/botbuilder-skills/src/http/skillHttpAdapter.ts
Labels: PR: reviewed-approved

#2024 add POI_TYPE nearest to provide nearest result (#1986)
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/de/PointOfInterest.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/en/PointOfInterest.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/es/PointOfInterest.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/fr/PointOfInterest.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/it/PointOfInterest.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/zh/PointOfInterest.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/FindParkingDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/MainDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Models/AzureMaps/SearchResult.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Models/PointOfInterestSkillState.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Services/AzureMapsGeoSpatialService.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Services/FoursquareGeoSpatialService.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Services/GeoSpatialServiceTypes.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Services/IGeoSpatialService.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Services/PointOfInterestLuis.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/API/Fakes/MockHttpClientHandlerGen.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/Fakes/MockGeneralIntent.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/Fakes/MockGeneralLuisRecognizer.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/Fakes/MockPointOfInterestIntent.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/Fakes/MockPointOfInterestLuisRecognizer.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/PointOfInterestDialogTests.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/PointOfInterestTestBase.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/Strings/ContextStrings.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/Utterances/BaseTestUtterances.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/Utterances/CancelRouteUtterances.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/Utterances/FindParkingUtterances.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/Utterances/FindPointOfInterestUtterances.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/Utterances/GeneralTestUtterances.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/Utterances/GeneralUtterances.Designer.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/Utterances/GeneralUtterances.resx
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/Utterances/PointOfInterestDialogUtterances.Designer.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/Utterances/PointOfInterestDialogUtterances.resx
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/Utterances/RouteFromXToYUtterances.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/PointOfInterestSkillTests.csproj
Labels: PR: reviewed-approved

#2038 [botskills] Cherry pick from next branch to workaround ludown issue
  tools/botskills/src/utils/childProcessUtils.ts
Labels: PR: reviewed-approved

#2039 Updated GitHub templates to apply `Bot Service` tag
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: PR: reviewed-approved

#2032 Ensure semantic action in every turn
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialog.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketBotAdapter.cs
Labels: PR: reviewed-approved

#2028 [HospitalitySkill] Adding RequestItems dialog
  skills/src/csharp/experimental/hospitalityskill/Data/AvailableItems.json
  skills/src/csharp/experimental/hospitalityskill/Deployment/Resources/LU/en/Hospitality.lu
  skills/src/csharp/experimental/hospitalityskill/Dialogs/MainDialog.cs
  skills/src/csharp/experimental/hospitalityskill/Dialogs/RequestItemDialog.cs
  skills/src/csharp/experimental/hospitalityskill/HospitalitySkill.csproj
  skills/src/csharp/experimental/hospitalityskill/Models/HospitalitySkillState.cs
  skills/src/csharp/experimental/hospitalityskill/Responses/RequestItem/RequestItemResponses.cs
  skills/src/csharp/experimental/hospitalityskill/Responses/RequestItem/RequestItemResponses.json
  skills/src/csharp/experimental/hospitalityskill/Responses/RequestItem/RequestItemResponses.tt
  skills/src/csharp/experimental/hospitalityskill/Services/HospitalityLuis.cs
  skills/src/csharp/experimental/hospitalityskill/Services/HotelService.cs
  skills/src/csharp/experimental/hospitalityskill/Services/IHotelService.cs
  skills/src/csharp/experimental/hospitalityskill/Startup.cs
Labels: PR: reviewed-approved

#2047 Yuesu/va lg preview
  skills/src/csharp/calendarskill/calendarskill/Dialogs/FindContactDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Responses/CreateEvent/CreateEventDialog.lg
  skills/src/csharp/calendarskill/calendarskill/Responses/FindContact/FindContactDialog.lg
Labels: PR: unreviewed

#2022 enable JWTToken auth by default
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/ManifestTests.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/Mocks/MockSkillWebSocketAdapter.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Auth/MsJWTAuthenticationProvider.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Models/SkillSettings.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketAdapter.cs
Labels: PR: reviewed-approved

#2052 support response manifest
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Models/Manifest/ActionDefinition.cs
Labels: PR: reviewed-approved

#2056 fix passing header with StreamingExtensions
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Auth/MsJWTAuthenticationProvider.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketTransport.cs
Labels: PR: reviewed-approved

#2026 poi uses lg
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Adapters/POISkillWebSocketBotAdapter.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Bots/DialogBot.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/CancelRouteDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/FindParkingDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/FindPointOfInterestDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/MainDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/RouteDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Models/PointofInterestModel.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Models/RouteDirectionsModel.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/PointOfInterestSkill.csproj
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/CancelRoute/CancelRouteResponses.lg
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Cards/PointOfInterestDetails.lg
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Cards/PointOfInterestDetailsWithRoute.lg
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Cards/PointOfInterestDetailsWithRoute_1_0.lg
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Cards/PointOfInterestDetails_1_0.lg
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/FindPointOfInterest/FindPointOfInterestResponses.lg
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Main/POIMainResponses.lg
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Route/RouteResponses.lg
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/POISharedResponses.lg
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Services/BotServices.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Startup.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Utilities/LGHelper.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/Flow/PointOfInterestTestBase.cs
Labels: PR: unreviewed

#2050 [Automotive Skill] Replace event name with settings name
  skills/src/csharp/automotiveskill/automotiveskill/Dialogs/VehicleSettingsDialog.cs
  skills/src/csharp/automotiveskill/automotiveskilltest/Flow/VehicleSettingsTests.cs
Labels: PR: reviewed-approved

#2043 change exising to existing
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/calendarskill/calendarskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/deploy_cognitive_models.ps1
  solutions/linkedaccounts/Microsoft.Identity.Web/README.md
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/deploy_cognitive_models.ps1
Labels: PR: reviewed-approved

#2069 return semantic response as dialog result
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/Mocks/MockSkillTransport.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/ISkillTransport.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillCallingRequestHandler.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialog.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketTransport.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Dialogs/RouterDialog.cs
Labels: PR: reviewed-approved

#2070 Weather skill and Restaurant Booking skill fixes
  skills/src/csharp/experimental/restaurantbooking/Deployment/Resources/LU/en/Restaurant.lu
  skills/src/csharp/experimental/restaurantbooking/cognitivemodels.json
  skills/src/csharp/experimental/weatherskill/Models/Accuweather/Timezone.cs
Labels: PR: reviewed-approved

#2066 Change sample from Skills to Virtual Assistant
  docs/tutorials/csharp/virtualassistant.md
Labels: PR: reviewed-approved

#2072 auth change 2
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/Mocks/MockServiceClientCredentials.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/Mocks/MockSkillWebSocketAdapter.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/Mocks/MockWhitelistAuthenticationProvider.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Auth/AuthHelpers.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Auth/IAuthenticationProvider.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Auth/IServiceClientCredentials.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Auth/IWhitelistAuthenticationProvider.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Auth/MsJWTAuthenticationProvider.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Models/SkillSettings.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialog.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketAdapter.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketRequestHandler.cs
Labels: PR: unreviewed

#2000 [TypeScript][BotBuilder Skills] Rename property msAppId to msaAppId
  lib/typescript/botbuilder-skills/src/models/skillManifest.ts
  lib/typescript/botbuilder-skills/src/skillManifestGenerator.ts
  lib/typescript/botbuilder-skills/src/websocket/skillWebSocketTransport.ts
  lib/typescript/botbuilder-skills/test/manifest.test.js
  lib/typescript/botbuilder-skills/test/mocks/fixtures/manifest_with_utterances.json
  lib/typescript/botbuilder-skills/test/mocks/fixtures/manifest_without_utterances.json
Labels: PR: reviewed-approved

#2033 [TypeScript][Generator] Add special character validation
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/index.js
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/index.js
Labels: Customer, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, supportability

#1983 [Botskills] Add msaAppId property to skillManifest model
  tools/botskills/src/models/skillManifest.ts
Labels: PR: reviewed-approved

#2049 [Android App] Update documentation with instructions on customizing Adaptive Card hostconfig.json
  solutions/android/VirtualAssistantClient/readme.md
Labels: PR: reviewed-approved

#2053 [HospitalitySkill] Fix reservation data issue and clean up files
  skills/src/csharp/experimental/hospitalityskill/Dialogs/CheckOutDialog.cs
  skills/src/csharp/experimental/hospitalityskill/Dialogs/ExtendStayDialog.cs
  skills/src/csharp/experimental/hospitalityskill/Dialogs/HospitalityDialogBase.cs
  skills/src/csharp/experimental/hospitalityskill/Dialogs/LateCheckOutDialog.cs
  skills/src/csharp/experimental/hospitalityskill/Dialogs/MainDialog.cs
  skills/src/csharp/experimental/hospitalityskill/Dialogs/RequestItemDialog.cs
  skills/src/csharp/experimental/hospitalityskill/Models/HospitalityUserSkillState.cs
  skills/src/csharp/experimental/hospitalityskill/Responses/CheckOut/CheckOutResponses.cs
  skills/src/csharp/experimental/hospitalityskill/Responses/CheckOut/CheckOutResponses.json
  skills/src/csharp/experimental/hospitalityskill/Responses/ExtendStay/ExtendStayResponses.cs
  skills/src/csharp/experimental/hospitalityskill/Responses/ExtendStay/ExtendStayResponses.json
  skills/src/csharp/experimental/hospitalityskill/Responses/LateCheckOut/LateCheckOutResponses.cs
  skills/src/csharp/experimental/hospitalityskill/Responses/LateCheckOut/LateCheckOutResponses.json
  skills/src/csharp/experimental/hospitalityskill/Services/GeneralLuis.cs
  skills/src/csharp/experimental/hospitalityskill/Services/HospitalityLuis.cs
  skills/src/csharp/experimental/hospitalityskill/Services/HotelService.cs
  skills/src/csharp/experimental/hospitalityskill/Services/IHotelService.cs
  skills/src/csharp/experimental/hospitalityskill/manifestTemplate.json
  skills/src/csharp/experimental/hospitalityskill/wwwroot/default.htm
Labels: PR: reviewed-approved

#2055 [HospitalitySample] Add KB for hotel FAQs and connect other skills
  solutions/HospitalitySample/Deployment/Resources/LU/en/General.lu
  solutions/HospitalitySample/Deployment/Resources/QnA/en/Chitchat.lu
  solutions/HospitalitySample/Deployment/Resources/QnA/en/Faq.lu
  solutions/HospitalitySample/Deployment/Resources/QnA/en/hotel_FAQ.lu
  solutions/HospitalitySample/Dialogs/MainDialog.cs
  solutions/HospitalitySample/Services/DispatchLuis.cs
  solutions/HospitalitySample/Services/GeneralLuis.cs
  solutions/HospitalitySample/skills.json
  solutions/HospitalitySample/wwwroot/default.htm
Labels: PR: reviewed-approved

#2065 update skill template
  templates/Skill-Template/csharp/Sample/SkillSample/Dialogs/SampleDialog.cs
  templates/Skill-Template/csharp/Sample/SkillSample/Dialogs/SkillDialogBase.cs
  templates/Skill-Template/csharp/Sample/SkillSample/Responses/Main/MainResponses.json
  templates/Skill-Template/csharp/Sample/SkillSample/Services/GeneralLuis.cs
  templates/Skill-Template/csharp/Sample/SkillSample/Services/SkillLuis.cs
  templates/Skill-Template/csharp/Template/Skill/Dialogs/SampleDialog.cs
  templates/Skill-Template/csharp/Template/Skill/Dialogs/SkillDialogBase.cs
  templates/Skill-Template/csharp/Template/Skill/Responses/Main/MainResponses.json
Labels: PR: unreviewed

#2025 [Calendar] Calendar bot with adaptive SDK (v4.6) - basic function Preview
  skills/src/csharp/Skills.sln
  skills/src/csharp/experimental/calendarskillpreview/AdapterWithErrorHandler.cs
  skills/src/csharp/experimental/calendarskillpreview/AdapterWithErrorHandler.lg
  skills/src/csharp/experimental/calendarskillpreview/Bots/DialogBot.cs
  skills/src/csharp/experimental/calendarskillpreview/CalendarSkillPreview.csproj
  skills/src/csharp/experimental/calendarskillpreview/ConfigurationCredentialProvider.cs
  skills/src/csharp/experimental/calendarskillpreview/Controllers/BotController.cs
  skills/src/csharp/experimental/calendarskillpreview/DialogExtensions.cs
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/AcceptCalendarEntry/AcceptCalendarEntry.cs
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/AcceptCalendarEntry/AcceptCalendarEntry.lg
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/AddContactDialog/AddContactDialog.cs
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/AddContactDialog/AddContactDialog.lg
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/ChangeCalendarEntry/ChangeCalendarEntry.cs
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/ChangeCalendarEntry/ChangeCalendarEntry.lg
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/CreateCalendarEntry/CreateCalendarEntry.cs
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/CreateCalendarEntry/CreateCalendarEntry.lg
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/DeleteCalendarEntry/DeleteCalendarEntry.cs
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/DeleteCalendarEntry/DeleteCalendarEntry.lg
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/FindCalendarEntry/FindCalendarEntry.cs
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/FindCalendarEntry/FindCalendarEntry.lg
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/FindCalendarWho/FindCalendarWho.cs
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/FindCalendarWho/FindCalendarWho.lg
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/OAuthPromptDialog.cs
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/RootDialog/RootDialog.cs
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/RootDialog/RootDialog.lg
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/RootDialog/RootDialog.lu
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/ShowAllMeetingDialog/ShowAllMeetingDialog.cs
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/ShowAllMeetingDialog/ShowAllMeetingDialog.lg
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/ShowNextCalendar/ShowNextCalendar.cs
  skills/src/csharp/experimental/calendarskillpreview/Dialogs/ShowNextCalendar/ShowNextCalendar.lg
  skills/src/csharp/experimental/calendarskillpreview/Program.cs
  skills/src/csharp/experimental/calendarskillpreview/Properties/launchSettings.json
  skills/src/csharp/experimental/calendarskillpreview/Startup.cs
  skills/src/csharp/experimental/calendarskillpreview/appsettings.json
  skills/src/csharp/experimental/calendarskillpreview/wwwroot/default.html
Labels: PR: reviewed-approved

#1971 [Skills& VA] Fallback rule support
  docs/howto/skills/bestpractices.md
  skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
  skills/src/csharp/calendarskill/calendarskill/Dialogs/MainDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/SummaryDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarSharedResponses.cs
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarSharedResponses.de.json
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarSharedResponses.es.json
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarSharedResponses.fr.json
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarSharedResponses.it.json
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarSharedResponses.json
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarSharedResponses.zh.json
  skills/src/csharp/calendarskill/calendarskill/Utilities/Actions.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/MainDialog.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/ShowEmailDialog.cs
  skills/src/csharp/emailskill/emailskill/EmailSkill.csproj
  skills/src/csharp/emailskill/emailskill/Responses/Shared/EmailSharedResponses.cs
  skills/src/csharp/emailskill/emailskill/Responses/Shared/EmailSharedResponses.de.json
  skills/src/csharp/emailskill/emailskill/Responses/Shared/EmailSharedResponses.es.json
  skills/src/csharp/emailskill/emailskill/Responses/Shared/EmailSharedResponses.fr.json
  skills/src/csharp/emailskill/emailskill/Responses/Shared/EmailSharedResponses.it.json
  skills/src/csharp/emailskill/emailskill/Responses/Shared/EmailSharedResponses.json
  skills/src/csharp/emailskill/emailskill/Responses/Shared/EmailSharedResponses.zh.json
  skills/src/csharp/emailskill/emailskill/Utilities/Actions.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Services/SkillIntentRecognizer.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
Labels: PR: unreviewed

#1991 POI improve language model (#1987)
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/de/secondary/poi_navigation_route_fromxtoy.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/en/secondary/poi_navigation_route_fromxtoy.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/es/secondary/poi_navigation_route_fromxtoy.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/fr/secondary/poi_navigation_route_fromxtoy.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/it/secondary/poi_navigation_route_fromxtoy.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/zh/secondary/poi_navigation_route_fromxtoy.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Services/AzureMapsGeoSpatialService.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskilltests/API/AzureMapsGeoSpatialServiceTests.cs
Labels: PR: unreviewed

#2063 Add GenericOauth2 to OAuthProvider (#2062)
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Authentication/OAuthProvider.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Authentication/OAuthProviderExtensions.cs
Labels: PR: reviewed-approved

#2086 add health check to SkillController
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/ManifestTests.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/Mocks/MockSkillController.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/Mocks/MockSkillWebSocketAdapter.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Auth/Authenticator.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Auth/IAuthenticator.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillController.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketAdapter.cs
Labels: PR: reviewed-approved

#2076 [Future to Next] Fallback skill & va change
  docs/howto/skills/bestpractices.md
  skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
  skills/src/csharp/calendarskill/calendarskill/Dialogs/MainDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/SummaryDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarSharedResponses.cs
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarSharedResponses.de.json
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarSharedResponses.es.json
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarSharedResponses.fr.json
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarSharedResponses.it.json
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarSharedResponses.json
  skills/src/csharp/calendarskill/calendarskill/Responses/Shared/CalendarSharedResponses.zh.json
  skills/src/csharp/calendarskill/calendarskill/Utilities/Actions.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/MainDialog.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/ShowEmailDialog.cs
  skills/src/csharp/emailskill/emailskill/EmailSkill.csproj
  skills/src/csharp/emailskill/emailskill/Responses/Shared/EmailSharedResponses.cs
  skills/src/csharp/emailskill/emailskill/Responses/Shared/EmailSharedResponses.de.json
  skills/src/csharp/emailskill/emailskill/Responses/Shared/EmailSharedResponses.es.json
  skills/src/csharp/emailskill/emailskill/Responses/Shared/EmailSharedResponses.fr.json
  skills/src/csharp/emailskill/emailskill/Responses/Shared/EmailSharedResponses.it.json
  skills/src/csharp/emailskill/emailskill/Responses/Shared/EmailSharedResponses.json
  skills/src/csharp/emailskill/emailskill/Responses/Shared/EmailSharedResponses.zh.json
  skills/src/csharp/emailskill/emailskill/Utilities/Actions.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Adapters/DefaultWebSocketAdapter.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Services/SkillIntentRecognizer.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
Labels: PR: reviewed-approved

#2089 [Skill & VA] Add nuget feed source
  skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
  skills/src/csharp/emailskill/emailskill/EmailSkill.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
Labels: PR: reviewed-approved

#2091 BingSearchSkill uses thumbnail in Teams
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Dialogs/SearchDialog.cs
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Models/SearchResultModel.cs
Labels: PR: reviewed-approved

#2100 change tabs to spaces so doc's markdown renders correctly
  docs/reference/skills/skillauthentication.md
Labels: PR: reviewed-approved

#2085 [TypeScript][BotBuilder Libs] Update SDK dependencies versions
  lib/typescript/botbuilder-skills/package.json
  lib/typescript/botbuilder-skills/src/models/skillManifest.ts
  lib/typescript/botbuilder-skills/src/skillManifestGenerator.ts
  lib/typescript/botbuilder-skills/src/websocket/skillWebSocketTransport.ts
  lib/typescript/botbuilder-skills/test/manifest.test.js
  lib/typescript/botbuilder-skills/test/mocks/fixtures/manifest_with_utterances.json
  lib/typescript/botbuilder-skills/test/mocks/fixtures/manifest_without_utterances.json
  lib/typescript/botbuilder-solutions/package.json
  lib/typescript/common/config/rush/npm-shrinkwrap.json
Labels: PR: reviewed-approved

#2097 [Skills] Localization issues for zh-cn
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Resources/LU/BingSearchSkill.lu
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Resources/LU/de/BingSearchSkill.lu
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Resources/LU/es/BingSearchSkill.lu
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Resources/LU/fr/BingSearchSkill.lu
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Resources/LU/it/BingSearchSkill.lu
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Resources/LU/zh/BingSearchSkill.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Content/PointOfInterestDetails.1.0.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Content/PointOfInterestDetails.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Models/PointofInterestModel.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/PointOfInterestSharedStrings.Designer.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/PointOfInterestSharedStrings.de.resx
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/PointOfInterestSharedStrings.es.resx
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/PointOfInterestSharedStrings.fr.resx
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/PointOfInterestSharedStrings.it.resx
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/PointOfInterestSharedStrings.resx
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Responses/Shared/PointOfInterestSharedStrings.zh.resx
  skills/src/csharp/todoskill/todoskill/Responses/AddToDo/AddToDoResponses.zh.json
  skills/src/csharp/todoskill/todoskill/Responses/DeleteToDo/DeleteToDoResponses.zh.json
  skills/src/csharp/todoskill/todoskill/Responses/Main/ToDoMainResponses.zh.json
  skills/src/csharp/todoskill/todoskill/Responses/MarkToDo/MarkToDoResponses.zh.json
  skills/src/csharp/todoskill/todoskill/Responses/Shared/ToDoSharedResponses.zh.json
  skills/src/csharp/todoskill/todoskill/Responses/Shared/ToDoStrings.zh.resx
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/Escalate/EscalateResponses.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/Escalate/EscalateStrings.Designer.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/Escalate/EscalateStrings.de.resx
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/Escalate/EscalateStrings.es.resx
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/Escalate/EscalateStrings.fr.resx
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/Escalate/EscalateStrings.it.resx
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/Escalate/EscalateStrings.resx
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/Escalate/EscalateStrings.zh.resx
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/Main/MainStrings.zh.resx
Labels: PR: reviewed-approved

#1982 [TypeScript][DevOps] Update deployment scripts and migrate new ARM templates
  README.md
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/parameters.template.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/template.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/deploy.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/luis_functions.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/publish.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/qna_functions.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/update_cognitive_models.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/appsettings.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/resources/parameters.template.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/resources/template.json
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/deploy.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/luis_functions.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/publish.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/update_cognitive_models.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/appsettings.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/parameters.template.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/template.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/deploy.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/luis_functions.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/publish.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/qna_functions.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/update_cognitive_models.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/appsettings.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/resources/parameters.template.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/resources/template.json
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/scripts/deploy.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/scripts/luis_functions.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/scripts/publish.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/scripts/update_cognitive_models.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/appsettings.json
Labels: PR: unreviewed

#2124 [Skills] Should use score threshold to filter general intent in OnInterruptDialogAsync
  skills/src/csharp/automotiveskill/automotiveskill/Dialogs/MainDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/MainDialog.cs
  skills/src/csharp/emailskill/emailskill/Dialogs/MainDialog.cs
  skills/src/csharp/experimental/newsskill/Dialogs/MainDialog.cs
  skills/src/csharp/experimental/restaurantbooking/Dialogs/MainDialog.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/MainDialog.cs
  skills/src/csharp/todoskill/todoskill/Dialogs/MainDialog.cs
Labels: PR: reviewed-approved

#2121 [Point of Interest] Update OpenDefaultApp event value with MapsUri property
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Models/OpenDefaultApp.cs
Labels: PR: reviewed-approved

#2147 add perf on SkillWebSocketTransport
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketTransport.cs
Labels: PR: reviewed-approved

#2143 [Calendar] calendar skill refactor part 1
  skills/src/csharp/calendarskill/calendarskill/Dialogs/CalendarSkillDialogBase.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/ChangeEventStatusDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/ConnectToMeetingDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/CreateEventDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/FindContactDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/MainDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/SummaryDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/TimeRemainingDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/UpdateEventDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Models/CalendarSkillDialogOptions.cs
  skills/src/csharp/calendarskill/calendarskill/Models/CalendarSkillState.cs
  skills/src/csharp/calendarskill/calendarskill/Models/DialogOptions/CalendarSkillDialogOptions.cs
  skills/src/csharp/calendarskill/calendarskill/Models/DialogOptions/ChangeEventStatusDialogOptions.cs
  skills/src/csharp/calendarskill/calendarskill/Models/DialogOptions/FindContactDialogOptions.cs
  skills/src/csharp/calendarskill/calendarskill/Models/DialogOptions/ShowMeetingsDialogOptions.cs
  skills/src/csharp/calendarskill/calendarskill/Models/DialogOptions/UpdateAddressDialogOptions.cs
  skills/src/csharp/calendarskill/calendarskill/Models/DialogOptions/UpdateDateTimeDialogOptions.cs
  skills/src/csharp/calendarskill/calendarskill/Models/DialogOptions/UpdateUserNameDialogOptions.cs
  skills/src/csharp/calendarskill/calendarskill/Prompts/GetEventPrompt.cs
  skills/src/csharp/calendarskill/calendarskilltest/Flow/CreateCalendarFlowTests.cs
Labels: PR: reviewed-approved

#2115 [POI] fix localization issue
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Content/PointOfInterestDetailsWithRoute.1.0.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Content/PointOfInterestDetailsWithRoute.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Resources/LU/zh/secondary/poi_navigation_route_fromxtoy.lu
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Models/PointofInterestModel.cs
  templates/Skill-Template/csharp/Sample/SkillSample/Dialogs/MainDialog.cs
  templates/Skill-Template/csharp/Template/Skill/Dialogs/MainDialog.cs
Labels: PR: reviewed-approved

#2133 Add experimental Music Skill
  skills/src/csharp/Skills.sln
  skills/src/csharp/experimental/musicskill/.filenesting.json
  skills/src/csharp/experimental/musicskill/Adapters/CustomSkillAdapter.cs
  skills/src/csharp/experimental/musicskill/Adapters/DefaultAdapter.cs
  skills/src/csharp/experimental/musicskill/Bots/DialogBot.cs
  skills/src/csharp/experimental/musicskill/Connected Services/Application Insights/ConnectedService.json
  skills/src/csharp/experimental/musicskill/Controllers/BotController.cs
  skills/src/csharp/experimental/musicskill/Deployment/Resources/LU/en/General.lu
  skills/src/csharp/experimental/musicskill/Deployment/Resources/LU/en/MusicSkill.lu
  skills/src/csharp/experimental/musicskill/Deployment/Resources/LU/zh/General.lu
  skills/src/csharp/experimental/musicskill/Deployment/Resources/LU/zh/MusicSkill.lu
  skills/src/csharp/experimental/musicskill/Deployment/Resources/parameters.template.json
  skills/src/csharp/experimental/musicskill/Deployment/Resources/template.json
  skills/src/csharp/experimental/musicskill/Deployment/Scripts/deploy.ps1
  skills/src/csharp/experimental/musicskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/musicskill/Deployment/Scripts/luis_functions.ps1
  skills/src/csharp/experimental/musicskill/Deployment/Scripts/publish.ps1
  skills/src/csharp/experimental/musicskill/Deployment/Scripts/qna_functions.ps1
  skills/src/csharp/experimental/musicskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/musicskill/Dialogs/MainDialog.cs
  skills/src/csharp/experimental/musicskill/Dialogs/PlayMusicDialog.cs
  skills/src/csharp/experimental/musicskill/Dialogs/SkillDialogBase.cs
  skills/src/csharp/experimental/musicskill/Models/OpenDefaultApp.cs
  skills/src/csharp/experimental/musicskill/Models/SkillState.cs
  skills/src/csharp/experimental/musicskill/MusicSkill.csproj
  skills/src/csharp/experimental/musicskill/Pipeline/MusicSkill.yml
  skills/src/csharp/experimental/musicskill/Program.cs
  skills/src/csharp/experimental/musicskill/Properties/launchSettings.json
  skills/src/csharp/experimental/musicskill/Responses/Main/MainResponses.cs
  skills/src/csharp/experimental/musicskill/Responses/Main/MainResponses.json
  skills/src/csharp/experimental/musicskill/Responses/Main/MainResponses.tt
  skills/src/csharp/experimental/musicskill/Responses/Main/MainResponses.zh.json
  skills/src/csharp/experimental/musicskill/Responses/Shared/ResponseIdCollection.t4
  skills/src/csharp/experimental/musicskill/Responses/Shared/SharedResponses.cs
  skills/src/csharp/experimental/musicskill/Responses/Shared/SharedResponses.json
  skills/src/csharp/experimental/musicskill/Responses/Shared/SharedResponses.tt
  skills/src/csharp/experimental/musicskill/Responses/Shared/SharedResponses.zh.json
  skills/src/csharp/experimental/musicskill/Services/BotServices.cs
  skills/src/csharp/experimental/musicskill/Services/BotSettings.cs
  skills/src/csharp/experimental/musicskill/Services/GeneralLuis.cs
  skills/src/csharp/experimental/musicskill/Services/MusicSkillLuis.cs
  skills/src/csharp/experimental/musicskill/Startup.cs
  skills/src/csharp/experimental/musicskill/appsettings.json
  skills/src/csharp/experimental/musicskill/cognitivemodels.json
  skills/src/csharp/experimental/musicskill/manifestTemplate.json
  skills/src/csharp/experimental/musicskill/readme.md
  skills/src/csharp/experimental/musicskill/wwwroot/default.htm
Labels: PR: reviewed-changes-requested

#2130 [TypeScript][Samples/Template] Add UTF8 default encoding for deployment scripts
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/deploy.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/publish.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/deploy.ps1
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/deploy.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/deploy_cognitive_models.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/publish.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/scripts/deploy.ps1
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
Labels: PR: reviewed-approved

#2134 fix test project
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/Microsoft.Bot.Builder.Skills.Tests.csproj
Labels: PR: reviewed-approved

#2146 Update experimental.md with music skill explanation
  docs/_docs/reference/skills/experimental.md
Labels: PR: reviewed-approved

#2111 [TypeScript][Generator] Update the replacement of template's files
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/index.js
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/src/copier.js
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/index.js
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/src/copier.js
Labels: PR: reviewed-approved

#2132 [HospitalitySkill] Add dialog for room service and update request item dialog
  skills/src/csharp/experimental/hospitalityskill/Content/FoodItemCard.json
  skills/src/csharp/experimental/hospitalityskill/Content/FoodOrderCard.json
  skills/src/csharp/experimental/hospitalityskill/Content/MenuCard.json
  skills/src/csharp/experimental/hospitalityskill/Content/MenuItemCard.json
  skills/src/csharp/experimental/hospitalityskill/Content/RequestItemCard.json
  skills/src/csharp/experimental/hospitalityskill/Content/RoomItemCard.json
  skills/src/csharp/experimental/hospitalityskill/Data/AvailableItems.json
  skills/src/csharp/experimental/hospitalityskill/Data/RoomServiceMenu.json
  skills/src/csharp/experimental/hospitalityskill/Deployment/Resources/LU/en/Hospitality.lu
  skills/src/csharp/experimental/hospitalityskill/Dialogs/MainDialog.cs
  skills/src/csharp/experimental/hospitalityskill/Dialogs/RequestItemDialog.cs
  skills/src/csharp/experimental/hospitalityskill/Dialogs/RoomServiceDialog.cs
  skills/src/csharp/experimental/hospitalityskill/HospitalitySkill.csproj
  skills/src/csharp/experimental/hospitalityskill/Models/HospitalitySkillState.cs
  skills/src/csharp/experimental/hospitalityskill/Models/RoomItem.cs
  skills/src/csharp/experimental/hospitalityskill/Models/RoomService/FoodOrderData.cs
  skills/src/csharp/experimental/hospitalityskill/Models/RoomService/Menu.cs
  skills/src/csharp/experimental/hospitalityskill/Models/RoomService/MenuItem.cs
  skills/src/csharp/experimental/hospitalityskill/Properties/launchSettings.json
  skills/src/csharp/experimental/hospitalityskill/Responses/RequestItem/RequestItemResponses.json
  skills/src/csharp/experimental/hospitalityskill/Responses/RoomService/RoomServiceResponses.cs
  skills/src/csharp/experimental/hospitalityskill/Responses/RoomService/RoomServiceResponses.json
  skills/src/csharp/experimental/hospitalityskill/Responses/RoomService/RoomServiceResponses.tt
  skills/src/csharp/experimental/hospitalityskill/Responses/Shared/HospitalityStrings.Designer.cs
  skills/src/csharp/experimental/hospitalityskill/Responses/Shared/HospitalityStrings.resx
  skills/src/csharp/experimental/hospitalityskill/Services/HospitalityLuis.cs
  skills/src/csharp/experimental/hospitalityskill/Services/HotelService.cs
  skills/src/csharp/experimental/hospitalityskill/Services/IHotelService.cs
  skills/src/csharp/experimental/hospitalityskill/Startup.cs
  skills/src/csharp/experimental/hospitalityskill/manifestTemplate.json
Labels: PR: reviewed-approved

#2138 Set CallerId in SkillWebSocketTransport
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialog.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketTransport.cs
Labels: PR: reviewed-approved

#2136 unify name of DialogState
  skills/src/csharp/automotiveskill/automotiveskill/Adapters/AutomotiveSkillWebSocketBotAdapter.cs
  skills/src/csharp/calendarskill/calendarskill/Adapters/CalendarSkillWebSocketBotAdapter.cs
  skills/src/csharp/emailskill/emailskill/Adapters/EmailSkillWebSocketBotAdapter.cs
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Adapters/CustomSkillAdapter.cs
  skills/src/csharp/experimental/hospitalityskill/Adapters/HospitalitySkillAdapter.cs
  skills/src/csharp/experimental/newsskill/Adapters/NewsSkillWebSocketBotAdapter.cs
  skills/src/csharp/experimental/restaurantbooking/Adapters/RestaurantSkillWebSocketBotAdapter.cs
  skills/src/csharp/experimental/weatherskill/Adapters/CustomSkillAdapter.cs
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Adapters/POISkillWebSocketBotAdapter.cs
  skills/src/csharp/todoskill/todoskill/Adapters/ToDoSkillWebSocketBotAdapter.cs
Labels: PR: reviewed-approved

#2149 Experimental skill fixes
  skills/src/csharp/experimental/newsskill/manifestTemplate.json
  skills/src/csharp/experimental/restaurantbooking/Dialogs/BookingDialog.cs
  skills/src/csharp/experimental/restaurantbooking/Dialogs/MainDialog.cs
  skills/src/csharp/experimental/restaurantbooking/Dialogs/SkillDialogBase.cs
  skills/src/csharp/experimental/weatherskill/Deployment/Resources/LU/en/WeatherSkill.lu
  skills/src/csharp/experimental/weatherskill/manifestTemplate.json
Labels: PR: reviewed-approved

#2154 fix speech auth
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialog.cs
Labels: PR: reviewed-approved

#2150 remove event triggering for action from documentation
  docs/_docs/reference/skills/skillmanifest.md
Labels: PR: reviewed-approved

#2123 [Libs] LG support for Email/Calendar/Todo/POI skill libs part
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/Microsoft.Bot.Builder.Skills.Tests.csproj
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/SkillDialogTestBase.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Microsoft.Bot.Builder.Skills.csproj
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Microsoft.Bot.Builder.Solutions.csproj
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Testing/DefaultTestAdapter.cs
Labels: PR: reviewed-approved

#2156 Initial version of event companion app
  solutions/android/EventCompanion/.gitignore
  solutions/android/EventCompanion/app/.gitignore
  solutions/android/EventCompanion/app/build.gradle
  solutions/android/EventCompanion/app/proguard-rules.pro
  solutions/android/EventCompanion/app/src/main/AndroidManifest.xml
  solutions/android/EventCompanion/app/src/main/assets/icons/defrost.png
  solutions/android/EventCompanion/app/src/main/assets/icons/seat_heater.png
  solutions/android/EventCompanion/app/src/main/assets/templates/numeric/Temperature.json
  solutions/android/EventCompanion/app/src/main/assets/templates/toggle/MaxDefrost.json
  solutions/android/EventCompanion/app/src/main/assets/templates/toggle/SeatHeater.json
  solutions/android/EventCompanion/app/src/main/java/com/microsoft/bot/builder/solutions/eventcompanion/EventReceiver.kt
  solutions/android/EventCompanion/app/src/main/java/com/microsoft/bot/builder/solutions/eventcompanion/MainActivity.kt
  solutions/android/EventCompanion/app/src/main/java/com/microsoft/bot/builder/solutions/eventcompanion/MainApplication.kt
  solutions/android/EventCompanion/app/src/main/java/com/microsoft/bot/builder/solutions/eventcompanion/MySpinner.kt
  solutions/android/EventCompanion/app/src/main/java/com/microsoft/bot/builder/solutions/eventcompanion/NumericWidget.kt
  solutions/android/EventCompanion/app/src/main/java/com/microsoft/bot/builder/solutions/eventcompanion/NumericWidgetConfigureActivity.kt
  solutions/android/EventCompanion/app/src/main/java/com/microsoft/bot/builder/solutions/eventcompanion/ToggleWidget.kt
  solutions/android/EventCompanion/app/src/main/java/com/microsoft/bot/builder/solutions/eventcompanion/ToggleWidgetConfigureActivity.kt
  solutions/android/EventCompanion/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  solutions/android/EventCompanion/app/src/main/res/drawable/ic_launcher_background.xml
  solutions/android/EventCompanion/app/src/main/res/drawable/ripple.xml
  solutions/android/EventCompanion/app/src/main/res/drawable/shape_rect_round_corners.xml
  solutions/android/EventCompanion/app/src/main/res/drawable/shape_rect_round_corners_dark.xml
  solutions/android/EventCompanion/app/src/main/res/drawable/shape_rect_round_corners_light_gray.xml
  solutions/android/EventCompanion/app/src/main/res/drawable/shape_rect_round_corners_suggested_action.xml
  solutions/android/EventCompanion/app/src/main/res/drawable/widget_preview_numberic.png
  solutions/android/EventCompanion/app/src/main/res/drawable/widget_preview_toggle.png
  solutions/android/EventCompanion/app/src/main/res/layout/activity_main.xml
  solutions/android/EventCompanion/app/src/main/res/layout/numeric_widget.xml
  solutions/android/EventCompanion/app/src/main/res/layout/numeric_widget_configure.xml
  solutions/android/EventCompanion/app/src/main/res/layout/numeric_widget_value_range_item.xml
  solutions/android/EventCompanion/app/src/main/res/layout/toggle_widget.xml
  solutions/android/EventCompanion/app/src/main/res/layout/toggle_widget_configure.xml
  solutions/android/EventCompanion/app/src/main/res/layout/widget_list_item.xml
  solutions/android/EventCompanion/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  solutions/android/EventCompanion/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  solutions/android/EventCompanion/app/src/main/res/mipmap-hdpi/ic_launcher.png
  solutions/android/EventCompanion/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  solutions/android/EventCompanion/app/src/main/res/mipmap-mdpi/ic_launcher.png
  solutions/android/EventCompanion/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  solutions/android/EventCompanion/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  solutions/android/EventCompanion/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  solutions/android/EventCompanion/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  solutions/android/EventCompanion/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  solutions/android/EventCompanion/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  solutions/android/EventCompanion/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  solutions/android/EventCompanion/app/src/main/res/values-v14/dimens.xml
  solutions/android/EventCompanion/app/src/main/res/values/colors.xml
  solutions/android/EventCompanion/app/src/main/res/values/dimens.xml
  solutions/android/EventCompanion/app/src/main/res/values/strings.xml
  solutions/android/EventCompanion/app/src/main/res/values/styles.xml
  solutions/android/EventCompanion/app/src/main/res/xml/numeric_widget_info.xml
  solutions/android/EventCompanion/app/src/main/res/xml/toggle_widget_info.xml
  solutions/android/EventCompanion/build.gradle
  solutions/android/EventCompanion/gradle.properties
  solutions/android/EventCompanion/gradle/wrapper/gradle-wrapper.properties
  solutions/android/EventCompanion/gradlew
  solutions/android/EventCompanion/gradlew.bat
  solutions/android/EventCompanion/settings.gradle
Labels: PR: reviewed-approved

#2159 [Weather Skill] Localization issues for zh-cn
  skills/src/csharp/experimental/weatherskill/Deployment/Resources/LU/de/WeatherSkill.lu
  skills/src/csharp/experimental/weatherskill/Deployment/Resources/LU/es/WeatherSkill.lu
  skills/src/csharp/experimental/weatherskill/Deployment/Resources/LU/fr/WeatherSkill.lu
  skills/src/csharp/experimental/weatherskill/Deployment/Resources/LU/it/WeatherSkill.lu
  skills/src/csharp/experimental/weatherskill/Deployment/Resources/LU/zh/WeatherSkill.lu
  skills/src/csharp/experimental/weatherskill/Responses/Main/MainResponses.de.json
  skills/src/csharp/experimental/weatherskill/Responses/Main/MainResponses.es.json
  skills/src/csharp/experimental/weatherskill/Responses/Main/MainResponses.fr.json
  skills/src/csharp/experimental/weatherskill/Responses/Main/MainResponses.it.json
  skills/src/csharp/experimental/weatherskill/Responses/Main/MainResponses.zh.json
Labels: PR: unreviewed

#2170 [Restaurant Booking Skill] Fix localization issue
  skills/src/csharp/experimental/restaurantbooking/Deployment/Resources/LU/de/General.lu
  skills/src/csharp/experimental/restaurantbooking/Deployment/Resources/LU/de/Restaurant.lu
  skills/src/csharp/experimental/restaurantbooking/Deployment/Resources/LU/es/General.lu
  skills/src/csharp/experimental/restaurantbooking/Deployment/Resources/LU/es/Restaurant.lu
  skills/src/csharp/experimental/restaurantbooking/Deployment/Resources/LU/fr/General.lu
  skills/src/csharp/experimental/restaurantbooking/Deployment/Resources/LU/fr/Restaurant.lu
  skills/src/csharp/experimental/restaurantbooking/Deployment/Resources/LU/it/General.lu
  skills/src/csharp/experimental/restaurantbooking/Deployment/Resources/LU/it/Restaurant.lu
  skills/src/csharp/experimental/restaurantbooking/Deployment/Resources/LU/zh/General.lu
  skills/src/csharp/experimental/restaurantbooking/Deployment/Resources/LU/zh/Restaurant.lu
  skills/src/csharp/experimental/restaurantbooking/Responses/Main/RestaurantBookingMainResponses.de.json
  skills/src/csharp/experimental/restaurantbooking/Responses/Main/RestaurantBookingMainResponses.es.json
  skills/src/csharp/experimental/restaurantbooking/Responses/Main/RestaurantBookingMainResponses.fr.json
  skills/src/csharp/experimental/restaurantbooking/Responses/Main/RestaurantBookingMainResponses.it.json
  skills/src/csharp/experimental/restaurantbooking/Responses/Main/RestaurantBookingMainResponses.zh.json
  skills/src/csharp/experimental/restaurantbooking/Responses/Shared/RestaurantBookingSharedResponses.de.json
  skills/src/csharp/experimental/restaurantbooking/Responses/Shared/RestaurantBookingSharedResponses.es.json
  skills/src/csharp/experimental/restaurantbooking/Responses/Shared/RestaurantBookingSharedResponses.fr.json
  skills/src/csharp/experimental/restaurantbooking/Responses/Shared/RestaurantBookingSharedResponses.it.json
  skills/src/csharp/experimental/restaurantbooking/Responses/Shared/RestaurantBookingSharedResponses.zh.json
  skills/src/csharp/experimental/restaurantbooking/RestaurantBooking.csproj
Labels: PR: reviewed-approved

#2164 use hashset for whitelist
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills.Tests/Mocks/MockWhitelistAuthenticationProvider.cs
  lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Auth/IWhitelistAuthenticationProvider.cs
Labels: PR: reviewed-approved

#2179 Work in progress
  docs/media/android_project_overview.jpg
  solutions/android/VirtualAssistantClient/app/build.gradle
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/BaseActivity.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/MainActivity.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/SfxManager.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/chatlist/SvgImageLoader.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/chatlist/ViewholderBot.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/customview/SquareRelativeLayout.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/service/SpeechService.java
  solutions/android/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/utils/PlayStoreUtils.java
  solutions/android/VirtualAssistantClient/app/src/main/res/drawable-anydpi/ic_keyboard.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/drawable-hdpi/ic_keyboard.png
  solutions/android/VirtualAssistantClient/app/src/main/res/drawable-mdpi/ic_keyboard.png
  solutions/android/VirtualAssistantClient/app/src/main/res/drawable-xhdpi/ic_keyboard.png
  solutions/android/VirtualAssistantClient/app/src/main/res/drawable-xxhdpi/ic_keyboard.png
  solutions/android/VirtualAssistantClient/app/src/main/res/drawable/shape_rect_round_corners_dark.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/layout-land/activity_main.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/layout-port/activity_settings.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/layout/activity_main.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/layout/item_suggested_action.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/values-night/styles.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/values/colors.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/values/strings.xml
  solutions/android/VirtualAssistantClient/app/src/main/res/values/styles.xml
  solutions/android/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/SpeechSdk.java
  solutions/android/VirtualAssistantClient/directlinespeech/src/main/java/events/BotListening.java
  solutions/android/VirtualAssistantClient/readme.md
Labels: PR: reviewed-approved

#2246 Update cognitivemodels.json for Event Skill
  skills/src/csharp/experimental/eventskill/cognitivemodels.json
Labels: PR: reviewed-approved

#2247 Update cognitivemodels.json for hospitality skill
  skills/src/csharp/experimental/hospitalityskill/cognitivemodels.json
Labels: PR: reviewed-approved

#2188 [TypeScript][Skill Sample] Solve merge conflicts
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/deployment/scripts/deploy.ps1
Labels: PR: reviewed-approved

#2141 [Script] cognitive model args should be camelCased
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/automotiveskill/automotiveskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/calendarskill/calendarskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/calendarskill/calendarskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/emailskill/emailskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/bingsearchskill/bingsearchskill/cognitivemodels.json
  skills/src/csharp/experimental/hospitalityskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/hospitalityskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/newsskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/restaurantbooking/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/experimental/weatherskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/experimental/weatherskill/cognitivemodels.json
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/pointofinterestskill/pointofinterestskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/deploy_cognitive_models.ps1
  skills/src/csharp/todoskill/todoskill/Deployment/Scripts/update_cognitive_models.ps1
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/update_cognitive_models.ps1
  templates/Skill-Template/csharp/Sample/SkillSample/cognitivemodels.json
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/update_cognitive_models.ps1
  templates/Skill-Template/csharp/Template/Skill/cognitivemodels.json
Labels: PR: reviewed-approved

#2168 update template for naming and DialogState
  skills/src/csharp/experimental/musicskill/Adapters/CustomSkillAdapter.cs
  templates/Skill-Template/csharp/Sample/SkillSample.Tests/SkillTestBase.cs
  templates/Skill-Template/csharp/Sample/SkillSample/Adapters/CustomSkillAdapter.cs
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Resources/LU/de/General.lu
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Resources/LU/de/Skill.lu
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Resources/LU/en/General.lu
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Resources/LU/en/Skill.lu
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Resources/LU/es/General.lu
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Resources/LU/es/Skill.lu
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Resources/LU/fr/General.lu
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Resources/LU/fr/Skill.lu
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Resources/LU/it/General.lu
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Resources/LU/it/Skill.lu
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Resources/LU/zh/General.lu
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Resources/LU/zh/Skill.lu
  templates/Skill-Template/csharp/Sample/SkillSample/Dialogs/MainDialog.cs
  templates/Skill-Template/csharp/Sample/SkillSample/Dialogs/SkillDialogBase.cs
  templates/Skill-Template/csharp/Sample/SkillSample/cognitivemodels.json
  templates/Skill-Template/csharp/Template/Skill/Adapters/CustomSkillAdapter.cs
  templates/Skill-Template/csharp/Template/Skill/Deployment/Resources/LU/de/General.lu
  templates/Skill-Template/csharp/Template/Skill/Deployment/Resources/LU/de/Skill.lu
  templates/Skill-Template/csharp/Template/Skill/Deployment/Resources/LU/en/General.lu
  templates/Skill-Template/csharp/Template/Skill/Deployment/Resources/LU/en/Skill.lu
  templates/Skill-Template/csharp/Template/Skill/Deployment/Resources/LU/es/General.lu
  templates/Skill-Template/csharp/Template/Skill/Deployment/Resources/LU/es/Skill.lu
  templates/Skill-Template/csharp/Template/Skill/Deployment/Resources/LU/fr/General.lu
  templates/Skill-Template/csharp/Template/Skill/Deployment/Resources/LU/fr/Skill.lu
  templates/Skill-Template/csharp/Template/Skill/Deployment/Resources/LU/it/General.lu
  templates/Skill-Template/csharp/Template/Skill/Deployment/Resources/LU/it/Skill.lu
  templates/Skill-Template/csharp/Template/Skill/Deployment/Resources/LU/zh/General.lu
  templates/Skill-Template/csharp/Template/Skill/Deployment/Resources/LU/zh/Skill.lu
  templates/Skill-Template/csharp/Template/Skill/cognitivemodels.json
Labels: PR: reviewed-approved

#2201 [Calendar] fix calendar timezone issue
  skills/src/csharp/calendarskill/calendarskill/Dialogs/CalendarSkillDialogBase.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/ConnectToMeetingDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/CreateEventDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/SummaryDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Dialogs/UpdateEventDialog.cs
  skills/src/csharp/calendarskill/calendarskill/Prompts/DatePrompt.cs
  skills/src/csharp/calendarskill/calendarskill/Prompts/GetEventPrompt.cs
  skills/src/csharp/calendarskill/calendarskill/Prompts/Options/DatePromptOptions.cs
  skills/src/csharp/calendarskill/calendarskill/Prompts/Options/NoSkipPromptOptions.cs
  skills/src/csharp/calendarskill/calendarskill/Prompts/Options/TimePromptOptions.cs
  skills/src/csharp/calendarskill/calendarskill/Prompts/TimePrompt.cs
  skills/src/csharp/calendarskill/calendarskilltest/Prompt/DatePromptTests.cs
Labels: PR: reviewed-approved

#2226 Add FeedbackMiddleware to Solutions lib
  docs/_docs/howto/virtual-assistant/feedback.md
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Feedback/FeedbackMiddleware.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Feedback/FeedbackOptions.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Feedback/FeedbackRecord.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Feedback/FeedbackResponses.Designer.cs
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Feedback/FeedbackResponses.de.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Feedback/FeedbackResponses.es.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Feedback/FeedbackResponses.fr.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Feedback/FeedbackResponses.it.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Feedback/FeedbackResponses.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Feedback/FeedbackResponses.zh.resx
  lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Microsoft.Bot.Builder.Solutions.csproj
  solutions/analytics/ConversationalAnalyticsSample_4_6_1.pbit
Labels: PR: reviewed-approved

#2210 [C#][DevOps] Spike for CD in Virtual Assistant Sample
  docs/_docs/howto/virtual-assistant/continuousdeployment.md
  docs/assets/images/configure_release_pipeline_1.png
  docs/assets/images/configure_release_pipeline_2.png
  docs/assets/images/configure_release_pipeline_3.png
  docs/assets/images/configure_release_pipeline_4.png
  docs/assets/images/configure_release_pipeline_5.png
  docs/assets/images/configure_release_pipeline_6.png
  docs/assets/images/create_release_pipeline_1.png
  docs/assets/images/create_release_pipeline_2.png
  docs/assets/images/create_release_pipeline_3.png
  docs/assets/images/create_release_pipeline_4.png
  docs/assets/images/create_release_pipeline_5.png
  docs/assets/images/create_release_pipeline_6.png
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Pipeline/VirtualAssistantSample.yml
  templates/Virtual-Assistant-Template/csharp/Template/VA/Pipeline/VirtualAssistantTemplate.yml
  yaml/csharp/virtual-assistant-sample.yml
Labels: PR: reviewed-approved

#2253 [TypeScript][BotBuilder-Skills] Use Handoff Activity to manage the signal completion of skill dialog
  lib/typescript/botbuilder-skills/src/skillCallingRequestHandler.ts
  lib/typescript/botbuilder-skills/src/skillDialog.ts
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/dialogs/_mainDialog.ts
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/dialogs/mainDialog.ts
Labels: PR: unreviewed

#2258 [Docs] Enterprise Notifications & Virtual Assistant Client (Android)
  docs/_data/toc.yml
  docs/_docs/howto/samples/enterprisenotifications.md
  docs/_docs/howto/samples/vaclient_android.md
  docs/_docs/overview/samples/enterprisenotifications.md
  docs/_docs/reference/samples/vaclient_android.md
  docs/_docs/tutorials/enable-speech/2_create_speech_instance.md
  docs/_docs/tutorials/enable-speech/3_add_speech_channel.md
  docs/assets/images/android_project_overview.jpg
  docs/assets/images/enterprisenotifications-architecture.png
  docs/assets/images/virtualassistantclient-android-fullconversationview.png
  docs/assets/images/virtualassistantclient-android-overview.png
  docs/assets/images/virtualassistantclient-android-widgetview.png
Labels: PR: reviewed-approved

#2257 handoff skilltemplate
  templates/Skill-Template/csharp/Sample/SkillSample/Dialogs/MainDialog.cs
  templates/Skill-Template/csharp/Template/Skill/Dialogs/MainDialog.cs
Labels: PR: reviewed-approved
