Repository microsoft/botframework-solutions, pull requests merged in 2019-11, with the labels that each got.

#2609 [Calendar] update wording
  skills/csharp/calendarskill/Dialogs/ChangeEventStatusDialog.cs
  skills/csharp/calendarskill/Responses/ChangeEventStatus/ChangeEventStatusResponses.de.json
  skills/csharp/calendarskill/Responses/ChangeEventStatus/ChangeEventStatusResponses.es.json
  skills/csharp/calendarskill/Responses/ChangeEventStatus/ChangeEventStatusResponses.fr.json
  skills/csharp/calendarskill/Responses/ChangeEventStatus/ChangeEventStatusResponses.it.json
  skills/csharp/calendarskill/Responses/ChangeEventStatus/ChangeEventStatusResponses.json
  skills/csharp/calendarskill/Responses/ChangeEventStatus/ChangeEventStatusResponses.zh.json
Labels: PR: reviewed-approved

#2637 Broke Apart Experimental Skills and Updated What's New and Virtual As…
  docs/_docs/overview/virtual-assistant-skills-pattern.md
  docs/_docs/overview/virtual-assistant-solution.md
  docs/_docs/overview/whats-new.md
  docs/_docs/skills/samples/automotive.md
  docs/_docs/skills/samples/bing-search.md
  docs/_docs/skills/samples/event.md
  docs/_docs/skills/samples/experimental.md
  docs/_docs/skills/samples/hospitality.md
  docs/_docs/skills/samples/itsm.md
  docs/_docs/skills/samples/music.md
  docs/_docs/skills/samples/news.md
  docs/_docs/skills/samples/phone.md
  docs/_docs/skills/samples/restaurant-booking.md
  docs/_docs/skills/samples/weather.md
Labels: PR: reviewed-approved

#2638 Completed Link check for Clients and Channels section.
  docs/_docs/clients-and-channels/clients/event-companion.md
  docs/_docs/clients-and-channels/clients/virtual-assistant-client.md
  docs/_docs/clients-and-channels/tutorials/enable-speech/1-intro.md
  docs/_docs/clients-and-channels/tutorials/enable-teams/1-intro.md
  docs/_docs/skills/samples/automotive.md
  docs/_docs/skills/samples/experimental.md
  docs/_docs/skills/tutorials/create-skill/csharp/1-intro.md
  docs/_docs/solution-accelerators/assistants/hospitality-assistant.md
  docs/_docs/solution-accelerators/tutorials/view-analytics/1-intro.md
  docs/_docs/solution-accelerators/tutorials/view-analytics/2-get-application-insights-application-id.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/csharp/1-intro.md
Labels: PR: reviewed-approved

#2634 [Skill Template] Remove extra luis call
  templates/Skill-Template/csharp/Sample/SkillSample/Dialogs/MainDialog.cs
Labels: PR: reviewed-approved

#2628 [ToDo & Weather] Update transcripts
  docs/assets/transcripts/skills-todo.transcript
  docs/assets/transcripts/skills-weather.transcript
Labels: PR: reviewed-approved

#2607 [Android] Button to reinitialize speech service
  samples/android/clients/VirtualAssistantClient/app/build.gradle
  samples/android/clients/VirtualAssistantClient/app/src/main/aidl/com/microsoft/bot/builder/solutions/virtualassistant/ISpeechService.aidl
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/MainActivity.java
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/settings/SettingsActivity.java
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/service/ServiceBinder.java
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/service/SpeechService.java
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/SpeechSdk.java
Labels: PR: reviewed-approved

#2636 Fix broken tests, and update to 4.6.1
  sdk/csharp/libraries/microsoft.bot.builder.solutions.skills/Microsoft.Bot.Builder.Solutions.Skills.csproj
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Microsoft.Bot.Builder.Solutions.csproj
  skills/csharp/Directory.Build.props
  skills/csharp/calendarskill/CalendarSkill.csproj
  skills/csharp/calendarskill/Dialogs/MainDialog.cs
  skills/csharp/emailskill/EmailSkill.csproj
  skills/csharp/experimental/automotiveskill/AutomotiveSkill.csproj
  skills/csharp/experimental/bingsearchskill/BingSearchSkill.csproj
  skills/csharp/experimental/eventskill/EventSkill.csproj
  skills/csharp/experimental/hospitalityskill/HospitalitySkill.csproj
  skills/csharp/experimental/itsmskill/ITSMSkill.csproj
  skills/csharp/experimental/musicskill/MusicSkill.csproj
  skills/csharp/experimental/newsskill/NewsSkill.csproj
  skills/csharp/experimental/phoneskill/PhoneSkill.csproj
  skills/csharp/experimental/restaurantbookingskill/RestaurantBookingSkill.csproj
  skills/csharp/experimental/weatherskill/WeatherSkill.csproj
  skills/csharp/pointofinterestskill/PointOfInterestSkill.csproj
  skills/csharp/tests/calendarskill.tests/Flow/CalendarSkillTestBase.cs
  skills/csharp/tests/calendarskill.tests/Flow/ChangeCalendarStatusFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/ConnectToMeetingFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/CreateCalendarFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/NextCalendarFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/SummaryCalendarFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/TimeRemainingFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/UpdateCalendarFlowTests.cs
  skills/csharp/tests/emailskill.tests/Flow/DeleteEmailFlowTests.cs
  skills/csharp/tests/emailskill.tests/Flow/EmailSkillTestBase.cs
  skills/csharp/tests/emailskill.tests/Flow/ForwardEmailFlowTests.cs
  skills/csharp/tests/emailskill.tests/Flow/ReplyFlowTests.cs
  skills/csharp/tests/emailskill.tests/Flow/SendEmailFlowTests.cs
  skills/csharp/tests/emailskill.tests/Flow/ShowEmailFlowTests.cs
  skills/csharp/tests/phoneskill.tests/Flow/InterruptionTests.cs
  skills/csharp/tests/phoneskill.tests/Flow/OutgoingCallDialogTests.cs
  skills/csharp/tests/phoneskill.tests/Flow/PhoneSkillTestBase.cs
  skills/csharp/tests/todoskill.tests/API/OutlookServiceTests.cs
  skills/csharp/tests/todoskill.tests/Flow/AddToDoFlowTests.cs
  skills/csharp/tests/todoskill.tests/Flow/DeleteAllToDosFlowTests.cs
  skills/csharp/tests/todoskill.tests/Flow/DeleteToDoFlowTests.cs
  skills/csharp/tests/todoskill.tests/Flow/MarkAllToDosFlowTests.cs
  skills/csharp/tests/todoskill.tests/Flow/MarkToDoFlowTests.cs
  skills/csharp/tests/todoskill.tests/Flow/ShowToDoFlowTests.cs
  skills/csharp/tests/todoskill.tests/Flow/ToDoSkillTestBase.cs
  skills/csharp/tests/todoskill.tests/ToDoSkill.Tests.csproj
  skills/csharp/todoskill/ToDoSkill.csproj
  templates/Skill-Template/csharp/Sample/SkillSample.Tests/SkillSample.Tests.csproj
  templates/Skill-Template/csharp/Sample/SkillSample/SkillSample.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
Labels: PR: reviewed-approved

#2416 Fix null reference exception in ScheduledTask.AddScheduledTask
  sdk/csharp/libraries/microsoft.bot.builder.solutions/TaskExtensions/ScheduledProcessor.cs
Labels: PR: reviewed-approved

#2629 [ToDo]Fix todo test
  skills/csharp/tests/todoskill.tests/API/Fakes/MockAppSettings.json
  skills/csharp/tests/todoskill.tests/API/Fakes/MockConfiguration.cs
  skills/csharp/tests/todoskill.tests/API/OutlookServiceTests.cs
  skills/csharp/todoskill/Services/ServiceHelper.cs
Labels: PR: merged

#2641 Enterprise VA Sample with proactive notifications and multi-turn QnA
  docs/_docs/solution-accelerators/tutorials/enable-proactive-notifications/4-virtual-assistant.md
  samples/csharp/assistants/enterprise-assistant/EnterpriseAssistant.sln
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Adapters/DefaultWebSocketAdapter.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Bots/DefaultActivityHandler.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Controllers/BotController.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Dialogs/OnboardingDialog.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Dialogs/QnADialog.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Models/EventData.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Models/UserProfileState.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/MainResponses.de-de.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/MainResponses.es-es.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/MainResponses.fr-fr.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/MainResponses.it-it.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/MainResponses.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/MainResponses.zh-cn.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/OnboardingResponses.de-de.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/OnboardingResponses.de.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/OnboardingResponses.es-es.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/OnboardingResponses.es.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/OnboardingResponses.fr-fr.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/OnboardingResponses.fr.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/OnboardingResponses.it-it.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/OnboardingResponses.it.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/OnboardingResponses.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/OnboardingResponses.zh-cn.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/OnboardingResponses.zh.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Services/BotSettings.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Services/DispatchLuis.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Services/GeneralLuis.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Startup.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/readme.md
  samples/csharp/clients/Clients.sln
  samples/csharp/clients/event-handler.function-app/EventHandler.csproj
  samples/csharp/clients/event-handler.function-app/Function1.cs
  samples/csharp/clients/event-producer.event-hub/Program.cs
Labels: PR: unreviewed

#2658 [Botskills] Display a warning when the tool found an unrecognized scope
  tools/botskills/src/utils/authenticationUtils.ts
Labels: PR: reviewed-approved

#2653 [Hospitality Skill] Add multi language lu files
  skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/de/General.lu
  skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/de/Hospitality.lu
  skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/es/General.lu
  skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/es/Hospitality.lu
  skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/fr/General.lu
  skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/fr/Hospitality.lu
  skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/it/General.lu
  skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/it/Hospitality.lu
  skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/zh/General.lu
  skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/zh/Hospitality.lu
Labels: PR: reviewed-approved

#2633 [Email] update to activity handler
  skills/csharp/emailskill/Adapters/DefaultAdapter.cs
  skills/csharp/emailskill/Adapters/EmailSkillWebSocketBotAdapter.cs
  skills/csharp/emailskill/Bots/DefaultActivityHandler.cs
  skills/csharp/emailskill/Bots/DialogBot.cs
  skills/csharp/emailskill/Controllers/BotController.cs
  skills/csharp/emailskill/Dialogs/DeleteEmailDialog.cs
  skills/csharp/emailskill/Dialogs/EmailSkillDialogBase.cs
  skills/csharp/emailskill/Dialogs/FindContactDialog.cs
  skills/csharp/emailskill/Dialogs/ForwardEmailDialog.cs
  skills/csharp/emailskill/Dialogs/MainDialog.cs
  skills/csharp/emailskill/Dialogs/ReplyEmailDialog.cs
  skills/csharp/emailskill/Dialogs/SendEmailDialog.cs
  skills/csharp/emailskill/Dialogs/ShowEmailDialog.cs
  skills/csharp/emailskill/EmailSkill.csproj
  skills/csharp/emailskill/Models/EmailSkillState.cs
  skills/csharp/emailskill/Models/StateProperties.cs
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.de.json
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.es.json
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.fr.json
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.it.json
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.json
  skills/csharp/emailskill/Responses/Shared/EmailSharedResponses.zh.json
  skills/csharp/emailskill/Services/BotSettings.cs
  skills/csharp/emailskill/Services/GoogleAPI/GoogleClient.cs
  skills/csharp/emailskill/Services/MSGraphAPI/GraphClient.cs
  skills/csharp/emailskill/Startup.cs
  skills/csharp/tests/emailskill.tests/Flow/EmailSkillTestBase.cs
  skills/csharp/tests/emailskill.tests/Flow/Fakes/MockEmailLuisRecognizer.cs
  skills/csharp/tests/emailskill.tests/Flow/Fakes/MockGeneralLuisRecognizer.cs
  skills/csharp/tests/emailskill.tests/Flow/ReplyFlowTests.cs
  skills/csharp/tests/emailskill.tests/Flow/SendEmailFlowTests.cs
  skills/csharp/tests/emailskill.tests/Flow/ShowEmailFlowTests.cs
Labels: PR: reviewed-approved

#2647 [Skills] use DefaultActivityHandler
  skills/csharp/experimental/eventskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/eventskill/Adapters/EventSkillAdapter.cs
  skills/csharp/experimental/eventskill/Bots/DefaultActivityHandler.cs
  skills/csharp/experimental/eventskill/Bots/DialogBot.cs
  skills/csharp/experimental/eventskill/Dialogs/MainDialog.cs
  skills/csharp/experimental/eventskill/EventSkill.csproj
  skills/csharp/experimental/eventskill/Services/BotSettings.cs
  skills/csharp/experimental/eventskill/Services/EventbriteService.cs
  skills/csharp/experimental/eventskill/Startup.cs
  skills/csharp/experimental/hospitalityskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/hospitalityskill/Adapters/HospitalitySkillAdapter.cs
  skills/csharp/experimental/hospitalityskill/Bots/DefaultActivityHandler.cs
  skills/csharp/experimental/hospitalityskill/Bots/DialogBot.cs
  skills/csharp/experimental/hospitalityskill/Dialogs/MainDialog.cs
  skills/csharp/experimental/hospitalityskill/HospitalitySkill.csproj
  skills/csharp/experimental/hospitalityskill/Startup.cs
  skills/csharp/experimental/itsmskill/Adapters/CustomSkillAdapter.cs
  skills/csharp/experimental/itsmskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/itsmskill/Bots/DefaultActivityHandler.cs
  skills/csharp/experimental/itsmskill/Bots/DialogBot.cs
  skills/csharp/experimental/itsmskill/Dialogs/MainDialog.cs
  skills/csharp/experimental/itsmskill/ITSMSkill.csproj
  skills/csharp/experimental/itsmskill/Startup.cs
  skills/csharp/experimental/restaurantbookingskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/restaurantbookingskill/Adapters/RestaurantSkillWebSocketBotAdapter.cs
  skills/csharp/experimental/restaurantbookingskill/Bots/DefaultActivityHandler.cs
  skills/csharp/experimental/restaurantbookingskill/Bots/DialogBot.cs
  skills/csharp/experimental/restaurantbookingskill/Dialogs/MainDialog.cs
  skills/csharp/experimental/restaurantbookingskill/RestaurantBookingSkill.csproj
  skills/csharp/experimental/restaurantbookingskill/Startup.cs
Labels: PR: reviewed-approved

#2650 [Calendar][News][Phone] update to ActivityHandler
  skills/csharp/calendarskill/Adapters/CalendarSkillWebSocketBotAdapter.cs
  skills/csharp/calendarskill/Adapters/DefaultAdapter.cs
  skills/csharp/calendarskill/Bots/DefaultActivityHandler.cs
  skills/csharp/calendarskill/Bots/DialogBot.cs
  skills/csharp/calendarskill/CalendarSkill.csproj
  skills/csharp/calendarskill/Dialogs/MainDialog.cs
  skills/csharp/calendarskill/Startup.cs
  skills/csharp/experimental/newsskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/newsskill/Adapters/NewsSkillWebSocketBotAdapter.cs
  skills/csharp/experimental/newsskill/Bots/DefaultActivityHandler.cs
  skills/csharp/experimental/newsskill/Bots/DialogBot.cs
  skills/csharp/experimental/newsskill/Dialogs/MainDialog.cs
  skills/csharp/experimental/newsskill/NewsSkill.csproj
  skills/csharp/experimental/newsskill/Startup.cs
  skills/csharp/experimental/phoneskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/phoneskill/Adapters/PhoneSkillWebSocketBotAdapter.cs
  skills/csharp/experimental/phoneskill/Bots/DefaultActivityHandler.cs
  skills/csharp/experimental/phoneskill/Bots/DialogBot.cs
  skills/csharp/experimental/phoneskill/Dialogs/MainDialog.cs
  skills/csharp/experimental/phoneskill/PhoneSkill.csproj
  skills/csharp/experimental/phoneskill/Startup.cs
  skills/csharp/tests/calendarskill.tests/Flow/CalendarSkillTestBase.cs
  skills/csharp/tests/phoneskill.tests/Flow/PhoneSkillTestBase.cs
  skills/csharp/tests/phoneskill.tests/TestDouble/MockLuisRecognizer.cs
Labels: PR: reviewed-approved

#2524 [Calendar] Add retry count limitation
  skills/csharp/calendarskill/Dialogs/CalendarSkillDialogBase.cs
  skills/csharp/calendarskill/Dialogs/ChangeEventStatusDialog.cs
  skills/csharp/calendarskill/Dialogs/CreateEventDialog.cs
  skills/csharp/calendarskill/Dialogs/JoinEventDialog.cs
  skills/csharp/calendarskill/Dialogs/UpdateEventDialog.cs
  skills/csharp/calendarskill/Prompts/DatePrompt.cs
  skills/csharp/calendarskill/Prompts/DurationPrompt.cs
  skills/csharp/calendarskill/Prompts/GetEventPrompt.cs
  skills/csharp/calendarskill/Prompts/GetRecreateInfoPrompt.cs
  skills/csharp/calendarskill/Prompts/Options/CalendarPromptOptions.cs
  skills/csharp/calendarskill/Prompts/Options/DatePromptOptions.cs
  skills/csharp/calendarskill/Prompts/Options/GetEventOptions.cs
  skills/csharp/calendarskill/Prompts/Options/NoSkipPromptOptions.cs
  skills/csharp/calendarskill/Prompts/Options/TimePromptOptions.cs
  skills/csharp/calendarskill/Prompts/TimePrompt.cs
  skills/csharp/calendarskill/Responses/Shared/CalendarSharedResponses.cs
  skills/csharp/calendarskill/Responses/Shared/CalendarSharedResponses.de.json
  skills/csharp/calendarskill/Responses/Shared/CalendarSharedResponses.es.json
  skills/csharp/calendarskill/Responses/Shared/CalendarSharedResponses.fr.json
  skills/csharp/calendarskill/Responses/Shared/CalendarSharedResponses.it.json
  skills/csharp/calendarskill/Responses/Shared/CalendarSharedResponses.json
  skills/csharp/calendarskill/Responses/Shared/CalendarSharedResponses.zh.json
  skills/csharp/calendarskill/Utilities/CalendarCommonUtil.cs
  skills/csharp/tests/calendarskill.tests/Flow/CreateCalendarFlowTests.cs
Labels: PR: unreviewed

#2648 [Doc] update links
  docs/_docs/skills/samples/hospitality.md
  docs/_docs/skills/samples/itsm.md
  docs/_docs/skills/samples/point-of-interest.md
  docs/_docs/virtual-assistant/handbook/events.md
Labels: PR: reviewed-approved

#2120 Add name extraction for onboarding
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/LU/de/General.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/LU/en/General.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/LU/es/General.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/LU/fr/General.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/LU/it/General.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/LU/zh/General.lu
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/OnboardingDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Services/GeneralLuis.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/LU/de/general.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/LU/en/general.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/LU/es/general.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/LU/fr/general.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/LU/it/general.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Resources/LU/zh/general.lu
  templates/Virtual-Assistant-Template/csharp/Template/VA/Dialogs/MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Dialogs/OnboardingDialog.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Models/AssistantState.cs
  templates/Virtual-Assistant-Template/csharp/Template/VA/Services/GeneralLuis.cs
Labels: PR: unreviewed

#2646 [Calendar]fix search meeting by time in the prompt
  skills/csharp/calendarskill/Prompts/GetEventPrompt.cs
Labels: PR: reviewed-approved

#2652 [Hospitality] LateCheckOut uses time
  skills/csharp/experimental/hospitalityskill/Dialogs/HospitalityDialogBase.cs
  skills/csharp/experimental/hospitalityskill/Dialogs/LateCheckOutDialog.cs
  skills/csharp/experimental/hospitalityskill/Dialogs/MainDialog.cs
  skills/csharp/experimental/hospitalityskill/Models/HospitalitySkillState.cs
  skills/csharp/experimental/hospitalityskill/Models/HospitalityUserSkillState.cs
  skills/csharp/experimental/hospitalityskill/Models/ReservationData.cs
  skills/csharp/experimental/hospitalityskill/Models/StateProperties.cs
  skills/csharp/experimental/hospitalityskill/Services/HotelService.cs
  skills/csharp/experimental/hospitalityskill/Services/IHotelService.cs
Labels: PR: reviewed-approved

#2662 [News] support location event
  skills/csharp/experimental/newsskill/Dialogs/MainDialog.cs
Labels: PR: reviewed-approved

#2660 [ToDo] libs update to 4.6.0-preview-rc2
  skills/csharp/tests/todoskill.tests/Flow/Fakes/MockLuisRecognizer.cs
  skills/csharp/tests/todoskill.tests/Flow/ToDoSkillTestBase.cs
  skills/csharp/todoskill/Adapters/DefaultAdapter.cs
  skills/csharp/todoskill/Adapters/ToDoSkillWebSocketBotAdapter.cs
  skills/csharp/todoskill/Bots/DefaultActivityHandler.cs
  skills/csharp/todoskill/Bots/DialogBot.cs
  skills/csharp/todoskill/Dialogs/MainDialog.cs
  skills/csharp/todoskill/Startup.cs
  skills/csharp/todoskill/ToDoSkill.csproj
Labels: PR: reviewed-approved

#2671 [Lib] Added skill switch dialog
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Dialogs/SwitchSkillDialog.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Dialogs/SwitchSkillDialogOptions.cs
Labels: PR: unreviewed

#2667 [Automotive/BingSearch/Music] Update to ActivityHandler
  skills/csharp/experimental/automotiveskill/Adapters/AutomotiveSkillWebSocketBotAdapter.cs
  skills/csharp/experimental/automotiveskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/automotiveskill/AutomotiveSkill.csproj
  skills/csharp/experimental/automotiveskill/Bots/DefaultActivityHandler.cs
  skills/csharp/experimental/automotiveskill/Bots/DialogBot.cs
  skills/csharp/experimental/automotiveskill/Dialogs/MainDialog.cs
  skills/csharp/experimental/automotiveskill/Startup.cs
  skills/csharp/experimental/bingsearchskill/Adapters/CustomSkillAdapter.cs
  skills/csharp/experimental/bingsearchskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/bingsearchskill/BingSearchSkill.csproj
  skills/csharp/experimental/bingsearchskill/Bots/DefaultActivityHandler.cs
  skills/csharp/experimental/bingsearchskill/Bots/DialogBot.cs
  skills/csharp/experimental/bingsearchskill/Dialogs/MainDialog.cs
  skills/csharp/experimental/bingsearchskill/Startup.cs
  skills/csharp/experimental/musicskill/Adapters/CustomSkillAdapter.cs
  skills/csharp/experimental/musicskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/musicskill/Bots/DefaultActivityHandler.cs
  skills/csharp/experimental/musicskill/Bots/DialogBot.cs
  skills/csharp/experimental/musicskill/Dialogs/MainDialog.cs
  skills/csharp/experimental/musicskill/MusicSkill.csproj
  skills/csharp/experimental/musicskill/Startup.cs
  skills/csharp/tests/automotiveskill.tests/Flow/AutomotiveSkillTestBase.cs
  skills/csharp/tests/automotiveskill.tests/Flow/Fakes/MockLuisRecognizer.cs
Labels: PR: reviewed-approved

#2672 [Lib] Removed fallback
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Dialogs/ActivityHandlerDialog.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Dialogs/RouterDialog.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Dialogs/RouterDialogTurnResult.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Dialogs/RouterDialogTurnStatus.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/IFallbackRequestProvider.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/ISkillIntentRecognizer.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/ISkillTransport.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Models/SkillEvents.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillCallingRequestHandler.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillDialog.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillSwitchConfirmOption.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillWebSocketBotAdapter.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillWebSocketTransport.cs
  sdk/csharp/tests/microsoft.bot.builder.solutions.tests/Skills/Mocks/MockSkillTransport.cs
  sdk/csharp/tests/microsoft.bot.builder.solutions.tests/Skills/SkillDialogTest.cs
Labels: PR: reviewed-approved

#2644 [VA] dotnet 3.0 update
  templates/Virtual-Assistant-Template/csharp/Directory.Build.props
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/readme.md
Labels: PR: reviewed-approved

#2665 [VA] Skill switch dialog
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/BotTestBase.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/OnboardingDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.de-de.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.es-es.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.fr-fr.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.it-it.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/MainResponses.zh-cn.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Responses/OnboardingResponses.lg
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Services/BotSettings.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Services/DispatchLuis.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
Labels: PR: reviewed-approved

#2674 [Templates] Update the VATemplate and SkillTemplate to latest solutions lib
  templates/Skill-Template/csharp/Sample/SkillSample/Adapters/CustomSkillAdapter.cs
  templates/Skill-Template/csharp/Sample/SkillSample/Controllers/BotController.cs
  templates/Skill-Template/csharp/Sample/SkillSample/Dialogs/SkillDialogBase.cs
  templates/Skill-Template/csharp/Sample/SkillSample/SkillSample.csproj
  templates/Skill-Template/csharp/Sample/SkillSample/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
Labels: PR: reviewed-approved

#2632 [POI] use activity handler
  skills/csharp/pointofinterestskill/Adapters/DefaultAdapter.cs
  skills/csharp/pointofinterestskill/Adapters/POISkillWebSocketBotAdapter.cs
  skills/csharp/pointofinterestskill/Bots/DefaultActivityHandler.cs
  skills/csharp/pointofinterestskill/Bots/DialogBot.cs
  skills/csharp/pointofinterestskill/Dialogs/MainDialog.cs
  skills/csharp/pointofinterestskill/PointOfInterestSkill.csproj
  skills/csharp/pointofinterestskill/Startup.cs
  skills/csharp/tests/pointofinterestskill.tests/Flow/Fakes/MockGeneralLuisRecognizer.cs
  skills/csharp/tests/pointofinterestskill.tests/Flow/Fakes/MockPointOfInterestLuisRecognizer.cs
  skills/csharp/tests/pointofinterestskill.tests/Flow/PointOfInterestSkillTestBase.cs
Labels: PR: unreviewed

#2681 [POI][Todo] restore deploy scripts
  skills/csharp/pointofinterestskill/Deployment/Scripts/luis_functions.ps1
  skills/csharp/todoskill/Deployment/Scripts/luis_functions.ps1
Labels: PR: reviewed-approved

#2683 [POI] search for category when valid
  skills/csharp/pointofinterestskill/Deployment/Resources/LU/de/PointOfInterest.lu
  skills/csharp/pointofinterestskill/Deployment/Resources/LU/en/PointOfInterest.lu
  skills/csharp/pointofinterestskill/Deployment/Resources/LU/es/PointOfInterest.lu
  skills/csharp/pointofinterestskill/Deployment/Resources/LU/fr/PointOfInterest.lu
  skills/csharp/pointofinterestskill/Deployment/Resources/LU/it/PointOfInterest.lu
  skills/csharp/pointofinterestskill/Deployment/Resources/LU/zh/PointOfInterest.lu
  skills/csharp/pointofinterestskill/Dialogs/FindParkingDialog.cs
  skills/csharp/pointofinterestskill/Dialogs/MainDialog.cs
  skills/csharp/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
  skills/csharp/pointofinterestskill/Models/PointOfInterestSkillState.cs
  skills/csharp/pointofinterestskill/Services/AzureMapsGeoSpatialService.cs
  skills/csharp/pointofinterestskill/Services/FoursquareGeoSpatialService.cs
  skills/csharp/pointofinterestskill/Services/IGeoSpatialService.cs
  skills/csharp/pointofinterestskill/Services/PointOfInterestLuis.cs
  skills/csharp/tests/pointofinterestskill.tests/API/AzureMapsGeoSpatialServiceTests.cs
  skills/csharp/tests/pointofinterestskill.tests/API/Fakes/MockHttpClientHandlerGen.cs
  skills/csharp/tests/pointofinterestskill.tests/API/FoursquareGeoSpatialServiceTests.cs
  skills/csharp/tests/pointofinterestskill.tests/Flow/PointOfInterestDialogTests.cs
  skills/csharp/tests/pointofinterestskill.tests/Flow/Utterances/BaseTestUtterances.cs
  skills/csharp/tests/pointofinterestskill.tests/Flow/Utterances/FindParkingUtterances.cs
  skills/csharp/tests/pointofinterestskill.tests/Flow/Utterances/FindPointOfInterestUtterances.cs
  skills/csharp/tests/pointofinterestskill.tests/Flow/Utterances/RouteFromXToYUtterances.cs
Labels: PR: unreviewed

#2682 [Calendar] add bing spell check
  skills/csharp/calendarskill/Dialogs/CalendarSkillDialogBase.cs
  skills/csharp/calendarskill/Services/BotServices.cs
  skills/csharp/calendarskill/Services/BotSettings.cs
  skills/csharp/calendarskill/appsettings.json
Labels: PR: reviewed-approved

#2655 [Calendar] provide more reasonable time setting when book meeting
  skills/csharp/calendarskill/Dialogs/CreateEventDialog.cs
  skills/csharp/calendarskill/Services/BotSettings.cs
  skills/csharp/calendarskill/Utilities/DateTimeHelper.cs
  skills/csharp/calendarskill/appsettings.json
Labels: PR: unreviewed

#2686 [Automotive] remove repeat input
  skills/csharp/experimental/automotiveskill/Dialogs/VehicleSettingsDialog.cs
  skills/csharp/experimental/automotiveskill/Responses/VehicleSettings/VehicleSettingsResponses.cs
  skills/csharp/experimental/automotiveskill/Responses/VehicleSettings/VehicleSettingsResponses.de.json
  skills/csharp/experimental/automotiveskill/Responses/VehicleSettings/VehicleSettingsResponses.es.json
  skills/csharp/experimental/automotiveskill/Responses/VehicleSettings/VehicleSettingsResponses.fr.json
  skills/csharp/experimental/automotiveskill/Responses/VehicleSettings/VehicleSettingsResponses.it.json
  skills/csharp/experimental/automotiveskill/Responses/VehicleSettings/VehicleSettingsResponses.json
  skills/csharp/experimental/automotiveskill/Responses/VehicleSettings/VehicleSettingsResponses.zh.json
  skills/csharp/tests/automotiveskill.tests/Flow/VehicleSettingsTests.cs
Labels: PR: reviewed-approved

#2621 [ITSM] add tests
  skills/csharp/Skills.sln
  skills/csharp/emailskill/Bots/DefaultActivityHandler.cs
  skills/csharp/experimental/hospitalityskill/Startup.cs
  skills/csharp/experimental/itsmskill/Content/Knowledge.1.0.json
  skills/csharp/experimental/itsmskill/Content/Knowledge.json
  skills/csharp/experimental/itsmskill/Content/TicketUpdate.1.0.json
  skills/csharp/experimental/itsmskill/Content/TicketUpdate.json
  skills/csharp/experimental/itsmskill/Content/TicketUpdateClose.1.0.json
  skills/csharp/experimental/itsmskill/Content/TicketUpdateClose.json
  skills/csharp/experimental/itsmskill/Deployment/Resources/LU/en/secondary/TicketClose.lu
  skills/csharp/experimental/itsmskill/Deployment/Resources/LU/en/secondary/TicketCreate.lu
  skills/csharp/experimental/itsmskill/Services/ServiceNow/Management.cs
  skills/csharp/tests/itsmskill.tests/API/Fakes/MockData.cs
  skills/csharp/tests/itsmskill.tests/API/Fakes/MockServiceNowRestClient.cs
  skills/csharp/tests/itsmskill.tests/API/ServiceNowServiceTests.cs
  skills/csharp/tests/itsmskill.tests/Flow/Fakes/BaseMockLuisRecognizer.cs
  skills/csharp/tests/itsmskill.tests/Flow/Fakes/MockServiceManager.cs
  skills/csharp/tests/itsmskill.tests/Flow/GeneralFlowTests.cs
  skills/csharp/tests/itsmskill.tests/Flow/KnowledgeShowTests.cs
  skills/csharp/tests/itsmskill.tests/Flow/SkillTestBase.cs
  skills/csharp/tests/itsmskill.tests/Flow/Strings/CardStrings.cs
  skills/csharp/tests/itsmskill.tests/Flow/Strings/ContextStrings.cs
  skills/csharp/tests/itsmskill.tests/Flow/TicketCloseFlowTests.cs
  skills/csharp/tests/itsmskill.tests/Flow/TicketCreateFlowTests.cs
  skills/csharp/tests/itsmskill.tests/Flow/TicketShowFlowTests.cs
  skills/csharp/tests/itsmskill.tests/Flow/TicketUpdateFlowTests.cs
  skills/csharp/tests/itsmskill.tests/Flow/Utterances/BaseTestUtterances.cs
  skills/csharp/tests/itsmskill.tests/Flow/Utterances/GeneralTestUtterances.cs
  skills/csharp/tests/itsmskill.tests/Flow/Utterances/ITSMTestUtterances.cs
  skills/csharp/tests/itsmskill.tests/Flow/Utterances/KnowledgeShowUtterances.cs
  skills/csharp/tests/itsmskill.tests/Flow/Utterances/NonLuisUtterances.cs
  skills/csharp/tests/itsmskill.tests/Flow/Utterances/TicketCloseUtterances.cs
  skills/csharp/tests/itsmskill.tests/Flow/Utterances/TicketCreateUtterances.cs
  skills/csharp/tests/itsmskill.tests/Flow/Utterances/TicketShowUtterances.cs
  skills/csharp/tests/itsmskill.tests/Flow/Utterances/TicketUpdateUtterances.cs
  skills/csharp/tests/itsmskill.tests/ITSMSkill.Tests.csproj
Labels: PR: reviewed-approved

#2685 [Email Skill] Add event debug support
  skills/csharp/emailskill/Dialogs/MainDialog.cs
Labels: PR: reviewed-approved

#2669 [TypeScript][Skill Sample/Template] Update populateStateFromSemanticAction method in Skill
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/dialogs/_mainDialog.ts
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/dialogs/mainDialog.ts
Labels: PR: reviewed-approved

#2624 [Lib] Add support for Luis sentiment
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Extensions/ActivityEx.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Extensions/LuisRecognizerEx.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Models/SentimentType.cs
  sdk/csharp/tests/microsoft.bot.builder.solutions.tests/Extensions/LuisRecognizeExTest.cs
Labels: PR: reviewed-approved

#2695 [Sdk] restore ManifestTemplateFilename
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillController.cs
  sdk/csharp/tests/microsoft.bot.builder.solutions.tests/Skills/ManifestTests.cs
Labels: PR: reviewed-approved

#2678 [Template] remove usage of MicrosoftAppCredentials since it's not used any more
  templates/Skill-Template/csharp/Sample/SkillSample/Startup.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Startup.cs
Labels: PR: reviewed-approved

#2697 [Calendar] fix calendar overlap intents
  skills/csharp/calendarskill/Deployment/Resources/LU/de/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/en/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/es/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/fr/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/it/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/zh/Calendar.lu
  skills/csharp/calendarskill/Services/CalendarLuis.cs
Labels: PR: reviewed-approved

#2698 [Tools]add synchronize_deploy_scripts.ps1
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  samples/csharp/assistants/hospitality-assistant/Deployment/Scripts/deploy.ps1
  samples/csharp/assistants/hospitality-assistant/Deployment/Scripts/deploy_cognitive_models.ps1
  samples/csharp/assistants/hospitality-assistant/Deployment/Scripts/update_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/deploy.ps1
  tools/scripts/synchronize_deploy_scripts.ps1
Labels: PR: reviewed-approved

#2696 [Skills] sync none to general's
  skills/csharp/calendarskill/Deployment/Resources/LU/de/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/en/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/es/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/fr/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/it/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/zh/Calendar.lu
  skills/csharp/emailskill/Deployment/Resources/LU/de/Email.lu
  skills/csharp/emailskill/Deployment/Resources/LU/en/Email.lu
  skills/csharp/emailskill/Deployment/Resources/LU/es/Email.lu
  skills/csharp/emailskill/Deployment/Resources/LU/fr/Email.lu
  skills/csharp/emailskill/Deployment/Resources/LU/it/Email.lu
  skills/csharp/emailskill/Deployment/Resources/LU/zh/Email.lu
  skills/csharp/experimental/eventskill/Deployment/Resources/LU/en/Event.lu
  skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/de/Hospitality.lu
  skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/en/Hospitality.lu
  skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/es/Hospitality.lu
  skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/fr/Hospitality.lu
  skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/it/Hospitality.lu
  skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/zh/Hospitality.lu
  skills/csharp/experimental/itsmskill/Deployment/Resources/LU/en/ITSM.lu
  skills/csharp/experimental/musicskill/Deployment/Resources/LU/en/MusicSkill.lu
  skills/csharp/experimental/musicskill/Deployment/Resources/LU/zh/MusicSkill.lu
  skills/csharp/experimental/newsskill/Deployment/Resources/LU/en/News.lu
  skills/csharp/pointofinterestskill/Deployment/Resources/LU/de/PointOfInterest.lu
  skills/csharp/pointofinterestskill/Deployment/Resources/LU/en/PointOfInterest.lu
  skills/csharp/pointofinterestskill/Deployment/Resources/LU/es/PointOfInterest.lu
  skills/csharp/pointofinterestskill/Deployment/Resources/LU/fr/PointOfInterest.lu
  skills/csharp/pointofinterestskill/Deployment/Resources/LU/it/PointOfInterest.lu
  skills/csharp/pointofinterestskill/Deployment/Resources/LU/zh/PointOfInterest.lu
Labels: PR: reviewed-approved

#2694 [POI] parking requires current location
  skills/csharp/pointofinterestskill/Dialogs/FindParkingDialog.cs
  skills/csharp/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
  skills/csharp/pointofinterestskill/Models/OpenDefaultApp.cs
  skills/csharp/pointofinterestskill/Models/PointofInterestModel.cs
  skills/csharp/pointofinterestskill/PointOfInterestSkill.csproj
  skills/csharp/tests/pointofinterestskill.tests/API/AzureMapsGeoSpatialServiceTests.cs
  skills/csharp/tests/pointofinterestskill.tests/Flow/PointOfInterestDialogTests.cs
Labels: PR: reviewed-approved

#2693 [Hospitality] add tests
  skills/csharp/Skills.sln
  skills/csharp/experimental/hospitalityskill/Dialogs/CheckOutDialog.cs
  skills/csharp/experimental/hospitalityskill/Dialogs/ExtendStayDialog.cs
  skills/csharp/experimental/hospitalityskill/Dialogs/GetReservationDialog.cs
  skills/csharp/experimental/hospitalityskill/Dialogs/HospitalityDialogBase.cs
  skills/csharp/experimental/hospitalityskill/Dialogs/LateCheckOutDialog.cs
  skills/csharp/experimental/hospitalityskill/Dialogs/RequestItemDialog.cs
  skills/csharp/experimental/hospitalityskill/Dialogs/RoomServiceDialog.cs
  skills/csharp/experimental/hospitalityskill/Models/HospitalityUserSkillState.cs
  skills/csharp/experimental/hospitalityskill/Models/ReservationData.cs
  skills/csharp/experimental/hospitalityskill/Responses/RequestItem/RequestItemResponses.json
  skills/csharp/experimental/hospitalityskill/Services/HotelService.cs
  skills/csharp/experimental/hospitalityskill/Startup.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/CheckOutFlowTests.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/ExtendStayFlowTests.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/Fakes/BaseMockLuisRecognizer.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/GeneralFlowTests.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/GetReservationFlowTests.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/HospitalitySkillTestBase.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/LateCheckOutFlowTests.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/RequestItemFlowTests.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/RoomServiceFlowTests.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/Strings/CardStrings.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/Utterances/BaseTestUtterances.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/Utterances/CheckOutUtterances.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/Utterances/ExtendStayUtterances.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/Utterances/GeneralTestUtterances.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/Utterances/GetReservationUtterances.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/Utterances/HospitalityTestUtterances.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/Utterances/LateCheckOutUtterances.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/Utterances/NonLuisUtterances.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/Utterances/RequestItemUtterances.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/Utterances/RoomServiceUtterances.cs
  skills/csharp/tests/hospitalityskill.tests/HospitalitySkill.Tests.csproj
Labels: PR: reviewed-approved

#2677 [TypeScript] Fix vulnerabilities in dependencies
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/package-lock.json
  tools/botskills/package-lock.json
Labels: PR: reviewed-approved

#2699 [Lib] Added support for custom text and title in multi provider auth card
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Authentication/MultiProviderAuthDialog.cs
Labels: PR: reviewed-approved

#2661 [Calendar] check available dialog
  skills/csharp/calendarskill/CalendarSkill.csproj
  skills/csharp/calendarskill/Dialogs/CalendarSkillDialogBase.cs
  skills/csharp/calendarskill/Dialogs/CheckAvailableDialog.cs
  skills/csharp/calendarskill/Dialogs/CreateEventDialog.cs
  skills/csharp/calendarskill/Dialogs/FindContactDialog.cs
  skills/csharp/calendarskill/Dialogs/MainDialog.cs
  skills/csharp/calendarskill/Models/AvailabilityResult.cs
  skills/csharp/calendarskill/Models/CalendarSkillState.cs
  skills/csharp/calendarskill/Models/DialogOptions/FindContactDialogOptions.cs
  skills/csharp/calendarskill/Models/EventModel.cs
  skills/csharp/calendarskill/Responses/CheckAvailable/CheckAvailableResponses.cs
  skills/csharp/calendarskill/Responses/CheckAvailable/CheckAvailableResponses.de.json
  skills/csharp/calendarskill/Responses/CheckAvailable/CheckAvailableResponses.es.json
  skills/csharp/calendarskill/Responses/CheckAvailable/CheckAvailableResponses.fr.json
  skills/csharp/calendarskill/Responses/CheckAvailable/CheckAvailableResponses.it.json
  skills/csharp/calendarskill/Responses/CheckAvailable/CheckAvailableResponses.json
  skills/csharp/calendarskill/Responses/CheckAvailable/CheckAvailableResponses.tt
  skills/csharp/calendarskill/Responses/CheckAvailable/CheckAvailableResponses.zh.json
  skills/csharp/calendarskill/Services/CalendarService.cs
  skills/csharp/calendarskill/Services/GoogleAPI/GoogleCalendarAPI.cs
  skills/csharp/calendarskill/Services/ICalendarService.cs
  skills/csharp/calendarskill/Services/MSGraphAPI/MSGraphCalendarAPI.cs
  skills/csharp/calendarskill/Startup.cs
  skills/csharp/calendarskill/Utilities/Actions.cs
  skills/csharp/calendarskill/Utilities/CalendarCommonUtil.cs
  skills/csharp/calendarskill/Utilities/DisplayHelper.cs
  skills/csharp/tests/calendarskill.tests/Flow/CalendarSkillTestBase.cs
  skills/csharp/tests/calendarskill.tests/Flow/CheckAvailableFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/Fakes/MockCalendarService.cs
  skills/csharp/tests/calendarskill.tests/Flow/Fakes/MockServiceManager.cs
  skills/csharp/tests/calendarskill.tests/Flow/Utterances/CheckAvailableTestUtterances.cs
Labels: PR: reviewed-approved

#2649 add pre-commit hook to check copyright & license
  tools/githooks/README.md
  tools/githooks/pre-commit
Labels: PR: reviewed-approved

#2692 [Skills] Enable anonymous skill
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Auth/Authenticator.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Auth/IAuthenticationProvider.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Auth/MsJWTAuthenticationProvider.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillController.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillWebSocketAdapter.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillWebSocketRequestHandler.cs
Labels: PR: reviewed-approved

#2717 [Sdk] provide full PromptOptions for SwitchSkillDialogOptions
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Dialogs/SwitchSkillDialog.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Dialogs/SwitchSkillDialogOptions.cs
Labels: PR: reviewed-approved

#2714 [Sdk] change promptSettings to list to match each authenticationConnections
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Authentication/MultiProviderAuthDialog.cs
Labels: PR: reviewed-approved

#2718 Update Microsoft.Bot.Builder.Solutions.csproj
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Microsoft.Bot.Builder.Solutions.csproj
Labels: PR: unreviewed

#2708 [Template] Update the libs version
  templates/Skill-Template/csharp/Sample/SkillSample.Tests/SkillSample.Tests.csproj
  templates/Skill-Template/csharp/Sample/SkillSample/SkillSample.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
Labels: PR: reviewed-approved

#2720 Fix npm pack path
  build/build.botskills.ts.ps1
Labels: PR: reviewed-approved

#2711 [Doc] Fix proactive doc link issue
  docs/_docs/solution-accelerators/tutorials/enable-proactive-notifications/2-event-producer.md
  docs/_docs/solution-accelerators/tutorials/enable-proactive-notifications/3-event-handler.md
  docs/_docs/solution-accelerators/tutorials/enable-proactive-notifications/4-virtual-assistant.md
Labels: PR: reviewed-approved

#2723 [Docs] Replace all code references to next branch with master
  docs/_docs/clients-and-channels/clients/event-companion.md
  docs/_docs/clients-and-channels/clients/virtual-assistant-client.md
  docs/_docs/overview/virtual-assistant-template.md
  docs/_docs/skills/samples/experimental.md
  docs/_docs/skills/samples/itsm.md
  docs/_docs/skills/tutorials/add-prebuilt-skill/1-intro.md
  docs/_docs/solution-accelerators/assistants/enterprise-assistant.md
  docs/_docs/solution-accelerators/assistants/hospitality-assistant.md
Labels: PR: reviewed-approved

#2712 [POI][ITSM] fix
  skills/csharp/experimental/itsmskill/Deployment/Resources/LU/en/General.lu
  skills/csharp/tests/pointofinterestskill.tests/Flow/Utterances/BaseTestUtterances.cs
Labels: PR: reviewed-approved

#2713 [Calendar] find contact dialog refactor
  skills/csharp/calendarskill/Dialogs/CalendarSkillDialogBase.cs
  skills/csharp/calendarskill/Dialogs/FindContactDialog.cs
  skills/csharp/calendarskill/Responses/FindContact/FindContactResponses.cs
  skills/csharp/calendarskill/Responses/FindContact/FindContactResponses.de.json
  skills/csharp/calendarskill/Responses/FindContact/FindContactResponses.es.json
  skills/csharp/calendarskill/Responses/FindContact/FindContactResponses.fr.json
  skills/csharp/calendarskill/Responses/FindContact/FindContactResponses.it.json
  skills/csharp/calendarskill/Responses/FindContact/FindContactResponses.json
  skills/csharp/calendarskill/Responses/FindContact/FindContactResponses.zh.json
  skills/csharp/calendarskill/Utilities/Actions.cs
  skills/csharp/tests/calendarskill.tests/Flow/CreateCalendarFlowTests.cs
Labels: PR: reviewed-approved

#2730 [Template] Updates skill template to .netcore3.0
  templates/Skill-Template/csharp/Sample/SkillSample.Tests/SkillSample.Tests.csproj
  templates/Skill-Template/csharp/Sample/SkillSample/SkillSample.csproj
  templates/Skill-Template/csharp/Sample/SkillSample/Startup.cs
  templates/Skill-Template/csharp/Sample/SkillSample/readme.md
  templates/Skill-Template/csharp/Template/Skill.Tests/Skill.Tests.csproj
  templates/Skill-Template/csharp/Template/Skill/Skill.csproj
  templates/Skill-Template/csharp/Template/Skill/Startup.cs
Labels: PR: unreviewed

#2734 Merging fixes from Next into Master
  skills/csharp/experimental/automotiveskill/Dialogs/VehicleSettingsDialog.cs
  skills/csharp/experimental/bingsearchskill/Dialogs/SkillDialogBase.cs
  skills/csharp/experimental/eventskill/Dialogs/EventDialogBase.cs
  skills/csharp/experimental/hospitalityskill/Dialogs/MainDialog.cs
  skills/csharp/experimental/itsmskill/Dialogs/ShowTicketDialog.cs
  skills/csharp/experimental/musicskill/Dialogs/SkillDialogBase.cs
  skills/csharp/experimental/phoneskill/Dialogs/PhoneSkillDialogBase.cs
  skills/csharp/experimental/restaurantbookingskill/Dialogs/SkillDialogBase.cs
  skills/csharp/experimental/weatherskill/Dialogs/SkillDialogBase.cs
  skills/csharp/pointofinterestskill/Dialogs/MainDialog.cs
  skills/csharp/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
  skills/csharp/tests/automotiveskill.tests/Flow/AutomotiveSkillTestBase.cs
  skills/csharp/tests/calendarskill.tests/Flow/ChangeCalendarStatusFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/CheckAvailableFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/ConnectToMeetingFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/CreateCalendarFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/GeneralSkillFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/NextCalendarFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/SummaryCalendarFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/TimeRemainingFlowTests.cs
  skills/csharp/tests/calendarskill.tests/Flow/UpdateCalendarFlowTests.cs
  skills/csharp/tests/emailskill.tests/Flow/EmailSkillTestBase.cs
  skills/csharp/tests/hospitalityskill.tests/Flow/HospitalitySkillTestBase.cs
  skills/csharp/tests/itsmskill.tests/Flow/SkillTestBase.cs
  skills/csharp/tests/phoneskill.tests/Flow/PhoneSkillTestBase.cs
  skills/csharp/tests/todoskill.tests/Flow/ToDoSkillTestBase.cs
Labels: PR: unreviewed

#2735 Update deployment scripts
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Scripts/update_cognitive_models.ps1
  samples/csharp/assistants/hospitality-assistant/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/calendarskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/emailskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/automotiveskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/bingsearchskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/eventskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/hospitalityskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/itsmskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/musicskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/newsskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/phoneskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/restaurantbookingskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/experimental/weatherskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/pointofinterestskill/Deployment/Scripts/update_cognitive_models.ps1
  skills/csharp/todoskill/Deployment/Scripts/update_cognitive_models.ps1
  templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/update_cognitive_models.ps1
  templates/Skill-Template/csharp/Template/Skill/Deployment/Scripts/update_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/update_cognitive_models.ps1
  templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/update_cognitive_models.ps1
Labels: PR: reviewed-approved

#2732 [Bing search skill] Change bg image to png for better support in andriod
  skills/csharp/experimental/bingsearchskill/Content/MovieCard.json
  skills/csharp/experimental/bingsearchskill/Content/PersonCard.json
Labels: PR: reviewed-approved

#2710 [Calendar][Email] fix lu
  skills/csharp/calendarskill/Deployment/Resources/LU/de-de/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/en-us/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/es-es/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/fr-fr/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/it-it/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/zh-cn/Calendar.lu
  skills/csharp/emailskill/Deployment/Resources/LU/de-de/Email.lu
  skills/csharp/emailskill/Deployment/Resources/LU/en-us/Email.lu
  skills/csharp/emailskill/Deployment/Resources/LU/es-es/Email.lu
  skills/csharp/emailskill/Deployment/Resources/LU/fr-fr/Email.lu
  skills/csharp/emailskill/Deployment/Resources/LU/it-it/Email.lu
  skills/csharp/emailskill/Deployment/Resources/LU/zh-cn/Email.lu
Labels: PR: unreviewed

#2736 [Docs] Updated Create VA tutorial
  docs/_docs/skills/tutorials/add-prebuilt-skill/4-connect-skill.md
  docs/_docs/skills/tutorials/create-skill/csharp/6-add-your-skill.md
  docs/_docs/skills/tutorials/create-skill/typescript/6-add-your-skill.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/1-intro.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/2-download-and-install.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/3-create-project.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/4-provision-your-azure-resources.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/5-run-your-assistant.md
Labels: PR: unreviewed

#2740 [Docs] Added activity flow doc
  docs/_docs/virtual-assistant/handbook/activity-flow.md
  docs/_docs/virtual-assistant/handbook/feedback.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models.md
  docs/assets/images/analytics/virtual-assistant-analytics-powerbi-13.png
  docs/assets/images/virtual-assistant-main-dialog-flow.png
Labels: PR: reviewed-approved

#2747 fix comments
  skills/csharp/emailskill/Adapters/DefaultAdapter.cs
  skills/csharp/emailskill/Adapters/EmailSkillWebSocketBotAdapter.cs
  skills/csharp/emailskill/Dialogs/DeleteEmailDialog.cs
  skills/csharp/emailskill/Dialogs/EmailSkillDialogBase.cs
  skills/csharp/emailskill/Dialogs/FindContactDialog.cs
  skills/csharp/emailskill/Dialogs/ForwardEmailDialog.cs
  skills/csharp/emailskill/Dialogs/MainDialog.cs
  skills/csharp/emailskill/Dialogs/ReplyEmailDialog.cs
  skills/csharp/emailskill/Dialogs/SendEmailDialog.cs
  skills/csharp/emailskill/Dialogs/ShowEmailDialog.cs
  skills/csharp/emailskill/Responses/DeleteEmail/DeleteEmailTexts.zh-cn.lg
  skills/csharp/emailskill/Responses/FindContact/FindContactTexts.de-de.lg
  skills/csharp/emailskill/Responses/FindContact/FindContactTexts.zh-cn.lg
  skills/csharp/emailskill/Responses/SendEmail/SendEmailTexts.zh-cn.lg
  skills/csharp/emailskill/Responses/Shared/SharedTexts.zh-cn.lg
  skills/csharp/emailskill/Responses/ShowEmail/ShowEmailTexts.zh-cn.lg
  skills/csharp/emailskill/Utilities/LGHelper.cs
  skills/csharp/tests/emailskill.tests/Flow/DeleteEmailFlowTests.cs
  skills/csharp/tests/emailskill.tests/Flow/EmailSkillTestBase.cs
  skills/csharp/tests/emailskill.tests/Flow/ForwardEmailFlowTests.cs
  skills/csharp/tests/emailskill.tests/Flow/GeneralSkillFlowTests.cs
  skills/csharp/tests/emailskill.tests/Flow/ReplyFlowTests.cs
  skills/csharp/tests/emailskill.tests/Flow/SendEmailFlowTests.cs
  skills/csharp/tests/emailskill.tests/Flow/ShowEmailFlowTests.cs
Labels: PR: unreviewed

#2755 [docs] fix broken links in experimental skills
  docs/_docs/skills/samples/bing-search.md
  docs/_docs/skills/samples/hospitality.md
  docs/_docs/skills/samples/music.md
  docs/_docs/skills/samples/news.md
  docs/_docs/skills/samples/restaurant-booking.md
  docs/_docs/skills/samples/weather.md
Labels: PR: unreviewed

#2756 Merge next into master
  skills/csharp/calendarskill/Deployment/Resources/LU/de-de/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/en-us/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/es-es/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/fr-fr/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/it-it/Calendar.lu
  skills/csharp/calendarskill/Deployment/Resources/LU/zh-cn/Calendar.lu
  skills/csharp/emailskill/Deployment/Resources/LU/de-de/Email.lu
  skills/csharp/emailskill/Deployment/Resources/LU/en-us/Email.lu
  skills/csharp/emailskill/Deployment/Resources/LU/es-es/Email.lu
  skills/csharp/emailskill/Deployment/Resources/LU/fr-fr/Email.lu
  skills/csharp/emailskill/Deployment/Resources/LU/it-it/Email.lu
  skills/csharp/emailskill/Deployment/Resources/LU/zh-cn/Email.lu
  skills/csharp/experimental/bingsearchskill/Content/MovieCard.json
  skills/csharp/experimental/bingsearchskill/Content/PersonCard.json
Labels: PR: unreviewed

#2760 fix comments; remove redundant relative path;
  skills/csharp/emailskill/EmailSkill.csproj
  skills/csharp/tests/emailskill.tests/Flow/EmailSkillTestBase.cs
  skills/csharp/tests/emailskill.tests/Flow/ForwardEmailFlowTests.cs
  skills/csharp/tests/emailskill.tests/Flow/ShowEmailFlowTests.cs
Labels: PR: unreviewed

#2750 [TypeScript] Remove Microsoft Bot Protocol dependency and related classes
  sdk/typescript/libraries/botbuilder-skills/package.json
  sdk/typescript/libraries/botbuilder-skills/src/index.ts
  sdk/typescript/libraries/botbuilder-skills/src/protocol/index.ts
  sdk/typescript/libraries/botbuilder-skills/src/protocol/routeContext.ts
  sdk/typescript/libraries/botbuilder-skills/src/protocol/routeTemplate.ts
  sdk/typescript/libraries/botbuilder-skills/src/protocol/router.ts
  sdk/typescript/libraries/botbuilder-skills/src/protocol/routerAction.ts
  sdk/typescript/libraries/botbuilder-skills/src/skillCallingRequestHandler.ts
  sdk/typescript/libraries/botbuilder-skills/src/websocket/index.ts
  sdk/typescript/libraries/botbuilder-skills/src/websocket/skillWebSocketAdapter.ts
  sdk/typescript/libraries/botbuilder-skills/src/websocket/skillWebSocketBotAdapter.ts
  sdk/typescript/libraries/botbuilder-skills/src/websocket/skillWebSocketRequestHandler.ts
  sdk/typescript/libraries/botbuilder-skills/src/websocket/skillWebSocketTransport.ts
  sdk/typescript/libraries/common/config/rush/.npmrc
  sdk/typescript/libraries/common/config/rush/npm-shrinkwrap.json
Labels: PR: reviewed-approved
