Repository microsoft/botframework-solutions, pull requests merged in 2020-07, with the labels that each got.

#3500 Fix Test build error
  sdk/csharp/tests/microsoft.bot.solutions.tests/Microsoft.Bot.Solutions.Tests.csproj
Labels: PR: unreviewed

#3494 Minor doc fixes pointed out by our community
  docs/_docs/overview/virtual-assistant-solution.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/csharp/3-edit-responses.md
Labels: PR: partially-approved, Type: Docs

#3536 Fixing formatting of feedback doc to ensure proper rendering of markdown
  docs/_docs/virtual-assistant/handbook/feedback.md
Labels: PR: partially-approved

#3499 Fix Nuget build error
  sdk/csharp/Directory.Build.props
  sdk/csharp/libraries/microsoft.bot.solutions/images/icon.png
Labels: PR: partially-approved

#3493 Add Microsoft.Bot.Solutions SDK UT
  sdk/csharp/libraries/microsoft.bot.solutions/Authentication/OAuthConnection.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Authentication/ProviderTokenResponse.cs
  sdk/csharp/libraries/microsoft.bot.solutions/BotSettingsBase.cs
  sdk/csharp/libraries/microsoft.bot.solutions/CognitiveModelSet.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Dialogs/ActivityHandlerDialog.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Dialogs/EventPrompt.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Dialogs/InterruptableDialog.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Dialogs/RouterDialog.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Feedback/FeedbackMiddleware.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Feedback/FeedbackOptions.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Feedback/FeedbackRecord.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Middleware/ContentModeratorMiddleware.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Models/OpenDefaultApp.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Proactive/ProactiveModel.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Proactive/ProactiveState.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Resources/General.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Serialization.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/Models/EnhancedBotFrameworkSkill.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/SkillException.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/SkillsConfiguration.cs
  sdk/csharp/libraries/microsoft.bot.solutions/TaskExtensions/ScheduledProcessor.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Testing/BotTestBase.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Authentication/AuthenticationTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Extensions/ActivityExTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Extensions/DateTimeExTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Extensions/DialogContextExtensionTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Extensions/ListExTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Extensions/LuisRecognizeExTest.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Extensions/OAuthProviderExtensionsTest.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Microsoft.Bot.Solutions.Tests.csproj
  sdk/csharp/tests/microsoft.bot.solutions.tests/Middleware/EventDebuggerMiddlewareTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Middleware/SetLocaleMiddlewareTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Middleware/SetSpeakMiddlewareTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Proactive/ProactiveTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Responses/LanguageGenerationTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Responses/ResponseGenerationTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Responses/SpeechUtilityTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Responses/Test.json
  sdk/csharp/tests/microsoft.bot.solutions.tests/Skills/Dialogs/SwitchSkillDialogTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Skills/SkillConversationIdFactoryTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/TaskExtensionTests/BackgroundWorkerTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Util/UtilTests.cs
Labels: PR: partially-approved

#3534 [PORT #3152][Botskills] Get the LU filename using basename
  tools/botskills/src/functionality/connectSkill.ts
Labels: PR: partially-approved

#3533 [PORT #3138][Botskills] Update tool documentation explaining new manifest schema changes
  docs/_docs/skills/handbook/botskills.md
  docs/_docs/skills/tutorials/create-skill/csharp/7-add-your-skill.md
  docs/_docs/skills/tutorials/create-skill/typescript/7-add-your-skill.md
  tools/botskills/docs/commands/connect.md
  tools/botskills/docs/commands/disconnect.md
  tools/botskills/docs/commands/update.md
Labels: PR: partially-approved

#3540 [Linked Account] fix bad request after link
  samples/csharp/clients/linkedaccounts.web/Controllers/HomeController.cs
  samples/csharp/clients/linkedaccounts.web/Controllers/LinkedAccountRepository.cs
Labels: PR: partially-approved

#3543 [Docs] Linked accounts, speech, script updates
  docs/_data/button.yml
  docs/_docs/clients-and-channels/tutorials/enable-speech/6-next-steps.md
  docs/_docs/overview/virtual-assistant-solution.md
  docs/_docs/solution-accelerators/samples/linked-accounts.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/csharp/3-edit-responses.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/typescript/4-edit-your-cognitive-models.md
Labels: PR: partially-approved, Type: Docs

#3557 Fix for encoding issue in update script
  docs/_docs/virtual-assistant/handbook/deployment-scripts.md
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/update_cognitive_models.ps1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/cognitivemodels.json
  samples/csharp/skill/SkillSample/Deployment/Scripts/update_cognitive_models.ps1
  samples/csharp/skill/SkillSample/cognitivemodels.json
  templates/csharp/Skill/Skill/Deployment/Scripts/update_cognitive_models.ps1
  templates/csharp/Skill/Skill/cognitivemodels.json
  templates/csharp/VA/VA/Deployment/Scripts/update_cognitive_models.ps1
  templates/csharp/VA/VA/cognitivemodels.json
Labels: PR: unreviewed

#3556 Update manifest.md to point to correct manifest schemas
  docs/_docs/skills/handbook/manifest.md
Labels: PR: partially-approved

#3555 Update skill template manifest to latest SDK versions
  samples/csharp/skill/SkillSample/wwwroot/manifest/manifest-1.0.json
  samples/csharp/skill/SkillSample/wwwroot/manifest/manifest-1.1.json
  templates/csharp/Skill/Skill/wwwroot/manifest/manifest-1.0.json
  templates/csharp/Skill/Skill/wwwroot/manifest/manifest-1.1.json
Labels: PR: partially-approved

#3569 Pavolum/add pii logging flag
  docs/_docs/solution-accelerators/tutorials/view-analytics/3-open-template.md
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Services/BotServices.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Services/BotSettings.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Startup.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/appsettings.json
  samples/csharp/skill/SkillSample/Services/BotServices.cs
  samples/csharp/skill/SkillSample/Services/BotSettings.cs
  samples/csharp/skill/SkillSample/Startup.cs
  samples/csharp/skill/SkillSample/appsettings.json
Labels: PR: partially-approved

#3572 Bring Virtual Assistant Client documentation inline with sample code
  docs/_docs/clients-and-channels/clients/virtual-assistant-client.md
Labels: PR: partially-approved

#3561 [Skill Template] Set default value for skill state accessor
  samples/csharp/skill/SkillSample/Dialogs/SkillDialogBase.cs
  templates/csharp/Skill/Skill/Dialogs/SkillDialogBase.cs
Labels: PR: partially-approved

#3461 Update VA in Hospitality Assistant and add test project
  samples/csharp/assistants/hospitality-assistant/HospitalityAssistant.sln
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.FunctionalTests/DirectLineClientTests.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.FunctionalTests/VirtualAssistantSample.FunctionalTests.csproj
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/BotTestBase.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/InterruptionTests.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/LocalizationTests.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/MainDialogTests.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/Mocks/MockLuisRecognizer.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/Mocks/MockMainDialog.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/OnboardingDialogTests.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/Resources/chitchat_default.json
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/Resources/chitchat_greeting.json
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/Resources/faq_default.json
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/Resources/faq_overview.json
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/TestData/QnAMaker_NoAnswer.json
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/Utilities/DispatchTestUtil.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/Utilities/GeneralTestUtil.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/Utterances/GeneralUtterances.Designer.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/Utterances/GeneralUtterances.resx
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Controllers/SkillController.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Resources/template.json
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Dialogs/OnboardingDialog.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/MainResponses.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Services/BotSettings.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Startup.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/TokenExchange/ITokenExchangeConfig.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/TokenExchange/TokenExchangeConfig.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/TokenExchange/TokenExchangeSkillHandler.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/appsettings.json
Labels: PR: partially-approved

#3597 Update template to working template supported by newest PowerBI version
  docs/assets/analytics/virtual-assistant-analytics-sample.pbit
Labels: PR: unreviewed

#3598 Update PowerBI template to template that has all latest changes and w…
  docs/assets/analytics/virtual-assistant-analytics-sample.pbit
Labels: PR: unreviewed
