Repository microsoft/botframework-solutions, pull requests merged in 2020-03, with the labels that each got.

#3140 Restore QnAMakerService to keep cognitive models working
  sdk/csharp/libraries/microsoft.bot.solutions/BotSettingsBase.cs
Labels: PR: reviewed-approved

#3147 Revert back to QnAMakerService references in VASample and scripts
  build/build.cognitive-models.ps1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Services/BotServices.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/cognitivemodels.json
Labels: PR: reviewed-approved

#3146 Change incorrect links
  .github/SUPPORT.md
  docs/_docs/virtual-assistant/handbook/migration.md
  samples/csharp/assistants/enterprise-assistant/Directory.Build.props
  samples/csharp/assistants/hospitality-assistant/Directory.Build.props
  samples/csharp/assistants/virtual-assistant/Directory.Build.props
  samples/csharp/clients/Directory.Build.props
  samples/csharp/clients/linkedaccounts.web/Views/Home/Index.cshtml
  samples/csharp/skill/Directory.Build.props
  skills/csharp/Directory.Build.props
  skills/csharp/experimental/phoneskill/readme.md
  templates/csharp/Directory.Build.props
  templates/typescript/generator-botbuilder-assistant/generators/app/README.md
Labels: PR: reviewed-approved

#3138 [Botskills] Update tool documentation explaining new manifest schema changes
  docs/_docs/skills/handbook/add-skills-to-a-virtual-assistant.md
  docs/_docs/skills/handbook/botskills.md
  docs/_docs/skills/tutorials/create-skill/csharp/7-add-your-skill.md
  docs/_docs/virtual-assistant/handbook/devops.md
  docs/_docs/virtual-assistant/handbook/migration.md
  tools/botskills/docs/commands/connect.md
  tools/botskills/docs/commands/disconnect.md
  tools/botskills/docs/commands/list.md
  tools/botskills/docs/commands/update.md
Labels: PR: reviewed-approved

#3150 [Botskills] Update outdated validation methods in migrate command
  tools/botskills/src/functionality/migrateSkill.ts
Labels: PR: reviewed-approved

#3151 [Documentation][DevOps] Update Continuous Deployment documentation
  docs/_docs/solution-accelerators/tutorials/enable-continuous-deployment/2-create-pipeline.md
  docs/_docs/solution-accelerators/tutorials/enable-continuous-deployment/3-configure-pipeline.md
  docs/assets/images/configure_release_pipeline_1.png
Labels: PR: reviewed-approved

#3152 [Botskills] Get the LU filename using basename
  tools/botskills/src/functionality/connectSkill.ts
Labels: PR: reviewed-approved

#3159 update sdk for solutions lib
  sdk/csharp/libraries/microsoft.bot.solutions/BotSettingsBase.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Microsoft.Bot.Solutions.csproj
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/Dialogs/SwitchSkillDialog.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/Models/SkillEvents.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/Responses/ResponseIdCollection.t4
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/Responses/SkillResponses.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/Responses/SkillResponses.de.json
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/Responses/SkillResponses.es.json
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/Responses/SkillResponses.fr.json
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/Responses/SkillResponses.it.json
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/Responses/SkillResponses.json
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/Responses/SkillResponses.tt
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/Responses/SkillResponses.zh.json
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/SkillConversationIdFactory.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/SkillDialogArgs.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/SkillMiddleware.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Skills/SkillMiddlewareTests.cs
Labels: PR: reviewed-approved

#3133 change from > to Out-File w/ encoding
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/update_cognitive_models.ps1
  samples/csharp/skill/SkillSample/Deployment/Scripts/update_cognitive_models.ps1
Labels: PR: reviewed-approved

#3164 update lib to rc0
  sdk/csharp/libraries/microsoft.bot.solutions/Microsoft.Bot.Solutions.csproj
  sdk/csharp/libraries/microsoft.bot.solutions/Responses/LocaleTemplateManager.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/SkillDialog.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Responses/LanguageGenerationTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Responses/TestResponses.es.lg
  sdk/csharp/tests/microsoft.bot.solutions.tests/Responses/TestResponses.lg
Labels: PR: reviewed-approved

#3163 update sdk for va sample
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/DirectLineClientTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/VirtualAssistantSample.FunctionalTests.csproj
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/BotTestBase.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/InterruptionTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/LocalizationTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/MainDialogTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/OnboardingDialogTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Bots/DefaultActivityHandler.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/OnboardingDialog.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Responses/MainResponses.de-de.lg
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Responses/MainResponses.es-es.lg
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Responses/MainResponses.fr-fr.lg
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Responses/MainResponses.it-it.lg
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Responses/MainResponses.lg
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Responses/MainResponses.zh-cn.lg
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Responses/OnboardingResponses.de-de.lg
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Responses/OnboardingResponses.es-es.lg
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Responses/OnboardingResponses.fr-fr.lg
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Responses/OnboardingResponses.it-it.lg
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Responses/OnboardingResponses.lg
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Responses/OnboardingResponses.zh-cn.lg
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Services/DispatchLuis.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Startup.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/appsettings.json
Labels: PR: unreviewed

#3167 update sdk lib to rc2 for solutions lib
  sdk/csharp/libraries/microsoft.bot.solutions/Microsoft.Bot.Solutions.csproj
  sdk/csharp/libraries/microsoft.bot.solutions/Responses/LocaleTemplateManager.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Responses/LanguageGenerationTests.cs
Labels: PR: unreviewed

#3166 update skill sample to latest sdk
  samples/csharp/skill/SkillSample.Tests/SkillModeTests.cs
  samples/csharp/skill/SkillSample.Tests/SkillSample.Tests.csproj
  samples/csharp/skill/SkillSample.Tests/SkillTestBase.cs
  samples/csharp/skill/SkillSample/Adapters/DefaultAdapter.cs
  samples/csharp/skill/SkillSample/Bots/DefaultActivityHandler.cs
  samples/csharp/skill/SkillSample/Dialogs/MainDialog.cs
  samples/csharp/skill/SkillSample/Dialogs/SkillDialogBase.cs
  samples/csharp/skill/SkillSample/Responses/AllResponses.de-de.lg
  samples/csharp/skill/SkillSample/Responses/AllResponses.es-es.lg
  samples/csharp/skill/SkillSample/Responses/AllResponses.fr-fr.lg
  samples/csharp/skill/SkillSample/Responses/AllResponses.it-it.lg
  samples/csharp/skill/SkillSample/Responses/AllResponses.lg
  samples/csharp/skill/SkillSample/Responses/AllResponses.zh-cn.lg
  samples/csharp/skill/SkillSample/Responses/MainResponses.de-de.lg
  samples/csharp/skill/SkillSample/Responses/MainResponses.es-es.lg
  samples/csharp/skill/SkillSample/Responses/MainResponses.fr-fr.lg
  samples/csharp/skill/SkillSample/Responses/MainResponses.it-it.lg
  samples/csharp/skill/SkillSample/Responses/MainResponses.lg
  samples/csharp/skill/SkillSample/Responses/MainResponses.zh-cn.lg
  samples/csharp/skill/SkillSample/Responses/SampleResponses.de-de.lg
  samples/csharp/skill/SkillSample/Responses/SampleResponses.es-es.lg
  samples/csharp/skill/SkillSample/Responses/SampleResponses.fr-fr.lg
  samples/csharp/skill/SkillSample/Responses/SampleResponses.it-it.lg
  samples/csharp/skill/SkillSample/Responses/SampleResponses.lg
  samples/csharp/skill/SkillSample/Responses/SampleResponses.zh-cn.lg
  samples/csharp/skill/SkillSample/SkillSample.csproj
  samples/csharp/skill/SkillSample/Startup.cs
  samples/csharp/skill/SkillSample/appsettings.json
Labels: PR: reviewed-approved

#3168 update va sample to rc2
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/DirectLineClientTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/VirtualAssistantSample.FunctionalTests.csproj
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/BotTestBase.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/InterruptionTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/LocalizationTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/MainDialogTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/OnboardingDialogTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
Labels: PR: reviewed-approved

#3160 [VA] remove duplicate GeneralResult
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/OnboardingDialog.cs
  templates/csharp/VA/VA/Dialogs/OnboardingDialog.cs
Labels: PR: unreviewed

#3185 [Botskills] Fix casing of the Skill's properties in the appsettings.json
  docs/_docs/help/known-issues.md
  docs/_docs/overview/whats-new/0.8-beta/migrate-existing-va-to-0.8.md
  docs/_docs/skills/handbook/add-skills-to-a-virtual-assistant.md
  docs/_docs/skills/handbook/botskills.md
  docs/_docs/virtual-assistant/handbook/devops.md
  tools/botskills/src/functionality/connectSkill.ts
  tools/botskills/src/functionality/disconnectSkill.ts
  tools/botskills/src/functionality/listSkill.ts
  tools/botskills/src/functionality/updateSkill.ts
  tools/botskills/src/models/appSetting.ts
  tools/botskills/src/models/skill.ts
Labels: PR: reviewed-approved

#3184 [Template] Update deployment scripts to use bf luis
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Resources/template.json
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/deploy_cognitive_models.ps1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/luis_functions.ps1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/qna_functions.ps1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/update_cognitive_models.ps1
  samples/csharp/skill/SkillSample/Deployment/Resources/template.json
  samples/csharp/skill/SkillSample/Deployment/Scripts/deploy.ps1
  samples/csharp/skill/SkillSample/Deployment/Scripts/deploy_cognitive_models.ps1
  samples/csharp/skill/SkillSample/Deployment/Scripts/luis_functions.ps1
  samples/csharp/skill/SkillSample/Deployment/Scripts/qna_functions.ps1
  samples/csharp/skill/SkillSample/Deployment/Scripts/update_cognitive_models.ps1
Labels: PR: reviewed-approved

#3182 [Documentation][BotSkills]Update Botskills documentation with migrate command
  docs/_docs/skills/handbook/botskills.md
  tools/botskills/docs/commands/migrate.md
  tools/botskills/src/botskills-migrate.ts
Labels: PR: reviewed-approved

#3154 [Skill] handle cancel/logout in skill mode
  samples/csharp/skill/SkillSample/Dialogs/MainDialog.cs
  templates/csharp/Skill/Skill/Dialogs/MainDialog.cs
Labels: PR: unreviewed

#3189 update to luisrecognizer v3
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/InterruptionTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/MainDialogTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/Mocks/MockLuisRecognizer.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Services/BotServices.cs
  samples/csharp/skill/SkillSample.Tests/Mocks/MockLuisRecognizer.cs
  samples/csharp/skill/SkillSample/Services/BotServices.cs
Labels: PR: reviewed-approved

#3129 [VA] handle SuppressCompletionMessage
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
  templates/csharp/VA/VA/Dialogs/MainDialog.cs
Labels: PR: reviewed-approved

#3114 [Sdk] change voiceName to dictionary for SetSpeakMiddleware
  sdk/csharp/libraries/microsoft.bot.solutions/Middleware/SetSpeakMiddleware.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Middleware/SetSpeakMiddlewareTests.cs
Labels: PR: reviewed-approved

#3195 update solutions lib to 4.8.1
  sdk/csharp/libraries/microsoft.bot.solutions/Microsoft.Bot.Solutions.csproj
Labels: PR: unreviewed

#3197 update sdk to 4.8.1 for VASample
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/VirtualAssistantSample.FunctionalTests.csproj
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/LocalizationTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/skill/SkillSample.Tests/SkillSample.Tests.csproj
  samples/csharp/skill/SkillSample/Dialogs/MainDialog.cs
  samples/csharp/skill/SkillSample/SkillSample.csproj
Labels: PR: unreviewed

#3202 update the doc for calendar book meeting room
  docs/_docs/skills/samples/calendar.md
Labels: PR: reviewed-approved

#3201 [Sdk] fix ProactiveStateMiddleware, add test
  sdk/csharp/libraries/microsoft.bot.solutions/Proactive/ProactiveStateMiddleware.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Proactive/ProactiveTests.cs
Labels: PR: reviewed-approved

#3199 [HA] update & fix VA
  samples/csharp/assistants/hospitality-assistant/HospitalityAssistant.sln
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Adapters/GoogleAdapterWithErrorHandler.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Bots/DefaultActivityHandler.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Controllers/GoogleController.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Controllers/SkillController.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Resources/QnA/de-de/Chitchat.qna
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Resources/QnA/es-es/Chitchat.qna
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Resources/QnA/es-es/Faq.qna
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Resources/QnA/fr-fr/Chitchat.qna
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Resources/QnA/it-it/Chitchat.qna
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Resources/QnA/zh-cn/Chitchat.qna
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Resources/template.json
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Scripts/deploy_cognitive_models.ps1
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Scripts/luis_functions.ps1
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Scripts/qna_functions.ps1
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Scripts/update_cognitive_models.ps1
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Dialogs/OnboardingDialog.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/AllResponses.de-de.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/AllResponses.es-es.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/AllResponses.fr-fr.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/AllResponses.it-it.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/AllResponses.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/AllResponses.zh-cn.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/MainResponses.de-de.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/MainResponses.es-es.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/MainResponses.fr-fr.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/MainResponses.it-it.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/MainResponses.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/MainResponses.zh-cn.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/OnboardingResponses.de-de.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/OnboardingResponses.es-es.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/OnboardingResponses.fr-fr.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/OnboardingResponses.it-it.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/OnboardingResponses.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Responses/OnboardingResponses.zh-cn.lg
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Services/BotServices.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Services/GeneralLuis.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Startup.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/appsettings.json
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/readme.md
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/skills.json
Labels: PR: reviewed-approved

#3218 SkillSample updates
  samples/csharp/skill/SkillSample.Tests/SkillSample.Tests.csproj
  samples/csharp/skill/SkillSample/Adapters/DefaultAdapter.cs
  samples/csharp/skill/SkillSample/Authentication/AllowedCallersClaimsValidator.cs
  samples/csharp/skill/SkillSample/Bots/DefaultActivityHandler.cs
  samples/csharp/skill/SkillSample/Dialogs/MainDialog.cs
  samples/csharp/skill/SkillSample/Dialogs/SampleAction.cs
  samples/csharp/skill/SkillSample/Dialogs/SampleDialog.cs
  samples/csharp/skill/SkillSample/Dialogs/SkillDialogBase.cs
  samples/csharp/skill/SkillSample/Extensions/ITurnContextEx.cs
  samples/csharp/skill/SkillSample/SkillSample.csproj
  samples/csharp/skill/SkillSample/Startup.cs
  samples/csharp/skill/SkillSample/appsettings.json
Labels: PR: unreviewed

#3219 Fix Enable Proactive Notification documentation
  docs/_docs/solution-accelerators/tutorials/enable-proactive-notifications/4-virtual-assistant.md
Labels: PR: reviewed-approved

#3207 Lamil/4 8 bugfixes
  samples/csharp/assistants/virtual-assistant/Directory.Build.props
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Resources/template.json
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/deploy_cognitive_models.ps1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/publish.ps1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/update_cognitive_models.ps1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/skill/SkillSample/Deployment/Resources/template.json
  samples/csharp/skill/SkillSample/Deployment/Scripts/deploy.ps1
  samples/csharp/skill/SkillSample/Deployment/Scripts/deploy_cognitive_models.ps1
  samples/csharp/skill/SkillSample/Deployment/Scripts/publish.ps1
  samples/csharp/skill/SkillSample/Deployment/Scripts/update_cognitive_models.ps1
  templates/csharp/Skill/Skill/Deployment/Resources/template.json
  templates/csharp/Skill/Skill/Deployment/Scripts/deploy.ps1
  templates/csharp/Skill/Skill/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/csharp/Skill/Skill/Deployment/Scripts/publish.ps1
  templates/csharp/Skill/Skill/Deployment/Scripts/update_cognitive_models.ps1
  templates/csharp/VA/VA/Deployment/Resources/template.json
  templates/csharp/VA/VA/Deployment/Scripts/deploy.ps1
  templates/csharp/VA/VA/Deployment/Scripts/deploy_cognitive_models.ps1
  templates/csharp/VA/VA/Deployment/Scripts/publish.ps1
  templates/csharp/VA/VA/Deployment/Scripts/update_cognitive_models.ps1
  templates/csharp/VA/VA/Dialogs/MainDialog.cs
Labels: PR: unreviewed

#3216 [EA] fix & update eva
  samples/csharp/assistants/enterprise-assistant/EnterpriseAssistant.sln
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Authentication/AllowedCallersClaimsValidator.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Bots/DefaultActivityHandler.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Controllers/BotController.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Controllers/SkillController.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Resources/QnA/de-de/Chitchat.qna
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Resources/QnA/en-us/Chitchat.qna
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Resources/QnA/es-es/Chitchat.qna
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Resources/QnA/fr-fr/Chitchat.qna
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Resources/QnA/it-it/Chitchat.qna
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Resources/QnA/zh-cn/Chitchat.qna
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Resources/template.json
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Scripts/deploy_cognitive_models.ps1
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Scripts/luis_functions.ps1
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Scripts/qna_functions.ps1
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Scripts/update_cognitive_models.ps1
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Dialogs/OnboardingDialog.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Models/StateProperties.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/AllResponses.de-de.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/AllResponses.es-es.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/AllResponses.fr-fr.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/AllResponses.it-it.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/AllResponses.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/AllResponses.zh-cn.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/MainResponses.de-de.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/MainResponses.es-es.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/MainResponses.fr-fr.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/MainResponses.it-it.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/MainResponses.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/MainResponses.zh-cn.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/OnboardingResponses.de-de.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/OnboardingResponses.es-es.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/OnboardingResponses.fr-fr.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/OnboardingResponses.it-it.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/OnboardingResponses.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Responses/OnboardingResponses.zh-cn.lg
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Services/BotServices.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Services/BotSettings.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Services/DispatchLuis.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Startup.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/appsettings.json
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/cognitivemodels.json
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/readme.md
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/skills.json
Labels: PR: reviewed-approved

#3209 [Botskills] Fix RegExp for validating URLs
  tools/botskills/src/utils/validationUtils.ts
  tools/botskills/test/connect.test.js
  tools/botskills/test/mocks/skills/invalidEndpoint.json
  tools/botskills/test/mocks/skills/invalidEndpointManifest.json
  tools/botskills/test/mocks/skills/invalidEndpointManifestV2.json
  tools/botskills/test/mocks/skills/invalidEndpointV2.json
Labels: PR: reviewed-approved

#3228 Various doc enhancements from bug bash
  docs/_docs/clients-and-channels/tutorials/enable-speech/4-integrate-speech-channel.md
  docs/_docs/skills/samples/calendar.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/csharp/2-edit-your-greeting.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/csharp/3-edit-responses.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/typescript/4-edit-your-cognitive-models.md
  docs/assets/images/calendar-meeting-room-script.png
  docs/assets/images/dlspeech_emulator.png
  docs/assets/images/dlspeechclient.png
  docs/assets/images/dlspeechclientsettings.png
Labels: PR: reviewed-approved, Type: Docs

#3235 Enable VA localization tests
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/BotTestBase.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/LocalizationTests.cs
Labels: PR: reviewed-approved

#3229 add oauth credentials to MultiProviderAuthDialog
  sdk/csharp/libraries/microsoft.bot.solutions/Authentication/MultiProviderAuthDialog.cs
  sdk/csharp/libraries/microsoft.bot.solutions/BotSettingsBase.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Microsoft.Bot.Solutions.csproj
  sdk/csharp/libraries/microsoft.bot.solutions/Testing/BotTestBase.cs
Labels: PR: unreviewed

#3239 VirtualAssistantSample updates
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/VirtualAssistantSample.FunctionalTests.csproj
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Bots/DefaultActivityHandler.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Controllers/SkillController.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/OnboardingDialog.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Program.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Startup.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/skill/SkillSample.Tests/SkillSample.Tests.csproj
  samples/csharp/skill/SkillSample/Adapters/DefaultAdapter.cs
  samples/csharp/skill/SkillSample/Program.cs
  samples/csharp/skill/SkillSample/SkillSample.csproj
Labels: PR: unreviewed

#3243 enable sso for VA
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Services/BotSettings.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Startup.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/TokenExchange/ITokenExchangeConfig.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/TokenExchange/TokenExchangeConfig.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/TokenExchange/TokenExchangeSkillHandler.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/appsettings.json
Labels: PR: unreviewed

#3234 update calendar doc
  docs/_docs/skills/samples/calendar.md
Labels: PR: reviewed-approved

#3242 Pavolum/enterprise assitant feedback sample
  .gitignore
  docs/_docs/overview/whats-new/1.0/feedback.md
  docs/_docs/virtual-assistant/handbook/feedback.md
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Feedback/FeedbackOptions.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Feedback/FeedbackRecord.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Feedback/FeedbackResponses.Designer.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Feedback/FeedbackResponses.de.resx
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Feedback/FeedbackResponses.es.resx
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Feedback/FeedbackResponses.fr.resx
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Feedback/FeedbackResponses.it.resx
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Feedback/FeedbackResponses.resx
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Feedback/FeedbackResponses.zh.resx
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Feedback/FeedbackUtil.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Startup.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  sdk/csharp/libraries/microsoft.bot.solutions/Feedback/FeedbackMiddleware.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Feedback/FeedbackMiddlewareTests.cs
Labels: PR: partially-approved

#3250 mark interruptable dialog obsolete
  sdk/csharp/libraries/microsoft.bot.solutions/Dialogs/EventPrompt.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Dialogs/InterruptableDialog.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Dialogs/InterruptionAction.cs
Labels: PR: partially-approved

#3251 update solutions lib to 1.0
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/skill/SkillSample/SkillSample.csproj
Labels: PR: partially-approved
