Repository microsoft/botframework-solutions, pull requests merged in 2020-05, with the labels that each got.

#3304 [TypeScript][Virtual Assistant] Chitchat as fallback
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/scripts/deploy_cognitive_models.ps1
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/scripts/update_cognitive_models.ps1
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/dialogs/mainDialog.ts
  templates/typescript/samples/sample-assistant/deployment/scripts/deploy_cognitive_models.ps1
  templates/typescript/samples/sample-assistant/deployment/scripts/update_cognitive_models.ps1
  templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts
Labels: PR: partially-approved

#3325 remove general intent from TODO lu file
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Resources/Skills/todoskill/en-us/ToDo.lu
Labels: PR: partially-approved

#3326 Fix update_cognitive_models.ps1 missing brace
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/update_cognitive_models.ps1
Labels: PR: partially-approved

#3323 Correct Property Setting for Speech Recognition Endpoint
  docs/_docs/clients-and-channels/clients/virtual-assistant-client.md
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/settings/SettingsActivity.java
  samples/android/clients/VirtualAssistantClient/app/src/main/res/layout-port/activity_settings.xml
  samples/android/clients/VirtualAssistantClient/app/src/main/res/layout/activity_settings.xml
  samples/android/clients/VirtualAssistantClient/app/src/main/res/values/strings.xml
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/assets/default_configuration.json
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/ConfigurationManager.java
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/SpeechSdk.java
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/model/Configuration.java
Labels: PR: partially-approved

#3333 update solutions to 4.9
  sdk/csharp/libraries/microsoft.bot.solutions/Microsoft.Bot.Solutions.csproj
  sdk/csharp/libraries/microsoft.bot.solutions/Responses/LocaleTemplateManager.cs
Labels: PR: unreviewed

#3331 Update VA/Skill Sample to SDK RC0 and fix LG tests
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/InterruptionTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/MainDialogTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/OnboardingDialogTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/skill/SkillSample/SkillSample.csproj
Labels: PR: unreviewed

#3335 Adding script for chitchat .qna file update
  tools/scripts/ChitChatUpdate.py
Labels: PR: partially-approved

#3288 [TypeScript][Virtual Assistant & Skill] Add lowerCaseLng config to i18next
  templates/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/index.ts
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/index.ts
  templates/typescript/samples/sample-assistant/src/index.ts
  templates/typescript/samples/sample-skill/src/index.ts
Labels: PR: partially-approved

#3313 [TypeScript] Telephony changes
  sdk/typescript/libraries/bot-solutions/src/extensions/activityEx.ts
  sdk/typescript/libraries/bot-solutions/src/middleware/setSpeakMiddleware.ts
  sdk/typescript/libraries/bot-solutions/test/middleware/setSpeakMiddleware.test.js
  sdk/typescript/libraries/bot-solutions/test/mocha.opts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/bots/_defaultActivityHandler.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/responses/MainResponses.lg
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/bots/defaultActivityHandler.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/responses/MainResponses.lg
  templates/typescript/samples/sample-assistant/src/bots/defaultActivityHandler.ts
  templates/typescript/samples/sample-assistant/src/responses/MainResponses.lg
  templates/typescript/samples/sample-skill/src/bots/defaultActivityHandler.ts
  templates/typescript/samples/sample-skill/src/responses/MainResponses.lg
Labels: PR: unreviewed

#3334 Update Functional Tests for QnA and fix ChitChat issue
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/DirectLineClientTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/BotTestBase.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/MainDialogTests.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/Mocks/MockMainDialog.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/TestData/QnAMaker_NoAnswer.json
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
Labels: PR: partially-approved

#3336 Virtual Assistant Client - Support Keyword Barge-in, Correct Build Error, & Update Gradle
  docs/_docs/clients-and-channels/clients/virtual-assistant-client.md
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/MainActivity.java
  samples/android/clients/VirtualAssistantClient/app/src/main/res/layout-land/activity_main.xml
  samples/android/clients/VirtualAssistantClient/app/src/main/res/layout/activity_main.xml
  samples/android/clients/VirtualAssistantClient/app/src/main/res/values/strings.xml
  samples/android/clients/VirtualAssistantClient/build.gradle
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/ConfigurationManager.java
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/model/Configuration.java
  samples/android/clients/VirtualAssistantClient/gradle/wrapper/gradle-wrapper.properties
Labels: PR: partially-approved

#3352 update botbuilder lib version to 4.9.0 release
  sdk/csharp/libraries/microsoft.bot.solutions/Microsoft.Bot.Solutions.csproj
Labels: PR: unreviewed

#3353 update va and skill sample to use latest sdk and latest bot.solutions
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/skill/SkillSample.Tests/SkillTestBase.cs
  samples/csharp/skill/SkillSample/SkillSample.csproj
Labels: PR: partially-approved

#3355 add oauth doc
  docs/_docs/skills/handbook/skill-oauth.md
  docs/assets/images/OAuth-Transcript.png
  docs/assets/images/OAuthConnection-TestConnection.png
  docs/assets/images/OAuthConnection.png
Labels: PR: unreviewed

#3356 update oauth doc
  docs/_docs/skills/handbook/skill-oauth.md
Labels: PR: unreviewed

#3357 update links
  docs/_docs/skills/handbook/skill-oauth.md
Labels: PR: unreviewed

#3360 update botbuilder sdk to 4.9.1 for bot.solutions lib
  sdk/csharp/libraries/microsoft.bot.solutions/Microsoft.Bot.Solutions.csproj
Labels: PR: unreviewed

#3361 update va and skill sample to botbuilder 4.9.1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/skill/SkillSample/SkillSample.csproj
Labels: PR: unreviewed

#3358 [TypeScript] Update botbuilder dependencies to 4.9.0
  sdk/typescript/libraries/bot-solutions/package-lock.json
  sdk/typescript/libraries/bot-solutions/package.json
  sdk/typescript/libraries/bot-solutions/src/extensions/dialogEx.ts
  sdk/typescript/libraries/bot-solutions/src/middleware/setSpeakMiddleware.ts
  sdk/typescript/libraries/bot-solutions/src/responses/localeTemplateManager.ts
  sdk/typescript/libraries/bot-solutions/test/middleware/setSpeakMiddleware.test.js
  sdk/typescript/libraries/bot-solutions/test/responses/testResponses.es.lg
  sdk/typescript/libraries/bot-solutions/test/responses/testResponses.lg
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/_package.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/dialogs/mainDialog.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/_package.json
  templates/typescript/samples/sample-assistant/package.json
  templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts
  templates/typescript/samples/sample-skill/package.json
Labels: PR: partially-approved

#3366 Fix Deployment Scripts
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  samples/csharp/skill/SkillSample/Deployment/Scripts/deploy.ps1
Labels: PR: reviewed-approved

#3367 dynamically register qnaDialog when user is in the middle of a multi turn qna
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
Labels: PR: partially-approved

#3369 update bot.solutions lib to 1.0.0
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/skill/SkillSample/SkillSample.csproj
Labels: PR: partially-approved

#3349 [Documentation] Chitchat as fallback migration documentation
  docs/_docs/overview/whats-new/1.0/migrate-existing-va-to-not-use-chitchat-in-dispatch.md
Labels: PR: partially-approved

#3346 [Documentation] Update botskills documentation
  docs/_docs/skills/handbook/botskills.md
  docs/_docs/skills/tutorials/create-skill/csharp/7-add-your-skill.md
  docs/_docs/skills/tutorials/create-skill/typescript/6-add-your-skill.md
Labels: PR: partially-approved

#3359 [TypeScript][Virtual Assistant & Skill] Improve request capacity updating @types/restify@^8.4.2
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/_package.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/index.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/_package.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/index.ts
  templates/typescript/samples/sample-assistant/package.json
  templates/typescript/samples/sample-assistant/src/index.ts
  templates/typescript/samples/sample-skill/package.json
  templates/typescript/samples/sample-skill/src/index.ts
Labels: PR: partially-approved

#3362 [TypeScript][Bot-Solutions] Implement changes in Bot-Solutions to 0.8 Beta release
  sdk/typescript/libraries/bot-solutions/package.json
  sdk/typescript/libraries/bot-solutions/src/authentication/multiProviderAuthDialog.ts
  sdk/typescript/libraries/bot-solutions/src/cognitiveModelSet.ts
  sdk/typescript/libraries/bot-solutions/src/dialogs/activityHandlerDialog.ts
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.zh.json
  sdk/typescript/libraries/bot-solutions/src/index.ts
  sdk/typescript/libraries/bot-solutions/src/remoteUserTokenProvider.ts
  sdk/typescript/libraries/bot-solutions/src/skills/dialogs/switchSkillDialogOptions.ts
  sdk/typescript/libraries/bot-solutions/src/skills/inProcAdapter.ts
  sdk/typescript/libraries/bot-solutions/src/skills/index.ts
  sdk/typescript/libraries/bot-solutions/src/skills/models/enhancedBotFrameworkSkill.ts
  sdk/typescript/libraries/bot-solutions/src/skills/models/index.ts
  sdk/typescript/libraries/bot-solutions/src/skills/models/manifest/action.ts
  sdk/typescript/libraries/bot-solutions/src/skills/models/manifest/actionDefinition.ts
  sdk/typescript/libraries/bot-solutions/src/skills/models/manifest/authenticationConnection.ts
  sdk/typescript/libraries/bot-solutions/src/skills/models/manifest/event.ts
  sdk/typescript/libraries/bot-solutions/src/skills/models/manifest/index.ts
  sdk/typescript/libraries/bot-solutions/src/skills/models/manifest/skillManifest.ts
  sdk/typescript/libraries/bot-solutions/src/skills/models/manifest/slot.ts
  sdk/typescript/libraries/bot-solutions/src/skills/models/manifest/triggers.ts
  sdk/typescript/libraries/bot-solutions/src/skills/models/manifest/utterance.ts
  sdk/typescript/libraries/bot-solutions/src/skills/models/manifest/utteranceSource.ts
  sdk/typescript/libraries/bot-solutions/src/skills/skillDialog.ts
  sdk/typescript/libraries/bot-solutions/src/skills/skillDialogOption.ts
  sdk/typescript/libraries/bot-solutions/src/skills/skillManifestGenerator.ts
  sdk/typescript/libraries/bot-solutions/src/skills/skillRouter.ts
  sdk/typescript/libraries/bot-solutions/src/skills/skillsConfiguration.ts
  sdk/typescript/libraries/bot-solutions/src/tokenEvents.ts
  sdk/typescript/libraries/bot-solutions/test/extensions/dateTimeEx.test.js
  sdk/typescript/libraries/bot-solutions/test/extensions/listEx.test.js
  sdk/typescript/libraries/bot-solutions/test/extensions/luisRecognizeEx.test.js
  sdk/typescript/libraries/bot-solutions/test/helpers/manifestServer.js
  sdk/typescript/libraries/bot-solutions/test/helpers/manifestUtilities.js
  sdk/typescript/libraries/bot-solutions/test/manifest.test.js
  sdk/typescript/libraries/bot-solutions/test/middleware/setSpeakMiddleware.test.js
  sdk/typescript/libraries/bot-solutions/test/mocks/fixtures/manifest_with_utterances.json
  sdk/typescript/libraries/bot-solutions/test/mocks/fixtures/manifest_without_utterances.json
  sdk/typescript/libraries/bot-solutions/test/mocks/mockMicrosoftAppCredentials.js
  sdk/typescript/libraries/bot-solutions/test/mocks/mockSkillTransport.js
  sdk/typescript/libraries/bot-solutions/test/mocks/resources/manifestTemplate.json
  sdk/typescript/libraries/bot-solutions/test/mocks/testData/luisCalendarModelResponse.json
  sdk/typescript/libraries/bot-solutions/test/mocks/testData/malformedManifestTemplate.json
  sdk/typescript/libraries/bot-solutions/test/mocks/testData/manifestInvalidIntent.json
  sdk/typescript/libraries/bot-solutions/test/mocks/testData/manifestInvalidLUISModel.json
  sdk/typescript/libraries/bot-solutions/test/mocks/testData/skillBeginEvent.json
  sdk/typescript/libraries/bot-solutions/test/mocks/testData/skillBeginEventWithOneParam.json
  sdk/typescript/libraries/bot-solutions/test/mocks/testData/skillBeginEventWithTwoParams.json
  sdk/typescript/libraries/bot-solutions/test/responses/languageGeneration.test.js
  sdk/typescript/libraries/bot-solutions/test/responses/responseGeneration.test.js
  sdk/typescript/libraries/bot-solutions/test/responses/speechUtility.test.js
Labels: PR: partially-approved

#3363 [TypeScript][Virtual Assistant] Implement changes in Virtual Assistant to 0.8 Beta release
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/adapters/defaultAdapter.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/cognitivemodels.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/dialogs/mainDialog.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/dialogs/onboardingDialog.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/index.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/locales/de-de.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/locales/en-us.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/locales/es-es.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/locales/fr-fr.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/locales/it-it.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/locales/zh-cn.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/models/stateProperties.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/templateManager/dictionaryRenderer.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/templateManager/graphClient.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/templateManager/templateManager.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/templateManager/templateRenderer.ts
  templates/typescript/samples/sample-assistant/src/adapters/defaultAdapter.ts
  templates/typescript/samples/sample-assistant/src/cognitivemodels.json
  templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts
  templates/typescript/samples/sample-assistant/src/dialogs/onboardingDialog.ts
  templates/typescript/samples/sample-assistant/src/index.ts
  templates/typescript/samples/sample-assistant/src/locales/de-de.json
  templates/typescript/samples/sample-assistant/src/locales/en-us.json
  templates/typescript/samples/sample-assistant/src/locales/es-es.json
  templates/typescript/samples/sample-assistant/src/locales/fr-fr.json
  templates/typescript/samples/sample-assistant/src/locales/it-it.json
  templates/typescript/samples/sample-assistant/src/locales/zh-cn.json
  templates/typescript/samples/sample-assistant/src/models/stateProperties.ts
  templates/typescript/samples/sample-assistant/src/templateManager/dictionaryRenderer.ts
  templates/typescript/samples/sample-assistant/src/templateManager/graphClient.ts
  templates/typescript/samples/sample-assistant/src/templateManager/templateManager.ts
  templates/typescript/samples/sample-assistant/src/templateManager/templateRenderer.ts
Labels: PR: partially-approved

#3364 [TypeScript][Skill] Implement changes in Skill to 0.8 Beta release
  templates/typescript/generator-bot-virtualassistant/generators/skill/src/copier.js
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/_manifestTemplate.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/index.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/manifest/_manifest-1.0.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/manifest/_manifest-1.1.json
  templates/typescript/generator-bot-virtualassistant/test/generator-bot-virtualassistant.skill.test.suite.js
  templates/typescript/samples/sample-skill/src/index.ts
  templates/typescript/samples/sample-skill/src/manifest/manifest-1.0.json
  templates/typescript/samples/sample-skill/src/manifest/manifest-1.1.json
  templates/typescript/samples/sample-skill/src/manifestTemplate.json
Labels: PR: partially-approved

#3368 Enhancements for Build (Virtual Assistant Client )
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/BaseActivity.java
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/settings/SettingsActivity.java
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/service/SpeechService.java
  samples/android/clients/VirtualAssistantClient/app/src/main/res/layout-port/activity_settings.xml
  samples/android/clients/VirtualAssistantClient/app/src/main/res/layout/activity_settings.xml
  samples/android/clients/VirtualAssistantClient/app/src/main/res/values/strings.xml
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/assets/default_configuration.json
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/ConfigurationManager.java
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/SpeechSdk.java
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/model/Configuration.java
Labels: PR: partially-approved

#3370 [TypeScript][Virtual Assistant] Add missing luisEndpoint argument in deploy.ps1
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/scripts/deploy.ps1
  templates/typescript/samples/sample-assistant/deployment/scripts/deploy.ps1
Labels: PR: partially-approved

#3371 update bot.solutions lib to 1.0.0
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/_package.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/_package.json
Labels: PR: unreviewed

#3372 [PORT PR #3367][TypeScript] dynamically register qnaDialog when user is in the middle of a multit…
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/dialogs/mainDialog.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/index.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/test/helpers/botTestBase.js
  templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts
  templates/typescript/samples/sample-assistant/src/index.ts
  templates/typescript/samples/sample-assistant/test/helpers/botTestBase.js
Labels: PR: partially-approved

#3373 [Botskills] Fix DispatchLuis not being overwritten
  tools/botskills/src/botskills-connect.ts
  tools/botskills/src/botskills-disconnect.ts
  tools/botskills/src/botskills-refresh.ts
  tools/botskills/src/botskills-update.ts
  tools/botskills/src/functionality/refreshSkill.ts
  tools/botskills/test/refresh.test.js
Labels: PR: partially-approved

#3379 [Botskills] Default to DispatchLuis className
  tools/botskills/src/functionality/refreshSkill.ts
Labels: PR: partially-approved

#3377 Update speech configuration to new schema
  docs/_docs/clients-and-channels/clients/virtual-assistant-client.md
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/MainActivity.java
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/settings/SettingsActivity.java
  samples/android/clients/VirtualAssistantClient/app/src/main/res/layout-port/activity_settings.xml
  samples/android/clients/VirtualAssistantClient/app/src/main/res/layout/activity_settings.xml
  samples/android/clients/VirtualAssistantClient/app/src/main/res/values/strings.xml
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/assets/default_configuration.json
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/ConfigurationManager.java
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/SpeechSdk.java
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/model/Configuration.java
Labels: PR: partially-approved

#3386 Add README reference to moved Skill samples
  README.md
  skills/README.md
Labels: PR: partially-approved

#3347 Composer: Virtual Assistant preview
  .gitignore
  samples/declarative/assistants/VirtualAssistant/.gitignore
  samples/declarative/assistants/VirtualAssistant/README.md
  samples/declarative/assistants/VirtualAssistant/dialogs/Chit-chat/Chit-chat.dialog
  samples/declarative/assistants/VirtualAssistant/dialogs/Chit-chat/language-generation/en-us/Chit-chat.en-us.lg
  samples/declarative/assistants/VirtualAssistant/dialogs/Chit-chat/language-understanding/en-us/Chit-chat.en-us.lu
  samples/declarative/assistants/VirtualAssistant/dialogs/FAQ/FAQ.dialog
  samples/declarative/assistants/VirtualAssistant/dialogs/FAQ/language-generation/en-us/FAQ.en-us.lg
  samples/declarative/assistants/VirtualAssistant/dialogs/FAQ/language-understanding/en-us/FAQ.en-us.lu
  samples/declarative/assistants/VirtualAssistant/dialogs/General/General.dialog
  samples/declarative/assistants/VirtualAssistant/dialogs/General/language-understanding/en-us/General.en-us.lu
  samples/declarative/assistants/VirtualAssistant/dialogs/Onboarding/Onboarding.dialog
  samples/declarative/assistants/VirtualAssistant/dialogs/Onboarding/language-generation/en-us/Onboarding.en-us.lg
  samples/declarative/assistants/VirtualAssistant/dialogs/Onboarding/language-understanding/en-us/Onboarding.en-us.lu
  samples/declarative/assistants/VirtualAssistant/language-generation/en-us/common.en-us.lg
  samples/declarative/assistants/VirtualAssistant/language-generation/en-us/general.en-us.lg
  samples/declarative/assistants/VirtualAssistant/language-generation/en-us/virtualassistant.en-us.lg
  samples/declarative/assistants/VirtualAssistant/language-understanding/en-us/virtualassistant.en-us.lu
  samples/declarative/assistants/VirtualAssistant/qnamaker/Deployment/Resources/QnA/en-us/Chitchat.qna
  samples/declarative/assistants/VirtualAssistant/qnamaker/Deployment/Resources/QnA/en-us/Faq.qna
  samples/declarative/assistants/VirtualAssistant/qnamaker/Deployment/Resources/template.json
  samples/declarative/assistants/VirtualAssistant/qnamaker/Deployment/Scripts/ChitChatUpdate.py
  samples/declarative/assistants/VirtualAssistant/qnamaker/Deployment/Scripts/deploy.ps1
  samples/declarative/assistants/VirtualAssistant/qnamaker/Deployment/Scripts/deploy_cognitive_models.ps1
  samples/declarative/assistants/VirtualAssistant/qnamaker/Deployment/Scripts/luis_functions.ps1
  samples/declarative/assistants/VirtualAssistant/qnamaker/Deployment/Scripts/qna_functions.ps1
  samples/declarative/assistants/VirtualAssistant/qnamaker/Deployment/Scripts/update_cognitive_models.ps1
  samples/declarative/assistants/VirtualAssistant/qnamaker/cognitivemodels.json
  samples/declarative/assistants/VirtualAssistant/scripts/DeploymentTemplates/function-template-with-preexisting-rg.json
  samples/declarative/assistants/VirtualAssistant/scripts/DeploymentTemplates/new-rg-parameters.json
  samples/declarative/assistants/VirtualAssistant/scripts/DeploymentTemplates/preexisting-rg-parameters.json
  samples/declarative/assistants/VirtualAssistant/scripts/DeploymentTemplates/template-with-new-rg.json
  samples/declarative/assistants/VirtualAssistant/scripts/DeploymentTemplates/template-with-preexisting-rg.json
  samples/declarative/assistants/VirtualAssistant/scripts/package.json
  samples/declarative/assistants/VirtualAssistant/scripts/provisionComposer.js
  samples/declarative/assistants/VirtualAssistant/settings/appsettings.json
  samples/declarative/assistants/VirtualAssistant/virtualassistant.dialog
Labels: PR: partially-approved

#3382 [TypeScript][Samples] Generate package-lock for samples
  templates/typescript/samples/sample-assistant/.npmrc
  templates/typescript/samples/sample-assistant/package-lock.json
  templates/typescript/samples/sample-skill/.npmrc
  templates/typescript/samples/sample-skill/package-lock.json
Labels: PR: partially-approved

#3384 [Documentation] Update JS packages
  README.md
Labels: PR: partially-approved

#3388 [Docs] Updates for 1.0
  docs/_docs/skills/tutorials/create-skill/csharp/2-download-and-install.md
  docs/_docs/skills/tutorials/create-skill/csharp/4-provision-your-azure-resources.md
  docs/_docs/skills/tutorials/create-skill/csharp/7-add-your-skill.md
  docs/_docs/skills/tutorials/create-skill/typescript/4-provision-your-azure-resources.md
  docs/_docs/skills/tutorials/create-skill/typescript/6-add-your-skill.md
  docs/_docs/virtual-assistant/handbook/deployment-scripts.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/2-download-and-install.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/3-create-project.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/4-provision-your-azure-resources.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/1-intro.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/2-download-and-install.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/4-provision-you-azure-resources.md
  docs/index.md
Labels: PR: partially-approved

#3383 [Documentation][Bot-Solutions] Add README
  sdk/typescript/libraries/bot-solutions/README.md
Labels: PR: unreviewed

#3398 Fix app crash on SettingsActivity rotation; update sdk logging O…
  samples/android/clients/VirtualAssistantClient/app/src/main/AndroidManifest.xml
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/settings/SettingsActivity.java
Labels: PR: partially-approved

#3415 Add PII telemetry instructions
  docs/_docs/solution-accelerators/tutorials/view-analytics/3-open-template.md
Labels: PR: partially-approved

#3409 Update weather skill doc
  docs/_docs/skills/samples/weather.md
Labels: PR: partially-approved

#3405 Clarify role of AD App
  docs/_docs/skills/tutorials/create-skill/csharp/4-provision-your-azure-resources.md
Labels: PR: unreviewed

#3391 Update Summary.md
  docs/_docs/overview/whats-new/1.0/Summary.md
Labels: PR: partially-approved

#3404 Update SSO with Bot doc link
  docs/_docs/skills/handbook/skill-oauth.md
Labels: PR: partially-approved

#3406 [Botskills] Fix vulnerabilities
  tools/botskills/package-lock.json
  tools/botskills/package.json
Labels: PR: unreviewed

#3418 Update Speech SDK to v1.12
  samples/android/clients/VirtualAssistantClient/directlinespeech/build.gradle
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/SpeechSdk.java
Labels: PR: partially-approved

#3397 [TypeScript][Virtual Assistant] Fix QnA validation after port #3372
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/dialogs/mainDialog.ts
  templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts
Labels: PR: partially-approved

#3392 Remove preview and update packages
  README.md
Labels: PR: unreviewed

#3131 Experimental Docs - Add Composer to a Skill
  docs/_docs/skills/handbook/experimental-add-composer.md
  docs/assets/images/composer-export-assets-to-zip.png
Labels: PR: unreviewed

#3421 Update Skill tutorial image
  docs/_docs/skills/tutorials/create-skill/csharp/6-run-your-skill.md
  docs/_docs/skills/tutorials/create-skill/typescript/5-run-your-skill.md
  docs/assets/images/quickstart-skill-greetingemulator.png
Labels: PR: unreviewed

#3422 Exchanging data with skills
  docs/_docs/virtual-assistant/handbook/exchanging-data-with-skills.md
Labels: PR: partially-approved

#3420 Fix to ARM Template to respect useComosDb on database
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Resources/template.json
  samples/csharp/skill/SkillSample/Deployment/Resources/template.json
Labels: PR: partially-approved

#3400 [TypeScript][Samples] Fix empty prompt in introStep using Teams
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/dialogs/mainDialog.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/dialogs/mainDialog.ts
  templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts
  templates/typescript/samples/sample-skill/src/dialogs/mainDialog.ts
Labels: PR: partially-approved

#3419 declaring $appName in UpdateLUIS
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Scripts/luis_functions.ps1
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Scripts/luis_functions.ps1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/luis_functions.ps1
  samples/csharp/skill/SkillSample/Deployment/Scripts/luis_functions.ps1
Labels: PR: partially-approved

#3390 Update publish scripts
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Scripts/publish.ps1
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Scripts/publish.ps1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/publish.ps1
Labels: PR: partially-approved

#3425 Fix broken link to Hospitality VA source code
  docs/_docs/solution-accelerators/assistants/hospitality-assistant.md
Labels: PR: partially-approved

#3423 Create CODEOWNERS for Android clients
  .github/CODEOWNERS
Labels: PR: partially-approved

#3424 [TypeScript] Add build props in the Samples and Templates
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/resources/template.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/resources/template.json
  templates/typescript/samples/sample-assistant/deployment/resources/template.json
  templates/typescript/samples/sample-skill/deployment/resources/template.json
Labels: PR: partially-approved

#3417 [TypeScript][Virtual Assistant] Handle versionChanged event adding onDialogEvent method
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/dialogs/mainDialog.ts
  templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts
Labels: PR: partially-approved

#3429 Fix deploy scripts with PowerShell Core 7.1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  samples/csharp/skill/SkillSample/Deployment/Scripts/deploy.ps1
  samples/csharp/skill/SkillSample/Deployment/Scripts/publish.ps1
Labels: PR: partially-approved

#3430 Update QnA Knowledgebase naming logic in qna_functions.ps1
  README.md
  docs/Gemfile.lock
  docs/_docs/overview/whats-new/1.0/Summary.md
  docs/_docs/skills/handbook/experimental-add-composer.md
  docs/_docs/skills/handbook/skill-oauth.md
  docs/_docs/skills/samples/weather.md
  docs/_docs/skills/tutorials/create-skill/csharp/2-download-and-install.md
  docs/_docs/skills/tutorials/create-skill/csharp/4-provision-your-azure-resources.md
  docs/_docs/skills/tutorials/create-skill/csharp/6-run-your-skill.md
  docs/_docs/skills/tutorials/create-skill/csharp/7-add-your-skill.md
  docs/_docs/skills/tutorials/create-skill/typescript/4-provision-your-azure-resources.md
  docs/_docs/skills/tutorials/create-skill/typescript/5-run-your-skill.md
  docs/_docs/skills/tutorials/create-skill/typescript/6-add-your-skill.md
  docs/_docs/solution-accelerators/tutorials/view-analytics/3-open-template.md
  docs/_docs/virtual-assistant/handbook/deployment-scripts.md
  docs/_docs/virtual-assistant/handbook/exchanging-data-with-skills.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/2-download-and-install.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/3-create-project.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/4-provision-your-azure-resources.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/1-intro.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/2-download-and-install.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/4-provision-you-azure-resources.md
  docs/assets/images/composer-export-assets-to-zip.png
  docs/assets/images/quickstart-skill-greetingemulator.png
  docs/index.md
  samples/android/clients/VirtualAssistantClient/app/src/main/AndroidManifest.xml
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/settings/SettingsActivity.java
  samples/android/clients/VirtualAssistantClient/directlinespeech/build.gradle
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/SpeechSdk.java
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Scripts/luis_functions.ps1
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Scripts/qna_functions.ps1
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Scripts/luis_functions.ps1
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Scripts/qna_functions.ps1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/luis_functions.ps1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/qna_functions.ps1
  samples/csharp/skill/SkillSample/Deployment/Scripts/luis_functions.ps1
  samples/csharp/skill/SkillSample/Deployment/Scripts/qna_functions.ps1
  sdk/typescript/libraries/bot-solutions/README.md
  skills/README.md
  templates/typescript/samples/sample-assistant/deployment/scripts/qna_functions.ps1
  templates/typescript/samples/sample-skill/deployment/scripts/qna_functions.ps1
Labels: PR: partially-approved

#3428 Update PBIT to reflect PowerBI data type change
  docs/assets/analytics/virtual-assistant-analytics-sample.pbit
Labels: PR: partially-approved
