Repository microsoft/botframework-solutions, pull requests merged in 2020-06, with the labels that each got.

#3438 [Botskills] Update documentation
  docs/_docs/skills/handbook/add-skills-to-a-virtual-assistant.md
  docs/_docs/skills/handbook/botskills.md
  docs/_docs/skills/tutorials/create-skill/csharp/7-add-your-skill.md
  docs/_docs/skills/tutorials/create-skill/typescript/6-add-your-skill.md
  tools/botskills/README.md
  tools/botskills/docs/commands/connect.md
  tools/botskills/docs/commands/disconnect.md
  tools/botskills/docs/commands/list.md
  tools/botskills/docs/commands/migrate.md
  tools/botskills/docs/commands/refresh.md
  tools/botskills/docs/commands/update.md
  tools/botskills/src/botskills-connect.ts
  tools/botskills/src/botskills-disconnect.ts
  tools/botskills/src/botskills-list.ts
  tools/botskills/src/botskills-update.ts
Labels: PR: partially-approved

#3434 get ITokenExchangeConfig from IServiceProvider
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/TokenExchange/TokenExchangeSkillHandler.cs
Labels: PR: partially-approved

#3442 [Botskills] Avoid warnings messages as errors
  tools/botskills/src/utils/childProcessUtils.ts
Labels: PR: partially-approved

#3443 [TypeScript] Migrate latest changes of ARM & deploy scripts, update botbuilder@4.9.2
  sdk/typescript/libraries/bot-solutions/package-lock.json
  sdk/typescript/libraries/bot-solutions/package.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/_package.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/resources/template.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/scripts/deploy.ps1
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/scripts/luis_functions.ps1
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/scripts/qna_functions.ps1
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/_package.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/resources/template.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/scripts/deploy.ps1
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/scripts/luis_functions.ps1
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/scripts/qna_functions.ps1
  templates/typescript/samples/sample-assistant/deployment/resources/template.json
  templates/typescript/samples/sample-assistant/deployment/scripts/deploy.ps1
  templates/typescript/samples/sample-assistant/deployment/scripts/luis_functions.ps1
  templates/typescript/samples/sample-assistant/package-lock.json
  templates/typescript/samples/sample-assistant/package.json
  templates/typescript/samples/sample-skill/deployment/resources/template.json
  templates/typescript/samples/sample-skill/deployment/scripts/deploy.ps1
  templates/typescript/samples/sample-skill/deployment/scripts/luis_functions.ps1
  templates/typescript/samples/sample-skill/package-lock.json
  templates/typescript/samples/sample-skill/package.json
Labels: PR: partially-approved

#3454 VA and Skill template updates for 1.0.1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/skill/SkillSample/SkillSample.csproj
  templates/csharp/Skill/Skill/Deployment/Resources/template.json
  templates/csharp/Skill/Skill/Deployment/Scripts/deploy.ps1
  templates/csharp/Skill/Skill/Deployment/Scripts/luis_functions.ps1
  templates/csharp/Skill/Skill/Deployment/Scripts/publish.ps1
  templates/csharp/Skill/Skill/Deployment/Scripts/qna_functions.ps1
  templates/csharp/Skill/Skill/Skill.csproj
  templates/csharp/VA/VA/Deployment/Resources/template.json
  templates/csharp/VA/VA/Deployment/Scripts/deploy.ps1
  templates/csharp/VA/VA/Deployment/Scripts/luis_functions.ps1
  templates/csharp/VA/VA/Deployment/Scripts/publish.ps1
  templates/csharp/VA/VA/Deployment/Scripts/qna_functions.ps1
  templates/csharp/VA/VA/TokenExchange/TokenExchangeSkillHandler.cs
  templates/csharp/VA/VA/VA.csproj
Labels: PR: partially-approved

#3453 Fix Urls in MarkDown
  docs/_docs/skills/samples/bing-search.md
  docs/_docs/skills/samples/hospitality.md
  docs/_docs/skills/samples/itsm.md
  docs/_docs/skills/samples/music.md
  docs/_docs/skills/samples/news.md
  docs/_docs/skills/samples/restaurant-booking.md
  docs/_docs/skills/samples/weather.md
  docs/_docs/solution-accelerators/assistants/hospitality-assistant.md
  docs/_docs/virtual-assistant/handbook/feedback.md
Labels: PR: partially-approved

#3457 Lamil/1.0.1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/skill/SkillSample/SkillSample.csproj
  sdk/csharp/libraries/microsoft.bot.solutions/Microsoft.Bot.Solutions.csproj
  templates/csharp/Skill/Skill/Skill.csproj
  templates/csharp/VA/VA/VA.csproj
Labels: PR: unreviewed

#3483 [Botskills] Add --force argument for bf luis convert method
  tools/botskills/src/functionality/connectSkill.ts
Labels: PR: partially-approved

#3471 Proactive and Feedback Util UT Tests in EnterpriseVA
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample.Tests/BotTestBase.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample.Tests/FeedbackTests.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample.Tests/ProactiveTests.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Feedback/FeedbackRecord.cs
  samples/csharp/clients/event-producer.event-hub/Program.cs
Labels: PR: unreviewed

#3426 Add InvokeHandler in VA
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/BotTestBase.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Bots/DefaultActivityHandler.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Extensions/InvokeActivityExtensions.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Extensions/InvokeResponseExtensions.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Models/SkillCardActionData.cs
Labels: PR: unreviewed

#3449 Add CodeQL security scanning
  .github/workflows/codeql.yml
Labels: PR: partially-approved

#3472 [Generator] Update documentation
  docs/_docs/skills/tutorials/create-skill/csharp/6-run-your-skill.md
  docs/_docs/skills/tutorials/create-skill/typescript/2-download-and-install.md
  docs/_docs/skills/tutorials/create-skill/typescript/3-create-your-skill.md
  docs/_docs/skills/tutorials/create-skill/typescript/4-provision-your-azure-resources.md
  docs/_docs/skills/tutorials/create-skill/typescript/5-update-manifest.md
  docs/_docs/skills/tutorials/create-skill/typescript/6-run-your-skill.md
  docs/_docs/skills/tutorials/create-skill/typescript/7-add-your-skill.md
  docs/_docs/skills/tutorials/create-skill/typescript/8-invoke-your-skill.md
  docs/_docs/skills/tutorials/create-skill/typescript/9-next-steps.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/5-run-your-assistant.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/1-intro.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/2-download-and-install.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/3-create-project.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/4-provision-you-azure-resources.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/5-run-your-assistant.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/csharp/3-edit-responses.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/typescript/2-edit-your-greeting.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/typescript/3-edit-responses.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/typescript/4-edit-your-cognitive-models.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/typescript/5-next-steps.md
Labels: PR: partially-approved

#3474 Concat texts for multiturn responses in Interactions table
  docs/assets/analytics/virtual-assistant-analytics-sample.pbit
Labels: PR: reviewed-approved

#3482 Close #3481: correct css unit typos
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/wwwroot/default.htm
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/wwwroot/default.htm
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/wwwroot/default.htm
  samples/csharp/skill/SkillSample/wwwroot/default.htm
  templates/csharp/Skill/Skill/wwwroot/default.htm
  templates/csharp/VA/VA/wwwroot/default.htm
Labels: PR: reviewed-approved

#3455 Add Bot identity To TurnState for Getting Token
  samples/csharp/clients/linkedaccounts.web/Controllers/HomeController.cs
  samples/csharp/clients/linkedaccounts.web/Controllers/LinkedAccountRepository.cs
Labels: PR: partially-approved
