Repository microsoft/botframework-solutions, pull requests merged in 2020-01, with the labels that each got.

#2854 Pro-active notifications (including Alexa pro-active events)
  skills/csharp/experimental/FoodOrderSkill/FoodOrderSkill.sln
  skills/csharp/experimental/FoodOrderSkill/FoodOrderSkill/Bots/DefaultActivityHandler.cs
  skills/csharp/experimental/FoodOrderSkill/FoodOrderSkill/Controllers/NotifyController.cs
  skills/csharp/experimental/FoodOrderSkill/FoodOrderSkill/Dialogs/RepeatOrderDialog.cs
  skills/csharp/experimental/FoodOrderSkill/FoodOrderSkill/FoodOrderSkill.csproj
  skills/csharp/experimental/FoodOrderSkill/FoodOrderSkill/Startup.cs
  skills/csharp/experimental/FoodOrderSkill/FoodOrderSkill/appsettings.json
Labels: PR: reviewed-approved

#2847 Add FeedbackMiddlewareTests
  sdk/csharp/tests/microsoft.bot.builder.solutions.tests/Feedback/FeedbackMiddlewareTests.cs
  sdk/csharp/tests/microsoft.bot.builder.solutions.tests/Responses/LanguageGenerationTests.cs
Labels: PR: reviewed-approved

#2845 update productive skills' manifest
  skills/csharp/calendarskill/manifestTemplate.json
  skills/csharp/emailskill/manifestTemplate.json
  skills/csharp/pointofinterestskill/manifestTemplate.json
  skills/csharp/todoskill/manifestTemplate.json
  tools/botskills/src/botskills-connect.ts
Labels: PR: reviewed-approved

#2857 fix doc for proactive notification
  docs/_docs/solution-accelerators/tutorials/enable-proactive-notifications/4-virtual-assistant.md
Labels: PR: reviewed-approved

#2863 add doc for migration for skills
  docs/_docs/skills/tutorials/migrate-to-new-skill/csharp/1-how-to.md
Labels: PR: reviewed-approved

#2745 [VA]Remove mentions (skills' will be removed when called from VA)
  docs/_docs/help/known-issues.md
Labels: PR: reviewed-approved

#2865 update va sample to professional chitchat
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/de-de/Chitchat.qna
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/en-us/Chitchat.qna
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/es-es/Chitchat.qna
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/fr-fr/Chitchat.qna
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/it-it/Chitchat.qna
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/QnA/zh-cn/Chitchat.qna
Labels: PR: reviewed-approved

#2858 Update all Skills to the latest 4.7 stable SDK packages
  skills/csharp/calendarskill/CalendarSkill.csproj
  skills/csharp/emailskill/EmailSkill.csproj
  skills/csharp/experimental/automotiveskill/AutomotiveSkill.csproj
  skills/csharp/experimental/bingsearchskill/BingSearchSkill.csproj
  skills/csharp/experimental/eventskill/EventSkill.csproj
  skills/csharp/experimental/hospitalityskill/HospitalitySkill.csproj
  skills/csharp/experimental/itsmskill/ITSMSkill.csproj
  skills/csharp/experimental/musicskill/MusicSkill.csproj
  skills/csharp/experimental/newsskill/NewsSkill.csproj
  skills/csharp/experimental/phoneskill/PhoneSkill.csproj
  skills/csharp/experimental/restaurantbookingskill/RestaurantBookingSkill.csproj
  skills/csharp/experimental/weatherskill/WeatherSkill.csproj
  skills/csharp/pointofinterestskill/PointOfInterestSkill.csproj
  skills/csharp/shared/SkillServiceLibrary/SkillServiceLibrary.csproj
  skills/csharp/todoskill/ToDoSkill.csproj
Labels: PR: reviewed-approved, Type: Maintenance

#2867 Pavolum/new skill implementation lib
  .gitignore
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Authentication/MultiProviderAuthDialog.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Microsoft.Bot.Builder.Solutions.csproj
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Auth/AuthHelpers.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Auth/Authenticator.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Auth/IAuthenticationProvider.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Auth/IAuthenticator.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Auth/IServiceClientCredentials.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Auth/IWhitelistAuthenticationProvider.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Auth/MicrosoftAppCredentialsEx.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Auth/MsJWTAuthenticationProvider.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Auth/WhitelistAuthenticationProvider.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Dialogs/SwitchSkillDialog.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Dialogs/SwitchSkillDialogOptions.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/IActivityHandler.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/ISkillTransport.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Models/EnhancedBotFrameworkSkill.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Protocol/RouteAction.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Protocol/RouteContext.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Protocol/RouteTemplate.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Protocol/Router.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillCallingRequestHandler.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillConstants.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillContext.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillController.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillConversationIdFactory.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillDialog.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillDialogArgs.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillDialogOption.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillMiddleware.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillWebSocketAdapter.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillWebSocketBotAdapter.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillWebSocketCallbackException.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillWebSocketRequestHandler.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillWebSocketTransport.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillsConfiguration.cs
  skills/csharp/Skills.sln
  skills/csharp/calendarskill/Adapters/CalendarSkillWebSocketBotAdapter.cs
  skills/csharp/calendarskill/CalendarSkill.csproj
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs
  templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/VirtualAssistantSample.csproj
Labels: PR: reviewed-approved

#2874 Fix build failures on solutions lib
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Authentication/MultiProviderAuthDialog.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Microsoft.Bot.Builder.Solutions.csproj
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Dialogs/SwitchSkillDialog.cs
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/SkillDialog.cs
Labels: PR: reviewed-approved

#2875 Temporarily exclude test project from solutions lib to enable daily build
  sdk/csharp/Microsoft.Bot.Builder.Solutions.sln
Labels: PR: reviewed-approved

#2883 [Skills] Unify CurrentUICulture
  skills/csharp/calendarskill/Adapters/CalendarSkillWebSocketBotAdapter.cs
  skills/csharp/calendarskill/Adapters/DefaultAdapter.cs
  skills/csharp/emailskill/Adapters/DefaultAdapter.cs
  skills/csharp/emailskill/Adapters/EmailSkillWebSocketBotAdapter.cs
  skills/csharp/experimental/automotiveskill/Adapters/AutomotiveSkillWebSocketBotAdapter.cs
  skills/csharp/experimental/automotiveskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/bingsearchskill/Adapters/CustomSkillAdapter.cs
  skills/csharp/experimental/bingsearchskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/eventskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/eventskill/Adapters/EventSkillAdapter.cs
  skills/csharp/experimental/hospitalityskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/hospitalityskill/Adapters/HospitalitySkillAdapter.cs
  skills/csharp/experimental/itsmskill/Adapters/CustomSkillAdapter.cs
  skills/csharp/experimental/itsmskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/musicskill/Adapters/CustomSkillAdapter.cs
  skills/csharp/experimental/musicskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/newsskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/newsskill/Adapters/NewsSkillWebSocketBotAdapter.cs
  skills/csharp/experimental/phoneskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/phoneskill/Adapters/PhoneSkillWebSocketBotAdapter.cs
  skills/csharp/experimental/restaurantbookingskill/Adapters/DefaultAdapter.cs
  skills/csharp/experimental/restaurantbookingskill/Adapters/RestaurantSkillWebSocketBotAdapter.cs
  skills/csharp/experimental/weatherskill/Adapters/CustomSkillAdapter.cs
  skills/csharp/experimental/weatherskill/Adapters/DefaultAdapter.cs
  skills/csharp/pointofinterestskill/Adapters/DefaultAdapter.cs
  skills/csharp/pointofinterestskill/Adapters/POISkillWebSocketBotAdapter.cs
  skills/csharp/todoskill/Adapters/DefaultAdapter.cs
  skills/csharp/todoskill/Adapters/ToDoSkillWebSocketBotAdapter.cs
Labels: PR: reviewed-approved

#2886 [Docs] fix nav
  docs/_includes/nav.html
Labels: PR: reviewed-approved

#2781 [Botskills] Add multilanguage documentation
  docs/_docs/clients-and-channels/tutorials/enable-teams/2-add-teams-channel.md
  docs/_docs/clients-and-channels/tutorials/enable-teams/3-install-app-studio.md
  docs/_docs/clients-and-channels/tutorials/enable-teams/4-create-app-manifest.md
  docs/_docs/clients-and-channels/tutorials/enable-teams/5-test-in-teams.md
  docs/_docs/clients-and-channels/tutorials/enable-teams/6-add-commands.md
  docs/_docs/help/known-issues.md
  docs/_docs/overview/virtual-assistant-template.md
  docs/_docs/skills/handbook/add-skills-to-a-virtual-assistant.md
  docs/_docs/skills/handbook/authentication.md
  docs/_docs/skills/handbook/best-practices.md
  docs/_docs/skills/handbook/botskills.md
  docs/_docs/skills/handbook/manifest.md
  docs/_docs/skills/handbook/multilanguage-functionality.md
  docs/_docs/skills/samples/automotive.md
  docs/_docs/skills/samples/phone.md
  docs/_docs/skills/samples/to-do.md
  docs/_docs/skills/tutorials/add-prebuilt-skill/2-download-and-install.md
  docs/_docs/skills/tutorials/add-prebuilt-skill/4-connect-skill.md
  docs/_docs/skills/tutorials/convert-v4-bot/csharp/2-add-packages.md
  docs/_docs/skills/tutorials/convert-v4-bot/csharp/3-skill-manifest.md
  docs/_docs/skills/tutorials/convert-v4-bot/typescript/2-add-packages.md
  docs/_docs/skills/tutorials/convert-v4-bot/typescript/3-skill-manifest.md
  docs/_docs/skills/tutorials/create-skill/csharp/2-download-and-install.md
  docs/_docs/skills/tutorials/create-skill/csharp/3-create-your-skill.md
  docs/_docs/skills/tutorials/create-skill/csharp/4-provision-your-azure-resources.md
  docs/_docs/skills/tutorials/create-skill/csharp/6-add-your-skill.md
  docs/_docs/skills/tutorials/create-skill/typescript/2-download-and-install.md
  docs/_docs/skills/tutorials/create-skill/typescript/4-provision-your-azure-resources.md
  docs/_docs/skills/tutorials/create-skill/typescript/6-add-your-skill.md
  docs/_docs/solution-accelerators/samples/linked-accounts.md
  docs/_docs/solution-accelerators/tutorials/enable-continuous-integration/csharp/2-add-coverlet.md
  docs/_docs/virtual-assistant/handbook/deployment-scripts.md
  docs/_docs/virtual-assistant/handbook/devops.md
  docs/_docs/virtual-assistant/handbook/localization.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/2-download-and-install.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/3-create-project.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/4-provision-your-azure-resources.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/2-download-and-install.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/typescript/4-edit-your-cognitive-models.md
  tools/botskills/README.md
  tools/botskills/docs/commands/connect.md
  tools/botskills/docs/commands/disconnect.md
  tools/botskills/docs/commands/list.md
  tools/botskills/docs/commands/refresh.md
  tools/botskills/docs/commands/update.md
  tools/botskills/docs/multilanguage-functionality.md
  tools/botskills/src/botskills-connect.ts
  tools/botskills/src/botskills-disconnect.ts
  tools/botskills/src/botskills-refresh.ts
  tools/botskills/src/botskills-update.ts
Labels: PR: reviewed-approved

#2894 [Android] Fix OpenDefaultApp behavior
  samples/android/clients/VirtualAssistantClient/app/build.gradle
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/models/OpenDefaultApp.java
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/service/SpeechService.java
Labels: PR: reviewed-approved

#2880 [Android] enable authentication in Android app
  samples/android/clients/VirtualAssistantClient/app/src/main/AndroidManifest.xml
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/linked_account/LinkedAccountActivity.java
  samples/android/clients/VirtualAssistantClient/app/src/main/java/com/microsoft/bot/builder/solutions/virtualassistant/activities/main/MainActivity.java
  samples/android/clients/VirtualAssistantClient/app/src/main/res/drawable/ic_signin.xml
  samples/android/clients/VirtualAssistantClient/app/src/main/res/layout/activity_linked_account.xml
  samples/android/clients/VirtualAssistantClient/app/src/main/res/menu/nav_drawer_menu.xml
  samples/android/clients/VirtualAssistantClient/app/src/main/res/values/strings.xml
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/assets/default_configuration.json
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/ConfigurationManager.java
  samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/model/Configuration.java
  samples/csharp/clients/linkedaccounts.web/Controllers/HomeController.cs
  samples/csharp/clients/linkedaccounts.web/Views/Home/LinkedAccounts.cshtml
  samples/csharp/clients/linkedaccounts.web/Views/Shared/_LoginPartial.cshtml
Labels: PR: reviewed-approved

#2882 Doc updates for Manifest and Action enhancements to an existing Skill
  docs/_docs/skills/tutorials/migrate-to-new-skill/csharp/1-how-to.md
  docs/_docs/skills/tutorials/migrate-to-new-skill/csharp/2-add-new-manifest.md
  docs/_docs/skills/tutorials/migrate-to-new-skill/csharp/3-add-action.md
Labels: PR: unreviewed

#2853 [BotBuilder-Libraries] Fix duplicate utterances text issue
  sdk/csharp/libraries/microsoft.bot.builder.solutions/Skills/Manifest/SkillManifestGenerator.cs
  sdk/typescript/libraries/botbuilder-skills/src/skillManifestGenerator.ts
Labels: PR: reviewed-approved

#2850 [Botskills] Implement support for --gov
  tools/botskills/src/functionality/connectSkill.ts
  tools/botskills/src/functionality/refreshSkill.ts
  tools/botskills/src/models/cloud.ts
  tools/botskills/src/models/index.ts
  tools/botskills/src/utils/azUtils.ts
  tools/botskills/src/utils/index.ts
Labels: PR: reviewed-approved

#2898 [Sdk]translation
  sdk/csharp/libraries/microsoft.bot.solutions/Feedback/FeedbackResponses.zh.resx
Labels: PR: reviewed-approved

#2868 Template changes for gov support
  docs/_includes/nav.html
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  samples/csharp/assistants/virtual-assistant/SkillSample.Tests/MainDialogTests.cs
  samples/csharp/assistants/virtual-assistant/SkillSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/virtual-assistant/SkillSample/Deployment/Resources/template.json
  samples/csharp/assistants/virtual-assistant/SkillSample/Deployment/Scripts/deploy.ps1
  samples/csharp/assistants/virtual-assistant/SkillSample/Dialogs/MainDialog.cs
  samples/csharp/assistants/virtual-assistant/SkillSample/Responses/MainResponses.de-de.lg
  samples/csharp/assistants/virtual-assistant/SkillSample/Responses/MainResponses.es-es.lg
  samples/csharp/assistants/virtual-assistant/SkillSample/Responses/MainResponses.fr-fr.lg
  samples/csharp/assistants/virtual-assistant/SkillSample/Responses/MainResponses.it-it.lg
  samples/csharp/assistants/virtual-assistant/SkillSample/Responses/MainResponses.lg
  samples/csharp/assistants/virtual-assistant/SkillSample/Responses/MainResponses.zh-cn.lg
  samples/csharp/assistants/virtual-assistant/SkillSample/Responses/SampleResponses.de-de.lg
  samples/csharp/assistants/virtual-assistant/SkillSample/Responses/SampleResponses.es-es.lg
  samples/csharp/assistants/virtual-assistant/SkillSample/Responses/SampleResponses.fr-fr.lg
  samples/csharp/assistants/virtual-assistant/SkillSample/Responses/SampleResponses.it-it.lg
  samples/csharp/assistants/virtual-assistant/SkillSample/Responses/SampleResponses.lg
  samples/csharp/assistants/virtual-assistant/SkillSample/Responses/SampleResponses.zh-cn.lg
  samples/csharp/assistants/virtual-assistant/SkillSample/Startup.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Resources/template.json
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Startup.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/readme.md
  skills/csharp/calendarskill/Deployment/Scripts/deploy.ps1
  skills/csharp/emailskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/automotiveskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/bingsearchskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/eventskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/hospitalityskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/itsmskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/musicskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/newsskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/phoneskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/restaurantbookingskill/Deployment/Scripts/deploy.ps1
  skills/csharp/experimental/weatherskill/Deployment/Scripts/deploy.ps1
  skills/csharp/pointofinterestskill/Deployment/Scripts/deploy.ps1
  skills/csharp/todoskill/Deployment/Scripts/deploy.ps1
  templates/csharp/Skill/Skill/Deployment/Scripts/deploy.ps1
  templates/csharp/VA/VA/Deployment/Scripts/deploy.ps1
Labels: PR: reviewed-approved

#2913 [Build] Update build files internal references
  build/build.generator-assistant.ts.ps1
  build/yaml/csharp/skill-sample.yml
  build/yaml/csharp/virtual-assistant-sample.yml
  build/yaml/typescript/generator-botbuilder-assistant.yml
  build/yaml/typescript/sample-assistant.yml
  build/yaml/typescript/sample-skill.yml
  docs/_docs/solution-accelerators/tutorials/enable-continuous-integration/csharp/3-create-yaml.md
  docs/_docs/solution-accelerators/tutorials/enable-continuous-integration/typescript/2-create-yaml.md
Labels: PR: reviewed-approved

#2914 [Template] Add SetSpeakMiddleware back
  templates/csharp/Skill/Skill/Adapters/DefaultAdapter.cs
  templates/csharp/VA/VA/Adapters/DefaultAdapter.cs
Labels: PR: reviewed-approved

#2911 Update Skill Template for new Manifest / SDK GA Changes
  templates/csharp/Skill/Skill.Tests/MainDialogTests.cs
  templates/csharp/Skill/Skill.Tests/Skill.Tests.csproj
  templates/csharp/Skill/Skill.Tests/SkillTestBase.cs
  templates/csharp/Skill/Skill/Adapters/CustomSkillAdapter.cs
  templates/csharp/Skill/Skill/Adapters/DefaultAdapter.cs
  templates/csharp/Skill/Skill/Controllers/BotController.cs
  templates/csharp/Skill/Skill/Dialogs/MainDialog.cs
  templates/csharp/Skill/Skill/Dialogs/SampleAction.cs
  templates/csharp/Skill/Skill/Dialogs/SampleDialog.cs
  templates/csharp/Skill/Skill/Skill.csproj
  templates/csharp/Skill/Skill/SkillProjectTemplate.vstemplate
  templates/csharp/Skill/Skill/Startup.cs
  templates/csharp/Skill/Skill/manifestTemplate.json
  templates/csharp/Skill/Skill/wwwroot/manifest/manifest.json
Labels: PR: reviewed-approved

#2901 [Botskills] Implement Inline Trigger Utterances feature
  tools/botskills/docs/connect.md
  tools/botskills/docs/inline-trigger-utterances-functionality.md
  tools/botskills/docs/update.md
  tools/botskills/src/botskills-connect.ts
  tools/botskills/src/botskills-update.ts
  tools/botskills/src/functionality/connectSkill.ts
  tools/botskills/src/functionality/refreshSkill.ts
  tools/botskills/src/functionality/updateSkill.ts
  tools/botskills/src/models/connectConfiguration.ts
  tools/botskills/src/models/updateConfiguration.ts
  tools/botskills/src/utils/filesUtils.ts
  tools/botskills/src/utils/index.ts
  tools/botskills/src/utils/sanitizationUtils.ts
Labels: PR: unreviewed

#2844 [TypeScript][Skill] Parity to release 0.6Beta
  templates/typescript/generator-botbuilder-assistant/generators/skill/src/copier.js
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/resources/LU/de-de/_skill.lu
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/resources/LU/en-us/_skill.lu
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/resources/LU/en-us/general.lu
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/resources/LU/es-es/_skill.lu
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/resources/LU/fr-fr/_skill.lu
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/resources/LU/it-it/_skill.lu
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/resources/LU/zh-cn/_skill.lu
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/resources/template.json
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/deploy.ps1
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/publish.ps1
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/deployment/scripts/update_cognitive_models.ps1
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/_manifestTemplate.json
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/adapters/defaultAdapter.ts
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/appsettings.json
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/bots/_dialogBot.ts
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/cognitivemodels.json
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/dialogs/_mainDialog.ts
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/dialogs/_skillDialogBase.ts
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/dialogs/sampleDialog.ts
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/index.ts
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/models/skillState.ts
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/responses/main/resources/MainResponses.json
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/test/helpers/skillTestBase.js
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/test/mainDialog.test.js
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/test/mocks/nockFixtures/localization_response_en-gb.json
  templates/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/test/mocks/nockFixtures/mainDialog_singleTurn_response.json
  templates/typescript/generator-botbuilder-assistant/test/generator-botbuilder-assistant.skill.test.suite.js
  templates/typescript/generator-botbuilder-assistant/test/generator-botbuilder-assistant.test.suite.js
  templates/typescript/samples/sample-skill/deployment/resources/LU/de-de/sampleSkill.lu
  templates/typescript/samples/sample-skill/deployment/resources/LU/en-us/general.lu
  templates/typescript/samples/sample-skill/deployment/resources/LU/en-us/sampleSkill.lu
  templates/typescript/samples/sample-skill/deployment/resources/LU/es-es/sampleSkill.lu
  templates/typescript/samples/sample-skill/deployment/resources/LU/fr-fr/sampleSkill.lu
  templates/typescript/samples/sample-skill/deployment/resources/LU/it-it/sampleSkill.lu
  templates/typescript/samples/sample-skill/deployment/resources/LU/zh-cn/sampleSkill.lu
  templates/typescript/samples/sample-skill/deployment/resources/template.json
  templates/typescript/samples/sample-skill/deployment/scripts/deploy.ps1
  templates/typescript/samples/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
  templates/typescript/samples/sample-skill/deployment/scripts/publish.ps1
  templates/typescript/samples/sample-skill/deployment/scripts/update_cognitive_models.ps1
  templates/typescript/samples/sample-skill/src/adapters/defaultAdapter.ts
  templates/typescript/samples/sample-skill/src/appsettings.json
  templates/typescript/samples/sample-skill/src/bots/dialogBot.ts
  templates/typescript/samples/sample-skill/src/cognitivemodels.json
  templates/typescript/samples/sample-skill/src/dialogs/mainDialog.ts
  templates/typescript/samples/sample-skill/src/dialogs/sampleDialog.ts
  templates/typescript/samples/sample-skill/src/dialogs/skillDialogBase.ts
  templates/typescript/samples/sample-skill/src/index.ts
  templates/typescript/samples/sample-skill/src/models/skillState.ts
  templates/typescript/samples/sample-skill/src/responses/main/resources/MainResponses.json
  templates/typescript/samples/sample-skill/test/helpers/skillTestBase.js
  templates/typescript/samples/sample-skill/test/mainDialog.test.js
  templates/typescript/samples/sample-skill/test/mocks/nockFixtures/localization_response_en-gb.json
  templates/typescript/samples/sample-skill/test/mocks/nockFixtures/mainDialog_singleTurn_response.json
Labels: PR: reviewed-approved

#2900 [TypeScript][Skill] Add onTurnError handler
  templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/adapters/defaultAdapter.ts
  templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/adapters/defaultAdapter.ts
Labels: PR: reviewed-approved

#2905 [Android] Version num fix
  samples/android/clients/VirtualAssistantClient/app/build.gradle
  samples/android/clients/VirtualAssistantClient/app/src/main/AndroidManifest.xml
  samples/android/clients/VirtualAssistantClient/build.gradle
Labels: PR: reviewed-approved, Type: Maintenance

#2885 [Docs][Master]fix proactive notifications and new line in code block
  docs/_docs/help/faq.md
  docs/_docs/help/known-issues.md
  docs/_docs/overview/virtual-assistant-solution.md
  docs/_docs/overview/virtual-assistant-template.md
  docs/_docs/skills/handbook/architecture.md
  docs/_docs/skills/handbook/best-practices.md
  docs/_docs/skills/samples/phone.md
  docs/_docs/skills/tutorials/add-prebuilt-skill/6-next-steps.md
  docs/_docs/skills/tutorials/create-skill/csharp/8-next-steps.md
  docs/_docs/skills/tutorials/create-skill/typescript/8-next-steps.md
  docs/_docs/skills/tutorials/customize-skill/csharp/5-next-steps.md
  docs/_docs/skills/tutorials/customize-skill/typescript/5-next-steps.md
  docs/_docs/solution-accelerators/assistants/enterprise-assistant.md
  docs/_docs/solution-accelerators/assistants/hospitality-assistant.md
  docs/_docs/solution-accelerators/tutorials/enable-continuous-deployment/3-configure-pipeline.md
  docs/_docs/solution-accelerators/tutorials/enable-proactive-notifications/1-intro.md
  docs/_docs/virtual-assistant/handbook/migration.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/6-next-steps.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/6-next-steps.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/typescript/1-intro.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/typescript/5-next-steps.md
Labels: PR: reviewed-approved

#2910 [Documentation] Add Firewall configuration in Known Issues documentation
  docs/_docs/help/known-issues.md
Labels: PR: reviewed-approved

#2922 add speak middleware to the samples
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/skill/SkillSample/Adapters/DefaultAdapter.cs
Labels: PR: unreviewed

#2917 Add New Skill Manifest to all Skills
  skills/csharp/Skills.sln
  skills/csharp/calendarskill/wwwroot/manifest/manifest.json
  skills/csharp/emailskill/wwwroot/manifest/manifest.json
  skills/csharp/experimental/automotiveskill/wwwroot/manifest/manifest.json
  skills/csharp/experimental/bingsearchskill/wwwroot/manifest/manifest.json
  skills/csharp/experimental/hospitalityskill/wwwroot/manifest/manifest.json
  skills/csharp/experimental/itsmskill/wwwroot/manifest/manifest.json
  skills/csharp/experimental/musicskill/wwwroot/manifest/manifest.json
  skills/csharp/experimental/newsskill/wwwroot/manifest.json
  skills/csharp/experimental/phoneskill/wwwroot/manifest/manifest.json
  skills/csharp/experimental/restaurantbookingskill/wwwroot/manifest/manifest.json
  skills/csharp/experimental/weatherskill/wwwroot/manifest/manifest.json
  skills/csharp/pointofinterestskill/wwwroot/manifest/manifest.json
  skills/csharp/todoskill/wwwroot/manifest/manifest.json
Labels: PR: reviewed-changes-requested

#2924 Move Changes made to VSIX back into sample
  samples/csharp/skill/SkillSample.Tests/SkillModeTests.cs
  samples/csharp/skill/SkillSample.Tests/SkillSample.Tests.csproj
  samples/csharp/skill/SkillSample.Tests/SkillTestBase.cs
  samples/csharp/skill/SkillSample/Adapters/CustomSkillAdapter.cs
  samples/csharp/skill/SkillSample/Adapters/DefaultAdapter.cs
  samples/csharp/skill/SkillSample/Controllers/BotController.cs
  samples/csharp/skill/SkillSample/Dialogs/MainDialog.cs
  samples/csharp/skill/SkillSample/SkillSample.csproj
  samples/csharp/skill/SkillSample/Startup.cs
  samples/csharp/skill/SkillSample/manifestTemplate.json
  samples/csharp/skill/SkillSample/wwwroot/manifest/manifest.json
Labels: PR: reviewed-approved

#2925 [VA]Update VA sample to use new Microsoft.Bot.Solutions package
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/BotTestBase.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/VirtualAssistantSample.Tests.csproj
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Authentication/AllowedCallersClaimsValidator.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Bots/DefaultActivityHandler.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Controllers/SkillController.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/OnboardingDialog.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Services/BotServices.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Services/BotSettings.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Startup.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
Labels: PR: reviewed-approved

#2929 [lib] upgrade to 4.7.2 for botbuilder sdk
  sdk/csharp/libraries/microsoft.bot.solutions/Microsoft.Bot.Solutions.csproj
Labels: PR: reviewed-approved

#2928 [VASample]correct case and add suppressCompletionMessage call
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Controllers/BotController.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Controllers/SkillController.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Startup.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/skills.json
Labels: PR: unreviewed

#2926 Update Skill Sample
  samples/csharp/skill/SkillSample.Tests/SkillSample.Tests.csproj
  samples/csharp/skill/SkillSample.Tests/SkillTestBase.cs
  samples/csharp/skill/SkillSample/Adapters/DefaultAdapter.cs
  samples/csharp/skill/SkillSample/Bots/DefaultActivityHandler.cs
  samples/csharp/skill/SkillSample/Dialogs/MainDialog.cs
  samples/csharp/skill/SkillSample/Dialogs/SkillDialogBase.cs
  samples/csharp/skill/SkillSample/Services/BotServices.cs
  samples/csharp/skill/SkillSample/Services/BotSettings.cs
  samples/csharp/skill/SkillSample/SkillSample.csproj
  samples/csharp/skill/SkillSample/Startup.cs
Labels: PR: unreviewed

#2938 [lib] add deprecation message for ActivityHandlerDialog
  sdk/csharp/libraries/microsoft.bot.solutions/Dialogs/ActivityHandlerDialog.cs
  sdk/csharp/libraries/microsoft.bot.solutions/IRemoteUserTokenProvider.cs
Labels: PR: reviewed-approved

#2940 Fix .ruleset file references for dotnet build tasks
  samples/csharp/assistants/enterprise-assistant/Directory.Build.props
  samples/csharp/assistants/hospitality-assistant/Directory.Build.props
  samples/csharp/assistants/virtual-assistant/Directory.Build.props
  samples/csharp/skill/Directory.Build.props
  samples/csharp/skill/VirtualAssistant.ruleset
  sdk/csharp/Directory.Build.props
  skills/csharp/Directory.Build.props
Labels: PR: reviewed-approved

#2941 [lib] MultiProviderAuth: Add verification for empty connection name
  sdk/csharp/libraries/microsoft.bot.solutions/Authentication/MultiProviderAuthDialog.cs
Labels: PR: unreviewed

#2918 Skill Documentation Updates
  docs/_docs/skills/handbook/add-skills-to-a-virtual-assistant.md
  docs/_docs/skills/handbook/architecture.md
  docs/_docs/skills/handbook/authentication.md
  docs/_docs/skills/handbook/best-practices.md
  docs/_docs/skills/handbook/botskills.md
  docs/_docs/skills/handbook/manifest.md
  docs/_docs/skills/samples/automotive.md
  docs/_docs/skills/samples/bing-search.md
  docs/_docs/skills/samples/calendar.md
  docs/_docs/skills/samples/email.md
  docs/_docs/skills/samples/hospitality.md
  docs/_docs/skills/samples/itsm.md
  docs/_docs/skills/samples/music.md
  docs/_docs/skills/samples/news.md
  docs/_docs/skills/samples/phone.md
  docs/_docs/skills/samples/restaurant-booking.md
  docs/_docs/skills/samples/to-do.md
  docs/_docs/skills/samples/weather.md
  docs/_docs/skills/tutorials/convert-v4-bot/csharp/1-intro.md
  docs/_docs/skills/tutorials/convert-v4-bot/csharp/2-add-packages.md
  docs/_docs/skills/tutorials/convert-v4-bot/csharp/3-skill-manifest.md
  docs/_docs/skills/tutorials/create-skill/csharp/1-intro.md
  docs/_docs/skills/tutorials/create-skill/csharp/2-download-and-install.md
  docs/_docs/skills/tutorials/create-skill/csharp/3-create-your-skill.md
  docs/_docs/skills/tutorials/create-skill/csharp/4-provision-your-azure-resources.md
  docs/_docs/skills/tutorials/create-skill/csharp/5-update-manifest.md
  docs/_docs/skills/tutorials/create-skill/csharp/6-run-your-skill.md
  docs/_docs/skills/tutorials/create-skill/csharp/7-add-your-skill.md
  docs/_docs/skills/tutorials/create-skill/csharp/8-invoke-your-skill.md
  docs/_docs/skills/tutorials/create-skill/csharp/9-next-steps.md
  docs/_docs/skills/tutorials/customize-skill/csharp/2-edit-your-responses.md
  docs/_docs/skills/tutorials/customize-skill/csharp/3-update-skill-manifest.md
  docs/_docs/skills/tutorials/extend-v4-bot/csharp/1-intro.md
  docs/_docs/skills/tutorials/extend-v4-bot/csharp/2-add-packages.md
  docs/_docs/skills/tutorials/extend-v4-bot/csharp/3-skill-configuration.md
  docs/_docs/skills/tutorials/extend-v4-bot/csharp/4-skill-dialog-registration.md
  docs/_docs/skills/tutorials/extend-v4-bot/csharp/5-forward-queries-to-skills.md
  docs/_docs/skills/tutorials/extend-v4-bot/typescript/1-intro.md
  docs/_docs/skills/tutorials/extend-v4-bot/typescript/2-add-packages.md
  docs/_docs/skills/tutorials/extend-v4-bot/typescript/3-skill-configuration.md
  docs/_docs/skills/tutorials/extend-v4-bot/typescript/4-skill-dialog-registration.md
  docs/_docs/skills/tutorials/extend-v4-bot/typescript/5-forward-queries-to-skills.md
  docs/_includes/nav.html
Labels: PR: reviewed-approved

#2942 Fix Calendar LU file issue
  skills/csharp/calendarskill/Deployment/Resources/LU/en-us/Calendar.lu
Labels: PR: reviewed-approved

#2943 update manifest with correct LU file reference
  samples/csharp/skill/SkillSample/wwwroot/manifest/manifest.json
  skills/csharp/calendarskill/wwwroot/manifest/manifest.json
  skills/csharp/emailskill/wwwroot/manifest/manifest.json
  skills/csharp/experimental/automotiveskill/wwwroot/manifest/manifest.json
  skills/csharp/experimental/bingsearchskill/wwwroot/manifest/manifest.json
  skills/csharp/experimental/hospitalityskill/wwwroot/manifest/manifest.json
  skills/csharp/experimental/itsmskill/wwwroot/manifest/manifest.json
  skills/csharp/experimental/musicskill/wwwroot/manifest/manifest.json
  skills/csharp/experimental/newsskill/wwwroot/manifest/manifest.json
  skills/csharp/experimental/phoneskill/wwwroot/manifest/manifest.json
  skills/csharp/experimental/restaurantbookingskill/wwwroot/manifest/manifest.json
  skills/csharp/experimental/weatherskill/wwwroot/manifest/manifest.json
  skills/csharp/pointofinterestskill/wwwroot/manifest/manifest.json
  skills/csharp/todoskill/wwwroot/manifest/manifest.json
Labels: PR: reviewed-approved

#2939 fix interruption logic for main dialog
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/skill/SkillSample/SkillSample.csproj
Labels: PR: reviewed-approved

#2944 [Lib]Fix input hint for LG response activity
  sdk/csharp/libraries/microsoft.bot.solutions/Responses/LocaleTemplateEngineManager.cs
Labels: PR: reviewed-approved

#2945 update solutions lib to latest
  skills/csharp/calendarskill/CalendarSkill.csproj
  skills/csharp/emailskill/EmailSkill.csproj
  skills/csharp/experimental/automotiveskill/AutomotiveSkill.csproj
  skills/csharp/experimental/bingsearchskill/BingSearchSkill.csproj
  skills/csharp/experimental/eventskill/EventSkill.csproj
  skills/csharp/experimental/hospitalityskill/HospitalitySkill.csproj
  skills/csharp/experimental/itsmskill/ITSMSkill.csproj
  skills/csharp/experimental/musicskill/MusicSkill.csproj
  skills/csharp/experimental/newsskill/NewsSkill.csproj
  skills/csharp/experimental/phoneskill/PhoneSkill.csproj
  skills/csharp/experimental/restaurantbookingskill/RestaurantBookingSkill.csproj
  skills/csharp/experimental/weatherskill/WeatherSkill.csproj
  skills/csharp/pointofinterestskill/PointOfInterestSkill.csproj
  skills/csharp/shared/SkillServiceLibrary/SkillServiceLibrary.csproj
  skills/csharp/todoskill/ToDoSkill.csproj
Labels: PR: reviewed-approved

#2946 [lib] remove tokens/request event
  sdk/csharp/libraries/microsoft.bot.solutions/TokenEvents.cs
Labels: PR: reviewed-approved

#2947 [Docs] Fix experimental link references with overview and add linked accounts info to Android
  docs/_docs/clients-and-channels/clients/virtual-assistant-client.md
  docs/_docs/help/faq.md
  docs/_docs/overview/skills.md
  docs/_docs/skills/tutorials/add-prebuilt-skill/3-deploy-skill-project.md
  docs/_docs/skills/tutorials/add-prebuilt-skill/5-test-your-skill.md
  docs/_docs/solution-accelerators/assistants/enterprise-assistant.md
  docs/_docs/solution-accelerators/assistants/hospitality-assistant.md
  docs/assets/images/android-virtual-assistant-client-side-menu-signin.png
  docs/assets/images/android-virtual-assistant-client-side-menu-signout.png
  docs/assets/images/linked-accounts-linked.jpg
  docs/assets/images/linked-accounts-unlinked.jpg
Labels: PR: reviewed-approved

#2949 Adding additional manifest for 2.0 and 2.1
  samples/csharp/skill/SkillSample/wwwroot/manifest/manifest-1.0.json
  samples/csharp/skill/SkillSample/wwwroot/manifest/manifest-1.1.json
Labels: PR: reviewed-approved

#2950 [Templates] Update skill manifests
  templates/csharp/Skill/Skill/SkillProjectTemplate.vstemplate
  templates/csharp/Skill/Skill/wwwroot/manifest/manifest-1.0.json
  templates/csharp/Skill/Skill/wwwroot/manifest/manifest-1.1.json
Labels: PR: reviewed-approved

#2951 [Templates] Updated manifest files with parameters
  templates/csharp/Skill/Skill/wwwroot/manifest/manifest-1.0.json
  templates/csharp/Skill/Skill/wwwroot/manifest/manifest-1.1.json
Labels: PR: reviewed-approved
